-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[DATA_02]
-- // MODULO:			QA INSPECCION DE MATERIAL
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	20/AGO/2020
-- //////////////////////////////////////////////////////////////  

USE [DATA_02]
GO

-- //////////////////////////////////////////////////////////////



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_INCINSP_SQL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_INCINSP_SQL]
GO
/*
 EXEC	[dbo].[PG_LI_INCINSP_SQL] 0,0, '', '2021/03/10', '2021/03/15', '( TODOS )', '( TODOS )', '( TODOS )'--, '( TODOS )'
*/


CREATE PROCEDURE [dbo].[PG_LI_INCINSP_SQL]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_BUSCAR					VARCHAR(200),
	-- ===========================
	@PP_F_INICIO				DATE,
	@PP_F_FIN					DATE,
	@PP_COLOR					VARCHAR(50),
	@PP_ESTATUS					VARCHAR(50),
	@PP_DEFECTO					VARCHAR(50)
AS

	-- ///////////////////////////////////////////
	DECLARE @TBL_INSPECCION_LOTE_PIEL TABLE(
		K_INSPECCION_LOTE		INT,
		FECHA					DATE,
		PACKING_NO				VARCHAR(50),
		COLOR					VARCHAR(100),
		D_COLOR					VARCHAR(150),
		K_ITEM					VARCHAR(10),
		LOTE					VARCHAR(50),
		CANTIDAD_LOTE			INT,
		CANTIDAD_MUESTRA		INT,
		THICKNESS				VARCHAR(10),
		DEFECTO					VARCHAR(255),
		ESTATUS					VARCHAR(50),
		F_INSPECCION			VARCHAR(50),
		USUARIO_INSPECCION		VARCHAR(50)
	) 

	-- ///////////////////////////////////////////
	INSERT INTO @TBL_INSPECCION_LOTE_PIEL
		SELECT	ID					AS K_INSPECCION_LOTE,
				[dbo].[CONVERT_INT_TO_DATE]([Date])	AS FECHA,
				PACKING_NO,
				LTRIM(RTRIM(Description)) AS COLOR,
				LTRIM(RTRIM(item_desc_1)) AS D_COLOR,
				upc_cd				AS K_ITEM,
				LTRIM(RTRIM(Lot))	AS LOTE,
				IncInsp_sql.Lot_size AS CANTIDAD_LOTE,
				Sample_size			AS CANTIDAD_MUESTRA,
				Thickness			AS THICKNESS,
				Defecto				AS DEFECTO,
				( CASE WHEN STATUS = 'C' AND [K_ESTATUS_INSPECCION_LOTE_PIEL] IS NULL THEN 'ACEPTADO'
					WHEN STATUS <> 'C' AND [K_ESTATUS_INSPECCION_LOTE_PIEL] IS NULL THEN 'PENDIENTE'
					WHEN [K_ESTATUS_INSPECCION_LOTE_PIEL] = 1 THEN 'INSPECCIONADO'
					WHEN [K_ESTATUS_INSPECCION_LOTE_PIEL] = 2 THEN 'REVISION'
					WHEN [K_ESTATUS_INSPECCION_LOTE_PIEL] = 3 THEN 'ACEPTADO'
					WHEN [K_ESTATUS_INSPECCION_LOTE_PIEL] = 4 THEN 'RECHAZADO'
				END ) AS ESTATUS,
				-- ===========================
			(CASE WHEN F_INSPECCION_LOTE_PIEL_RESULTADO IS NULL THEN '-'
				ELSE CONVERT(VARCHAR(10),F_INSPECCION_LOTE_PIEL_RESULTADO, 5) END) AS F_INSPECCION,
			-- =============================	
			(CASE WHEN [INSPECCION_LOTE_PIEL_RESULTADO].K_USUARIO_ALTA IS NULL THEN '-'
				ELSE (	SELECT D_USUARIO_PEARL 
						FROM BD_GENERAL.DBO.USUARIO_PEARL 
						WHERE K_USUARIO_PEARL =  [INSPECCION_LOTE_PIEL_RESULTADO].K_USUARIO_ALTA ) END ) AS USUARIO_INSPECCION
		FROM	IncInsp_sql (NOLOCK)
		INNER JOIN	IMITMIDX_SQL (NOLOCK) ON  LTRIM(RTRIM(ITEM_NO)) =  [Description]
		LEFT JOIN	[INSPECCION_LOTE_PIEL_RESULTADO] (NOLOCK) ON K_IMPORTACION_LOTE_PIEL = ID 
				AND	RIGHT('000000' + LTRIM(RTRIM(LOTE)), 6)  = LTRIM(RTRIM(Lot))
				AND K_ITEM = upc_cd
		WHERE 	( LOT				LIKE '%'+@PP_BUSCAR+'%'
				OR	PACKING_NO		LIKE '%'+@PP_BUSCAR+'%'
				OR	ID		LIKE '%'+@PP_BUSCAR+'%' )
		-- =============================
		AND		[DATE] >= [dbo].[CONVERT_DATE_TO_INT](@PP_F_INICIO, 'yyyyMMdd')
		AND		[DATE] <= [dbo].[CONVERT_DATE_TO_INT](@PP_F_FIN, 'yyyyMMdd') 	
		AND		( @PP_COLOR = '( TODOS )'		OR	LTRIM(RTRIM([Description])) = @PP_COLOR  )
		AND		( @PP_DEFECTO = '( TODOS )'		OR	LTRIM(RTRIM(Defecto)) = @PP_DEFECTO )
		ORDER BY	[DATE]	DESC

	SELECT	K_INSPECCION_LOTE,
			FECHA,
			PACKING_NO,
			COLOR,				
			D_COLOR,				
			K_ITEM,			
			LOTE,			
			CANTIDAD_LOTE,		
			CANTIDAD_MUESTRA,	
			THICKNESS,			
			DEFECTO,				
			ESTATUS,				
			F_INSPECCION,		
			USUARIO_INSPECCION	
	FROM @TBL_INSPECCION_LOTE_PIEL
	WHERE ( @PP_ESTATUS = '( TODOS )'		OR	ESTATUS = @PP_ESTATUS )
	ORDER BY FECHA ASC
	
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INCINSP_SQL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INCINSP_SQL]
GO
/*
 EXEC	[dbo].[PG_SK_INCINSP_SQL] 0,0, 5635
 EXEC	[dbo].[PG_SK_INCINSP_SQL] 0,0, 5634
*/


CREATE PROCEDURE [dbo].[PG_SK_INCINSP_SQL]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_INSPECCION_LOTE			INT
AS

	-- //////////SE VALIDA SI EXISTE LA INSPECCION TIPO GROOS/////////////////////////////////
	DECLARE @VP_N_INSPECCION_GROSS INT = 0

	SELECT @VP_N_INSPECCION_GROSS = COUNT([K_INSPECCION_LOTE_PIEL]) 
	FROM [INSPECCION_LOTE_PIEL] (NOLOCK)
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON  INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = [INSPECCION_LOTE_PIEL].K_INSPECCION_MATERIAL
	WHERE K_IMPORTACION_LOTE_PIEL =  @PP_K_INSPECCION_LOTE
	AND K_TIPO_INSPECCION_MATERIAL = 5 --# GROSS

	IF @VP_N_INSPECCION_GROSS IS NULL
		SET @VP_N_INSPECCION_GROSS = 0

	-- //////////SE VALIDA SI EXISTE LA INSPECCION TIPO SUAVIDAD/////////////////////////////////
	DECLARE @VP_N_INSPECCION_SUAVIDAD INT = 0
	SELECT @VP_N_INSPECCION_SUAVIDAD = COUNT([K_INSPECCION_LOTE_PIEL]) 
	FROM [INSPECCION_LOTE_PIEL] (NOLOCK)
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON  INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = [INSPECCION_LOTE_PIEL].K_INSPECCION_MATERIAL
	WHERE K_IMPORTACION_LOTE_PIEL =  @PP_K_INSPECCION_LOTE
	AND K_TIPO_INSPECCION_MATERIAL = 6 --# SUAVIDAD

	IF @VP_N_INSPECCION_SUAVIDAD IS NULL
		SET @VP_N_INSPECCION_SUAVIDAD = 0

	-- ///////////////////////////////////////////
	SELECT	ID						AS K_INSPECCION_LOTE,
			[dbo].[CONVERT_INT_TO_DATE]([Date])	AS FECHA,
			PACKING_NO,
			LTRIM(RTRIM(Lot))		AS LOTE,
			LTRIM(RTRIM(Description)) AS COLOR,
			LTRIM(RTRIM(item_desc_1)) AS D_COLOR,
			upc_cd					AS K_ITEM,
			IncInsp_sql.Lot_size	AS CANTIDAD_LOTE,
			Sample_size				AS CANTIDAD_MUESTRA,
			Thickness				AS THICKNESS,
			Defecto					AS DEFECTO,
			-- ===========================
			( CASE WHEN STATUS = 'C' AND [K_ESTATUS_INSPECCION_LOTE_PIEL] IS NULL THEN 'ACEPTADO'
					WHEN STATUS <> 'C' AND [K_ESTATUS_INSPECCION_LOTE_PIEL] IS NULL THEN 'PENDIENTE'
					WHEN [K_ESTATUS_INSPECCION_LOTE_PIEL] = 1 THEN 'INSPECCIONADO'
					WHEN [K_ESTATUS_INSPECCION_LOTE_PIEL] = 2 THEN 'REVISION'
					WHEN [K_ESTATUS_INSPECCION_LOTE_PIEL] = 3 THEN 'ACEPTADO'
					WHEN [K_ESTATUS_INSPECCION_LOTE_PIEL] = 4 THEN 'RECHAZADO'
				END ) AS ESTATUS,
			-- ===========================
			@VP_N_INSPECCION_GROSS		AS N_INSPECCION_GROSS,
			@VP_N_INSPECCION_SUAVIDAD	AS N_INSPECCION_SUAVIDAD
	FROM	IncInsp_sql (NOLOCK)
	INNER JOIN IMITMIDX_SQL (NOLOCK) ON  LTRIM(RTRIM(ITEM_NO)) =  [Description]
	LEFT JOIN	[INSPECCION_LOTE_PIEL_RESULTADO] (NOLOCK) ON K_IMPORTACION_LOTE_PIEL = ID 
				AND	RIGHT('000000' + LTRIM(RTRIM(LOTE)), 6) = LTRIM(RTRIM(Lot))
				AND K_ITEM = upc_cd
	WHERE 	ID = @PP_K_INSPECCION_LOTE

	
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- USE DATA_02 --PRUEBAS
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_PIEL_X_LOTE_CON_OPCION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_PIEL_X_LOTE_CON_OPCION]
GO
 
/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_1_PDF] 0, 144,   7020 , 2477 , 450321 , 5 , 1 --#5 GROSS/THICKNESS #6 SUAVIDAD
 EXEC	[dbo].[PG_SK_INSPECCION_PIEL_X_LOTE_CON_OPCION] 0, 144 ,  7020 , 2477 , 450321 , 0 , 1 , 1 
 EXEC	[dbo].[PG_SK_INSPECCION_PIEL_X_LOTE_CON_OPCION] 0, 144 ,  5635 , 1191 , 107791 , 31 , 0 , 0
 EXEC	[dbo].[PG_SK_INSPECCION_PIEL_X_LOTE_CON_OPCION] 0, 144 , 7031, 2477 , 450321 , 370 , 0 , 2 
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_PIEL_X_LOTE_CON_OPCION]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_INSPECCION_MATERIAL		INT,
	@PP_PRIMER_INSPECCION			INT, --#0 Cuando se abre ficha, #1 cuando se oprime adelande o atras 
	@PP_TIPO_MOVIMIENTO				INT --#0 ANTERIOR, #1 SIGUIENTE
AS

	-- ////////////////////////////////////////////////
	DECLARE @VP_POSICION_INSPECCION INT = 0
	DECLARE @VP_N_INSPECCION_X_ITEM INT = 0
	SELECT @VP_N_INSPECCION_X_ITEM = COUNT(K_INSPECCION_MATERIAL)
	FROM INSPECCION_MATERIAL (NOLOCK)
	WHERE K_ITEM = @PP_K_ITEM
	AND		INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = 1 -- ACTIVA

	IF @VP_N_INSPECCION_X_ITEM IS NULL
		SET @VP_N_INSPECCION_X_ITEM = 0
		
	-- ////////////////////////////////////////////////
	IF @PP_TIPO_MOVIMIENTO = 1 -- SIGUIENTE
		SELECT	TOP 1
				INSPECCION_MATERIAL.*,
				INSPECCION_OPCION.*,
				D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
				D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
				K_USUARIO_PEARL AS D_USUARIO_CAMBIO,
				ISNULL(OPCION_SELECCIONADA, '') AS OPCION_SELECCIONADA,
				ISNULL(ACEPTADO, '') AS ACEPTADO,
				ISNULL(COMENTARIO, '') AS COMENTARIO,
				@VP_N_INSPECCION_X_ITEM AS TOTAL_INSPECCION,
				@VP_POSICION_INSPECCION	AS POSICION_INSPECCION
				-- =============================	
		FROM	INSPECCION_MATERIAL (NOLOCK)
				-- =============================
				INNER JOIN ESTATUS_INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL
				INNER JOIN TIPO_INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
				INNER JOIN INSPECCION_OPCION (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
				INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL (NOLOCK) ON INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
				-- =============================
				LEFT  JOIN INSPECCION_LOTE_PIEL (NOLOCK) ON INSPECCION_LOTE_PIEL.K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
						AND INSPECCION_LOTE_PIEL.K_ITEM = INSPECCION_MATERIAL.K_ITEM
						AND	INSPECCION_LOTE_PIEL.K_IMPORTACION_LOTE_PIEL = @PP_K_LOTE_IMPORTACION
						AND INSPECCION_LOTE_PIEL.LOTE = @PP_LOTE
				-- =============================
		WHERE	INSPECCION_MATERIAL.K_ITEM=@PP_K_ITEM
		AND		INSPECCION_MATERIAL.K_INSPECCION_MATERIAL > ( CASE	WHEN @PP_PRIMER_INSPECCION = 1	THEN 0
															ELSE @PP_K_INSPECCION_MATERIAL END )
		-- =============================
		AND		ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = 1 -- ACTIVA
		-- =============================
		ORDER BY INSPECCION_MATERIAL.K_INSPECCION_MATERIAL ASC

	-- ////////////////////////////////////////////////
	IF @PP_TIPO_MOVIMIENTO = 0 -- ANTERIOR
		SELECT	TOP 1
				INSPECCION_MATERIAL.*,
				INSPECCION_OPCION.*,
				D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
				D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
				K_USUARIO_PEARL AS D_USUARIO_CAMBIO,
				ISNULL(OPCION_SELECCIONADA, '') AS OPCION_SELECCIONADA,
				ISNULL(ACEPTADO, '') AS ACEPTADO,
				ISNULL(COMENTARIO, '') AS COMENTARIO,
				@VP_N_INSPECCION_X_ITEM AS TOTAL_INSPECCION,
				@VP_POSICION_INSPECCION	AS POSICION_INSPECCION
				-- =============================	
		FROM	INSPECCION_MATERIAL (NOLOCK)
				-- =============================
				INNER JOIN ESTATUS_INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL
				INNER JOIN TIPO_INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
				INNER JOIN INSPECCION_OPCION (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
				INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL (NOLOCK) ON INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
				-- =============================
				LEFT  JOIN INSPECCION_LOTE_PIEL (NOLOCK) ON INSPECCION_LOTE_PIEL.K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
						AND INSPECCION_LOTE_PIEL.K_ITEM = INSPECCION_MATERIAL.K_ITEM
						AND	INSPECCION_LOTE_PIEL.K_IMPORTACION_LOTE_PIEL = @PP_K_LOTE_IMPORTACION
						AND INSPECCION_LOTE_PIEL.LOTE = @PP_LOTE
				-- =============================
		WHERE	INSPECCION_MATERIAL.K_ITEM=@PP_K_ITEM
		AND		INSPECCION_MATERIAL.K_INSPECCION_MATERIAL < ( CASE	WHEN @PP_PRIMER_INSPECCION = 1	THEN 0
																	ELSE @PP_K_INSPECCION_MATERIAL END )
		-- =============================
		AND		ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = 1 -- ACTIVA
		-- =============================
		ORDER BY INSPECCION_MATERIAL.K_INSPECCION_MATERIAL DESC


		-- ////////////////////////////////////////////////
	IF @PP_TIPO_MOVIMIENTO = 2 -- PARA ACTUALIZAR INSPECCION
		BEGIN
			SELECT @VP_POSICION_INSPECCION = COUNT(K_INSPECCION_MATERIAL) 
			FROM INSPECCION_MATERIAL (NOLOCK)
			WHERE K_ITEM = @PP_K_ITEM AND K_ESTATUS_INSPECCION_MATERIAL = 1 
			AND K_INSPECCION_MATERIAL <= @PP_K_INSPECCION_MATERIAL
						
			SELECT	TOP 1
					INSPECCION_MATERIAL.*,
					INSPECCION_OPCION.*,
					D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
					D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
					K_USUARIO_PEARL AS D_USUARIO_CAMBIO,
					ISNULL(OPCION_SELECCIONADA, '') AS OPCION_SELECCIONADA,
					ISNULL(ACEPTADO, '') AS ACEPTADO,
					ISNULL(COMENTARIO, '') AS COMENTARIO,
					@VP_N_INSPECCION_X_ITEM AS TOTAL_INSPECCION,
					@VP_POSICION_INSPECCION	AS POSICION_INSPECCION
					-- =============================	
			FROM	INSPECCION_MATERIAL (NOLOCK)
					-- =============================
					INNER JOIN ESTATUS_INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL
					INNER JOIN TIPO_INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
					INNER JOIN INSPECCION_OPCION (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
					INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL (NOLOCK) ON INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
					-- =============================
					LEFT  JOIN INSPECCION_LOTE_PIEL (NOLOCK) ON INSPECCION_LOTE_PIEL.K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
							AND INSPECCION_LOTE_PIEL.K_ITEM = INSPECCION_MATERIAL.K_ITEM
							AND	INSPECCION_LOTE_PIEL.K_IMPORTACION_LOTE_PIEL = @PP_K_LOTE_IMPORTACION
							AND INSPECCION_LOTE_PIEL.LOTE = @PP_LOTE
					-- =============================
			WHERE	INSPECCION_MATERIAL.K_ITEM = @PP_K_ITEM
			AND		INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL 
			-- =============================
			ORDER BY INSPECCION_MATERIAL.K_INSPECCION_MATERIAL DESC
		END
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_INSPECCION_LOTE_PIEL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_INSPECCION_LOTE_PIEL]
GO

/*
 EXEC	[dbo].[PG_LI_INSPECCION_LOTE_PIEL] 0, 144,  5635 , 1191 , 107791 
 EXEC	[dbo].[PG_LI_INSPECCION_LOTE_PIEL] 0, 144,  5634 , 1191 , 900101 
*/

CREATE PROCEDURE [dbo].[PG_LI_INSPECCION_LOTE_PIEL]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT
	
AS

	-- ///////////////////////////////////////////
	SELECT	
			[INSPECCION_LOTE_PIEL].*,
			D_USUARIO_PEARL AS D_USUARIO_CAMBIO,
			INSPECCION_MATERIAL.*,
			INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL,
			LTRIM(RTRIM([DESCRIPTION])) AS COLOR,
			IncInsp_sql.Lot_size	AS CANTIDAD_LOTE
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL] (NOLOCK)
	INNER JOIN IncInsp_sql (NOLOCK) ON ID = K_IMPORTACION_LOTE_PIEL
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON [INSPECCION_LOTE_PIEL].K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
			AND [INSPECCION_LOTE_PIEL].K_ITEM = INSPECCION_MATERIAL.K_ITEM
	INNER JOIN	TIPO_INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL (NOLOCK) ON [INSPECCION_LOTE_PIEL].K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		[INSPECCION_LOTE_PIEL].K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL] 0, 144,  5635 , 1191 , 107791 , 28 
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_INSPECCION_MATERIAL		INT
	
AS

	-- ///////////////////////////////////////////
	SELECT	
			[INSPECCION_LOTE_PIEL].*,
			INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL] (NOLOCK)
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON [INSPECCION_LOTE_PIEL].K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
			AND [INSPECCION_LOTE_PIEL].K_ITEM = INSPECCION_MATERIAL.K_ITEM
	INNER JOIN	TIPO_INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		[INSPECCION_LOTE_PIEL].K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		[INSPECCION_LOTE_PIEL].K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////
 -- USE DATA_02
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_1_PDF]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_1_PDF]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_1_PDF] 0, 144,   7020 , 2477 , 450321 , 5 , 1 --#5 GROSS/THICKNESS #6 SUAVIDAD
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_1_PDF] 0, 144,   5634 , 1191 , 900101 , 5 , 1 --#5 GROSS/THICKNESS #6 SUAVIDAD
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_1_PDF]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_TIPO_INSPECCION_MATERIAL	INT,
	@PP_POSICION_PIEL_1				INT
	
AS

	-- ///////OBTIENE EL VALOR DEL GORSS - SUAVIDAD QUE MAS SE REPITE//////////////////
	DECLARE @VP_VALOR_REPETIDO DECIMAL(13,2) = 0,  @VP_N_VALOR_REPETIDO INT = 0;

	SET NOCOUNT ON
	SELECT TOP 1 @VP_VALOR_REPETIDO = [VALOR], 
			@VP_N_VALOR_REPETIDO = COUNT(*) 
	FROM INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD (NOLOCK)
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = [INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].K_INSPECCION_MATERIAL
	WHERE [K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD.K_ITEM = @PP_K_ITEM
	AND LOTE = @PP_LOTE
	AND K_TIPO_INSPECCION_MATERIAL = @PP_K_TIPO_INSPECCION_MATERIAL			
	GROUP BY [VALOR]
	ORDER BY COUNT(*) DESC

	-- ///////OBTIENE EL VALOR MINIMO Y MAXIMO CONFIGURADO DEL GORSS - SUAVIDAD//////////////////
	DECLARE @VP_VALOR_MINIMO VARCHAR(10) = '', @VP_VALOR_MAXIMO VARCHAR(10) = '';
	SELECT	@VP_VALOR_MINIMO = OPCION_1,
			@VP_VALOR_MAXIMO = OPCION_2
	FROM INSPECCION_OPCION (NOLOCK)
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
	WHERE K_ITEM = @PP_K_ITEM
	AND K_TIPO_INSPECCION_MATERIAL = @PP_K_TIPO_INSPECCION_MATERIAL
	AND K_ESTATUS_INSPECCION_MATERIAL = 1 --ACTIVA

	-- ///////SE CREA LA TABLA TEMPORAL PARA OBTENER LOS DATOS COMO COLUMNAS//////////////////
	DECLARE @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1 TABLE(		
		[POSICION_PIEL]				INT,
		[PIEL]						INT,
		[K_INSPECCION_MATERIAL]		INT,
		[VALOR_ZONA_A]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_B]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_C]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_D]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_E]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_F]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_G]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_H]				VARCHAR(20) DEFAULT ''
		)
			
	-- ///////SE DECLARAN LAS VARIABLES A USAR//////////////////
	DECLARE @VP_POSICION_PIEL	INT = 0, @VP_PIEL INT = 0, @VP_K_INSPECCION_MATERIAL INT = 0, @VP_ZONA	VARCHAR(10) = '', @VP_VALOR VARCHAR(10) = ''
	DECLARE @VP_VALOR_ZONA_A VARCHAR(20) = '', @VP_VALOR_ZONA_B VARCHAR(20) = '', @VP_VALOR_ZONA_C VARCHAR(20) = ''
	DECLARE @VP_VALOR_ZONA_D VARCHAR(20) = '', @VP_VALOR_ZONA_E VARCHAR(20) = '', @VP_VALOR_ZONA_F VARCHAR(20) = '' 
	DECLARE @VP_VALOR_ZONA_G VARCHAR(20) = '', @VP_VALOR_ZONA_H VARCHAR(20) = ''

	DECLARE CU_GROSS_SUAVIDAD_PIEL_1 CURSOR 
	FOR SELECT	[POSICION_PIEL],			
				[PIEL],					
				[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].[K_INSPECCION_MATERIAL],
				ZONA,
				VALOR
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] (NOLOCK)
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = [INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].K_INSPECCION_MATERIAL
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		K_TIPO_INSPECCION_MATERIAL = @PP_K_TIPO_INSPECCION_MATERIAL
	AND		[POSICION_PIEL] = @PP_POSICION_PIEL_1
	ORDER BY ZONA ASC
	
	OPEN CU_GROSS_SUAVIDAD_PIEL_1
	FETCH NEXT FROM CU_GROSS_SUAVIDAD_PIEL_1 INTO @VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, @VP_ZONA, @VP_VALOR
	
	WHILE @@FETCH_STATUS = 0
		BEGIN
			IF @VP_ZONA = 'A'
				SET @VP_VALOR_ZONA_A = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'B'
				SET @VP_VALOR_ZONA_B = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'C'
				SET @VP_VALOR_ZONA_C = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'D'
				SET @VP_VALOR_ZONA_D = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'E'
				SET @VP_VALOR_ZONA_E = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'F'
				SET @VP_VALOR_ZONA_F = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'G'
				SET @VP_VALOR_ZONA_G = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'H'
				SET @VP_VALOR_ZONA_H = CONVERT(VARCHAR(20), @VP_VALOR)

			FETCH NEXT FROM CU_GROSS_SUAVIDAD_PIEL_1 INTO @VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, @VP_ZONA, @VP_VALOR
									
		END
	CLOSE CU_GROSS_SUAVIDAD_PIEL_1
	DEALLOCATE CU_GROSS_SUAVIDAD_PIEL_1

	INSERT INTO @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1
	SELECT	@VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, 
			@VP_VALOR_ZONA_A, @VP_VALOR_ZONA_B, @VP_VALOR_ZONA_C, @VP_VALOR_ZONA_D,
			@VP_VALOR_ZONA_E, @VP_VALOR_ZONA_F, @VP_VALOR_ZONA_G, @VP_VALOR_ZONA_H
	SET NOCOUNT OFF	

	-- //////////////////////////////////////////////////
	SELECT [POSICION_PIEL],			
		   (CASE WHEN PIEL <> 0 THEN RIGHT('0000' + CONVERT(VARCHAR(4), PIEL), 4) 
				ELSE '' END) AS N_PIEL,					
		   [K_INSPECCION_MATERIAL],
		   [VALOR_ZONA_A],			
		   [VALOR_ZONA_B],			
		   [VALOR_ZONA_C],			
		   [VALOR_ZONA_D],			
		   [VALOR_ZONA_E],			
		   [VALOR_ZONA_F],			
		   [VALOR_ZONA_G],			
		   [VALOR_ZONA_H],	
		   @VP_VALOR_REPETIDO AS AVG_GROS_SUAVIDAD,
		   @VP_VALOR_MINIMO	AS VALOR_MINIMO,
		   @VP_VALOR_MAXIMO	AS VALOR_MAXIMO
	FROM @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_2_PDF]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_2_PDF]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_2_PDF] 0, 144,   5635 , 1191 , 107791 , 5 , 2 --#5 GROSS/THICKNESS #6 SUAVIDAD
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_2_PDF]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_TIPO_INSPECCION_MATERIAL	INT,
	@PP_POSICION_PIEL_2				INT
	
AS
	-- ///////SE CREA LA TABLA TEMPORAL PARA OBTENER LOS DATOS COMO COLUMNAS//////////////////
	DECLARE @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1 TABLE(		
		[POSICION_PIEL]				INT,
		[PIEL]						INT,
		[K_INSPECCION_MATERIAL]		INT,
		[VALOR_ZONA_A]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_B]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_C]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_D]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_E]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_F]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_G]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_H]				VARCHAR(20) DEFAULT ''
		)
			
	-- ///////SE DECLARAN LAS VARIABLES A USAR//////////////////
	DECLARE @VP_POSICION_PIEL	INT = 0, @VP_PIEL INT = 0, @VP_K_INSPECCION_MATERIAL INT = 0, @VP_ZONA	VARCHAR(10) = '', @VP_VALOR VARCHAR(10) = ''
	DECLARE @VP_VALOR_ZONA_A VARCHAR(20) = '', @VP_VALOR_ZONA_B VARCHAR(20) = '', @VP_VALOR_ZONA_C VARCHAR(20) = ''
	DECLARE @VP_VALOR_ZONA_D VARCHAR(20) = '', @VP_VALOR_ZONA_E VARCHAR(20) = '', @VP_VALOR_ZONA_F VARCHAR(20) = '' 
	DECLARE @VP_VALOR_ZONA_G VARCHAR(20) = '', @VP_VALOR_ZONA_H VARCHAR(20) = ''

	DECLARE CU_GROSS_SUAVIDAD_PIEL_1 CURSOR 
	FOR SELECT	[POSICION_PIEL],			
				[PIEL],					
				[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].[K_INSPECCION_MATERIAL],
				ZONA,
				VALOR
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] (NOLOCK)
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = [INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].K_INSPECCION_MATERIAL
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		K_TIPO_INSPECCION_MATERIAL = @PP_K_TIPO_INSPECCION_MATERIAL
	AND		[POSICION_PIEL] = @PP_POSICION_PIEL_2
	ORDER BY ZONA ASC
	
	OPEN CU_GROSS_SUAVIDAD_PIEL_1
	FETCH NEXT FROM CU_GROSS_SUAVIDAD_PIEL_1 INTO @VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, @VP_ZONA, @VP_VALOR
	
	WHILE @@FETCH_STATUS = 0
		BEGIN
			IF @VP_ZONA = 'A'
				SET @VP_VALOR_ZONA_A = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'B'
				SET @VP_VALOR_ZONA_B = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'C'
				SET @VP_VALOR_ZONA_C = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'D'
				SET @VP_VALOR_ZONA_D = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'E'
				SET @VP_VALOR_ZONA_E = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'F'
				SET @VP_VALOR_ZONA_F = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'G'
				SET @VP_VALOR_ZONA_G = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'H'
				SET @VP_VALOR_ZONA_H = CONVERT(VARCHAR(20), @VP_VALOR)

			FETCH NEXT FROM CU_GROSS_SUAVIDAD_PIEL_1 INTO @VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, @VP_ZONA, @VP_VALOR
									
		END
	CLOSE CU_GROSS_SUAVIDAD_PIEL_1
	DEALLOCATE CU_GROSS_SUAVIDAD_PIEL_1

	INSERT INTO @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1
	SELECT	@VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, 
			@VP_VALOR_ZONA_A, @VP_VALOR_ZONA_B, @VP_VALOR_ZONA_C, @VP_VALOR_ZONA_D,
			@VP_VALOR_ZONA_E, @VP_VALOR_ZONA_F, @VP_VALOR_ZONA_G, @VP_VALOR_ZONA_H

	-- //////////////////////////////////////////////////
	SELECT [POSICION_PIEL],			
		   (CASE WHEN PIEL <> 0 THEN RIGHT('0000' + CONVERT(VARCHAR(4), PIEL), 4) 
				ELSE '' END) AS N_PIEL,								
		   [K_INSPECCION_MATERIAL],
		   [VALOR_ZONA_A],			
		   [VALOR_ZONA_B],			
		   [VALOR_ZONA_C],			
		   [VALOR_ZONA_D],			
		   [VALOR_ZONA_E],			
		   [VALOR_ZONA_F],			
		   [VALOR_ZONA_G],			
		   [VALOR_ZONA_H],	
		   0 AS AVG_GROS_SUAVIDAD 
	FROM @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_3_PDF]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_3_PDF]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_3_PDF] 0, 144,   5635 , 1191 , 107791 , 5 , 3 --#5 GROSS/THICKNESS #6 SUAVIDAD
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_3_PDF]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_TIPO_INSPECCION_MATERIAL	INT,
	@PP_POSICION_PIEL_3				INT
	
AS

	-- ///////SE CREA LA TABLA TEMPORAL PARA OBTENER LOS DATOS COMO COLUMNAS//////////////////
	DECLARE @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1 TABLE(		
		[POSICION_PIEL]				INT,
		[PIEL]						INT,
		[K_INSPECCION_MATERIAL]		INT,
		[VALOR_ZONA_A]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_B]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_C]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_D]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_E]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_F]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_G]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_H]				VARCHAR(20) DEFAULT ''
		)
			
	-- ///////SE DECLARAN LAS VARIABLES A USAR//////////////////
	DECLARE @VP_POSICION_PIEL	INT = 0, @VP_PIEL INT = 0, @VP_K_INSPECCION_MATERIAL INT = 0, @VP_ZONA	VARCHAR(10) = '', @VP_VALOR VARCHAR(10) = ''
	DECLARE @VP_VALOR_ZONA_A VARCHAR(20) = '', @VP_VALOR_ZONA_B VARCHAR(20) = '', @VP_VALOR_ZONA_C VARCHAR(20) = ''
	DECLARE @VP_VALOR_ZONA_D VARCHAR(20) = '', @VP_VALOR_ZONA_E VARCHAR(20) = '', @VP_VALOR_ZONA_F VARCHAR(20) = '' 
	DECLARE @VP_VALOR_ZONA_G VARCHAR(20) = '', @VP_VALOR_ZONA_H VARCHAR(20) = ''

	DECLARE CU_GROSS_SUAVIDAD_PIEL_1 CURSOR 
	FOR SELECT	[POSICION_PIEL],			
				[PIEL],					
				[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].[K_INSPECCION_MATERIAL],
				ZONA,
				VALOR
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] (NOLOCK)
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = [INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].K_INSPECCION_MATERIAL
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		K_TIPO_INSPECCION_MATERIAL = @PP_K_TIPO_INSPECCION_MATERIAL
	AND		[POSICION_PIEL] = @PP_POSICION_PIEL_3
	ORDER BY ZONA ASC
	
	OPEN CU_GROSS_SUAVIDAD_PIEL_1
	FETCH NEXT FROM CU_GROSS_SUAVIDAD_PIEL_1 INTO @VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, @VP_ZONA, @VP_VALOR
	
	WHILE @@FETCH_STATUS = 0
		BEGIN
			IF @VP_ZONA = 'A'
				SET @VP_VALOR_ZONA_A = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'B'
				SET @VP_VALOR_ZONA_B = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'C'
				SET @VP_VALOR_ZONA_C = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'D'
				SET @VP_VALOR_ZONA_D = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'E'
				SET @VP_VALOR_ZONA_E = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'F'
				SET @VP_VALOR_ZONA_F = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'G'
				SET @VP_VALOR_ZONA_G = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'H'
				SET @VP_VALOR_ZONA_H = CONVERT(VARCHAR(20), @VP_VALOR)

			FETCH NEXT FROM CU_GROSS_SUAVIDAD_PIEL_1 INTO @VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, @VP_ZONA, @VP_VALOR
									
		END
	CLOSE CU_GROSS_SUAVIDAD_PIEL_1
	DEALLOCATE CU_GROSS_SUAVIDAD_PIEL_1

	INSERT INTO @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1
	SELECT	@VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, 
			@VP_VALOR_ZONA_A, @VP_VALOR_ZONA_B, @VP_VALOR_ZONA_C, @VP_VALOR_ZONA_D,
			@VP_VALOR_ZONA_E, @VP_VALOR_ZONA_F, @VP_VALOR_ZONA_G, @VP_VALOR_ZONA_H

	-- //////////////////////////////////////////////////
	SELECT [POSICION_PIEL],			
		   (CASE WHEN PIEL <> 0 THEN RIGHT('0000' + CONVERT(VARCHAR(4), PIEL), 4) 
				ELSE '' END) AS N_PIEL,						
		   [K_INSPECCION_MATERIAL],
		   [VALOR_ZONA_A],			
		   [VALOR_ZONA_B],			
		   [VALOR_ZONA_C],			
		   [VALOR_ZONA_D],			
		   [VALOR_ZONA_E],			
		   [VALOR_ZONA_F],			
		   [VALOR_ZONA_G],			
		   [VALOR_ZONA_H],	
		   0 AS AVG_GROS_SUAVIDAD 
	FROM @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_4_PDF]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_4_PDF]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_4_PDF] 0, 144,   5635 , 1191 , 107791 , 5 , 4 --#5 GROSS/THICKNESS #6 SUAVIDAD
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_4_PDF]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_TIPO_INSPECCION_MATERIAL	INT,
	@PP_POSICION_PIEL_4				INT
	
AS

	-- ///////SE CREA LA TABLA TEMPORAL PARA OBTENER LOS DATOS COMO COLUMNAS//////////////////
	DECLARE @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1 TABLE(		
		[POSICION_PIEL]				INT,
		[PIEL]						INT,
		[K_INSPECCION_MATERIAL]		INT,
		[VALOR_ZONA_A]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_B]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_C]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_D]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_E]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_F]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_G]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_H]				VARCHAR(20) DEFAULT ''
		)
			
	-- ///////SE DECLARAN LAS VARIABLES A USAR//////////////////
	DECLARE @VP_POSICION_PIEL	INT = 0, @VP_PIEL INT = 0, @VP_K_INSPECCION_MATERIAL INT = 0, @VP_ZONA	VARCHAR(10) = '', @VP_VALOR VARCHAR(10) = ''
	DECLARE @VP_VALOR_ZONA_A VARCHAR(20) = '', @VP_VALOR_ZONA_B VARCHAR(20) = '', @VP_VALOR_ZONA_C VARCHAR(20) = ''
	DECLARE @VP_VALOR_ZONA_D VARCHAR(20) = '', @VP_VALOR_ZONA_E VARCHAR(20) = '', @VP_VALOR_ZONA_F VARCHAR(20) = '' 
	DECLARE @VP_VALOR_ZONA_G VARCHAR(20) = '', @VP_VALOR_ZONA_H VARCHAR(20) = ''

	DECLARE CU_GROSS_SUAVIDAD_PIEL_1 CURSOR 
	FOR SELECT	[POSICION_PIEL],			
				[PIEL],					
				[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].[K_INSPECCION_MATERIAL],
				ZONA,
				VALOR
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] (NOLOCK)
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = [INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].K_INSPECCION_MATERIAL
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		K_TIPO_INSPECCION_MATERIAL = @PP_K_TIPO_INSPECCION_MATERIAL
	AND		[POSICION_PIEL] = @PP_POSICION_PIEL_4
	ORDER BY ZONA ASC
	
	OPEN CU_GROSS_SUAVIDAD_PIEL_1
	FETCH NEXT FROM CU_GROSS_SUAVIDAD_PIEL_1 INTO @VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, @VP_ZONA, @VP_VALOR
	
	WHILE @@FETCH_STATUS = 0
		BEGIN
			IF @VP_ZONA = 'A'
				SET @VP_VALOR_ZONA_A = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'B'
				SET @VP_VALOR_ZONA_B = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'C'
				SET @VP_VALOR_ZONA_C = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'D'
				SET @VP_VALOR_ZONA_D = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'E'
				SET @VP_VALOR_ZONA_E = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'F'
				SET @VP_VALOR_ZONA_F = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'G'
				SET @VP_VALOR_ZONA_G = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'H'
				SET @VP_VALOR_ZONA_H = CONVERT(VARCHAR(20), @VP_VALOR)

			FETCH NEXT FROM CU_GROSS_SUAVIDAD_PIEL_1 INTO @VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, @VP_ZONA, @VP_VALOR
									
		END
	CLOSE CU_GROSS_SUAVIDAD_PIEL_1
	DEALLOCATE CU_GROSS_SUAVIDAD_PIEL_1

	INSERT INTO @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1
	SELECT	@VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, 
			@VP_VALOR_ZONA_A, @VP_VALOR_ZONA_B, @VP_VALOR_ZONA_C, @VP_VALOR_ZONA_D,
			@VP_VALOR_ZONA_E, @VP_VALOR_ZONA_F, @VP_VALOR_ZONA_G, @VP_VALOR_ZONA_H

	-- //////////////////////////////////////////////////
	SELECT [POSICION_PIEL],			
		    (CASE WHEN PIEL <> 0 THEN RIGHT('0000' + CONVERT(VARCHAR(4), PIEL), 4) 
				ELSE '' END) AS N_PIEL,									
		   [K_INSPECCION_MATERIAL],
		   [VALOR_ZONA_A],			
		   [VALOR_ZONA_B],			
		   [VALOR_ZONA_C],			
		   [VALOR_ZONA_D],			
		   [VALOR_ZONA_E],			
		   [VALOR_ZONA_F],			
		   [VALOR_ZONA_G],			
		   [VALOR_ZONA_H],	
		   0 AS AVG_GROS_SUAVIDAD 
	FROM @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO






-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_5_PDF]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_5_PDF]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_5_PDF] 0, 144,   5635 , 1191 , 107791 , 5, 5 --#5 GROSS/THICKNESS #6 SUAVIDAD
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD_X_TIPO_POSS_5_PDF]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_TIPO_INSPECCION_MATERIAL	INT,
	@PP_POSICION_PIEL_5				INT
	
AS

	-- ///////SE CREA LA TABLA TEMPORAL PARA OBTENER LOS DATOS COMO COLUMNAS//////////////////
	DECLARE @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1 TABLE(		
		[POSICION_PIEL]				INT,
		[PIEL]						INT,
		[K_INSPECCION_MATERIAL]		INT,
		[VALOR_ZONA_A]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_B]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_C]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_D]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_E]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_F]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_G]				VARCHAR(20) DEFAULT '',
		[VALOR_ZONA_H]				VARCHAR(20) DEFAULT ''
		)
			
	-- ///////SE DECLARAN LAS VARIABLES A USAR//////////////////
	DECLARE @VP_POSICION_PIEL	INT = 0, @VP_PIEL INT = 0, @VP_K_INSPECCION_MATERIAL INT = 0, @VP_ZONA	VARCHAR(10) = '', @VP_VALOR VARCHAR(10) = ''
	DECLARE @VP_VALOR_ZONA_A VARCHAR(20) = '', @VP_VALOR_ZONA_B VARCHAR(20) = '', @VP_VALOR_ZONA_C VARCHAR(20) = ''
	DECLARE @VP_VALOR_ZONA_D VARCHAR(20) = '', @VP_VALOR_ZONA_E VARCHAR(20) = '', @VP_VALOR_ZONA_F VARCHAR(20) = '' 
	DECLARE @VP_VALOR_ZONA_G VARCHAR(20) = '', @VP_VALOR_ZONA_H VARCHAR(20) = ''

	DECLARE CU_GROSS_SUAVIDAD_PIEL_1 CURSOR 
	FOR SELECT	[POSICION_PIEL],			
				[PIEL],					
				[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].[K_INSPECCION_MATERIAL],
				ZONA,
				VALOR
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] (NOLOCK)
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = [INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].K_INSPECCION_MATERIAL
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		K_TIPO_INSPECCION_MATERIAL = @PP_K_TIPO_INSPECCION_MATERIAL
	AND		[POSICION_PIEL] = @PP_POSICION_PIEL_5
	ORDER BY ZONA ASC
	
	OPEN CU_GROSS_SUAVIDAD_PIEL_1
	FETCH NEXT FROM CU_GROSS_SUAVIDAD_PIEL_1 INTO @VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, @VP_ZONA, @VP_VALOR
	
	WHILE @@FETCH_STATUS = 0
		BEGIN
			IF @VP_ZONA = 'A'
				SET @VP_VALOR_ZONA_A = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'B'
				SET @VP_VALOR_ZONA_B = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'C'
				SET @VP_VALOR_ZONA_C = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'D'
				SET @VP_VALOR_ZONA_D = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'E'
				SET @VP_VALOR_ZONA_E = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'F'
				SET @VP_VALOR_ZONA_F = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'G'
				SET @VP_VALOR_ZONA_G = CONVERT(VARCHAR(20), @VP_VALOR)

			IF @VP_ZONA = 'H'
				SET @VP_VALOR_ZONA_H = CONVERT(VARCHAR(20), @VP_VALOR)

			FETCH NEXT FROM CU_GROSS_SUAVIDAD_PIEL_1 INTO @VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, @VP_ZONA, @VP_VALOR
									
		END
	CLOSE CU_GROSS_SUAVIDAD_PIEL_1
	DEALLOCATE CU_GROSS_SUAVIDAD_PIEL_1

	INSERT INTO @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1
	SELECT	@VP_POSICION_PIEL, @VP_PIEL, @VP_K_INSPECCION_MATERIAL, 
			@VP_VALOR_ZONA_A, @VP_VALOR_ZONA_B, @VP_VALOR_ZONA_C, @VP_VALOR_ZONA_D,
			@VP_VALOR_ZONA_E, @VP_VALOR_ZONA_F, @VP_VALOR_ZONA_G, @VP_VALOR_ZONA_H

	-- //////////////////////////////////////////////////
	SELECT [POSICION_PIEL],			
		   (CASE WHEN PIEL <> 0 THEN RIGHT('0000' + CONVERT(VARCHAR(4), PIEL), 4) 
				ELSE '' END) AS N_PIEL,					
		   [K_INSPECCION_MATERIAL],
		   [VALOR_ZONA_A],			
		   [VALOR_ZONA_B],			
		   [VALOR_ZONA_C],			
		   [VALOR_ZONA_D],			
		   [VALOR_ZONA_E],			
		   [VALOR_ZONA_F],			
		   [VALOR_ZONA_G],			
		   [VALOR_ZONA_H],	
		   0 AS AVG_GROS_SUAVIDAD 
	FROM @TBL_INSPECCION_GROSS_SUAVIDAD_PIEL_1

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] 0, 144,   5635 , 1191 , 107791 , 29 , 1 
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] 0, 144,   5635 , 1191 , 107791 , 29 , 2
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] 0, 144,   5635 , 1191 , 107791 , 29 , 3 
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_INSPECCION_MATERIAL		INT,
	@PP_POSICION_PIEL				INT
	
AS

	-- ///////OBTIENE EL VALOR DEL GORSS - SUAVIDAD QUE MAS SE REPITE//////////////////
	DECLARE @VP_VALOR_REPETIDO DECIMAL(13,2) = 0
	DECLARE @VP_N_VALOR_REPETIDO INT = 0

	SELECT TOP 1 @VP_VALOR_REPETIDO = [VALOR], 
			@VP_N_VALOR_REPETIDO = COUNT(*) 
	FROM INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD (NOLOCK)
	WHERE [K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND K_ITEM = @PP_K_ITEM
	AND LOTE = @PP_LOTE
	AND K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL			
	GROUP BY [VALOR]
	ORDER BY COUNT(*) DESC

	-- //////////////////////////////////////////////////
	SELECT	@VP_VALOR_REPETIDO AS VALOR_REPETIDO,
			[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].*
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] (NOLOCK)
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL
	AND		[POSICION_PIEL] = @PP_POSICION_PIEL
	ORDER BY ZONA ASC

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL_MARCA_NATURAL_X_TIPO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_MARCA_NATURAL_X_TIPO]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_MARCA_NATURAL_X_TIPO] 0, 144,   5635 , 1191 , 107791, 7 --#7 MARCAS NATURALES
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_MARCA_NATURAL_X_TIPO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_TIPO_INSPECCION_MATERIAL	INT
	
AS

	-- //////////////////////////////////////////////////
	SELECT	ROW_NUMBER() OVER(ORDER BY [K_INSPECCION_LOTE_PIEL_MARCA_NATURAL] ASC) AS [CONSECUTIVO],
			[K_INSPECCION_LOTE_PIEL_MARCA_NATURAL],
			-- =================================
			[K_IMPORTACION_LOTE_PIEL],			
			[INSPECCION_LOTE_PIEL_MARCA_NATURAL].[K_ITEM],							
			[LOTE],								
			RIGHT('0000' + CONVERT(VARCHAR(4), PIEL), 4) AS PIEL,				
			[INSPECCION_LOTE_PIEL_MARCA_NATURAL].[K_INSPECCION_MATERIAL],			
			[DEFECTO],							
			[AREA_PORCENTAJE]		
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_MARCA_NATURAL] (NOLOCK)
	INNER JOIN INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = [INSPECCION_LOTE_PIEL_MARCA_NATURAL].K_INSPECCION_MATERIAL
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		[INSPECCION_LOTE_PIEL_MARCA_NATURAL].K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		[K_TIPO_INSPECCION_MATERIAL] = @PP_K_TIPO_INSPECCION_MATERIAL
	ORDER BY PIEL

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL_MARCA_NATURAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_MARCA_NATURAL]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_MARCA_NATURAL] 0, 144,   5635 , 1191 , 107791, 33
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_MARCA_NATURAL]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_INSPECCION_MATERIAL		INT
	
AS

	-- //////////////////////////////////////////////////
	SELECT	ROW_NUMBER() OVER(ORDER BY [K_INSPECCION_LOTE_PIEL_MARCA_NATURAL] ASC) AS [CONSECUTIVO],
			[K_INSPECCION_LOTE_PIEL_MARCA_NATURAL],
			-- =================================
			[K_IMPORTACION_LOTE_PIEL],			
			[K_ITEM],							
			[LOTE],								
			[PIEL],								
			[K_INSPECCION_MATERIAL],			
			[DEFECTO],							
			[AREA_PORCENTAJE]		
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_MARCA_NATURAL] (NOLOCK)
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		[K_INSPECCION_MATERIAL] = @PP_K_INSPECCION_MATERIAL
	ORDER BY PIEL

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////
-- USE DATA_02
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_GET_DATO_INSPECCION_LOTE_PIEL_MARCA_NATURAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_GET_DATO_INSPECCION_LOTE_PIEL_MARCA_NATURAL]
GO

/*
 EXEC	[dbo].[PG_GET_DATO_INSPECCION_LOTE_PIEL_MARCA_NATURAL] 0, 144,   5635 , 1191 , 107791, 33
*/

CREATE PROCEDURE [dbo].[PG_GET_DATO_INSPECCION_LOTE_PIEL_MARCA_NATURAL]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_INSPECCION_MATERIAL		INT
	
AS

	-- //////////////////////////////////////////////////
	DECLARE @VP_N_PIEL_A_INSPECCIONAR	INT = 0
	DECLARE @VP_CANTIDAD_PIEL_LOTE		INT = 0

	SELECT	@VP_CANTIDAD_PIEL_LOTE = LOT_SIZE
	FROM	IncInsp_sql (NOLOCK)
	WHERE	ID = @PP_K_LOTE_IMPORTACION

	IF @VP_CANTIDAD_PIEL_LOTE IS NULL
		SET @VP_CANTIDAD_PIEL_LOTE = 0

	SET @VP_N_PIEL_A_INSPECCIONAR = (1 * @VP_CANTIDAD_PIEL_LOTE) / 100
	
	-- //////////////////////////////////////////////////
	DECLARE @VP_N_PIEL_INSPECCIONADA INT = 0

	SELECT	@VP_N_PIEL_INSPECCIONADA = COUNT(DISTINCT PIEL)		
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_MARCA_NATURAL] (NOLOCK)
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		[K_INSPECCION_MATERIAL] = @PP_K_INSPECCION_MATERIAL

	IF @VP_N_PIEL_INSPECCIONADA IS NULL
		SET @VP_N_PIEL_INSPECCIONADA = 0

	SELECT	@VP_N_PIEL_A_INSPECCIONAR AS N_PIEL_A_INSPECCIONAR,
			@VP_N_PIEL_INSPECCIONADA AS N_PIEL_INSPECCIONADA
			

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_GET_DATO_INSPECCION_LOTE_PIEL_GROSS_X_TIPO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_GET_DATO_INSPECCION_LOTE_PIEL_GROSS_X_TIPO]
GO

/*
 EXEC	[dbo].[PG_GET_DATO_INSPECCION_LOTE_PIEL_GROSS_X_TIPO] 0, 144,   7031 , 2477 , 450321, 5 --#5 GROSS
*/

CREATE PROCEDURE [dbo].[PG_GET_DATO_INSPECCION_LOTE_PIEL_GROSS_X_TIPO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_TIPO_INSPECCION_MATERIAL	INT
	
AS

	-- //////////////////////////////////////////////////
	DECLARE @VP_MENSAJE				INT = 0
	DECLARE @VP_CANTIDAD_MUESTRA	INT = 0

	SELECT @VP_CANTIDAD_MUESTRA = sample_size 
	FROM	IncInsp_sql
	WHERE ID = @PP_K_LOTE_IMPORTACION
	AND LTRIM(RTRIM(LOT)) = @PP_LOTE

	IF @VP_CANTIDAD_MUESTRA IS NULL OR @VP_CANTIDAD_MUESTRA = 0
		RAISERROR ('ERROR: No fue posible obtener la cantidad de muestra en [IncInsp_sql] ', 16, 1 ) --MENSAJE - Severity -State.

	DECLARE @VP_N_PIEL_INSPECCIONADA INT = 0
	SELECT	@VP_N_PIEL_INSPECCIONADA = COUNT(DISTINCT(PIEL)) 
	FROM	INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD (NOLOCK)
	INNER	JOIN INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD.K_INSPECCION_MATERIAL
	WHERE	[K_IMPORTACION_LOTE_PIEL]	= @PP_K_LOTE_IMPORTACION
	AND		INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD.[K_ITEM] = @PP_K_ITEM						
	AND		[LOTE] = @PP_LOTE							
	AND		[K_TIPO_INSPECCION_MATERIAL] = @PP_K_TIPO_INSPECCION_MATERIAL

	IF @VP_N_PIEL_INSPECCIONADA IS NULL
		SET @VP_N_PIEL_INSPECCIONADA = 0

	IF @VP_CANTIDAD_MUESTRA <> @VP_N_PIEL_INSPECCIONADA
		BEGIN
			DECLARE @VP_K_INSPECCION INT = 0
			SELECT @VP_K_INSPECCION = K_INSPECCION_MATERIAL
			FROM INSPECCION_MATERIAL (NOLOCK)
			INNER	JOIN TIPO_INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
			WHERE K_ITEM = @PP_K_ITEM AND K_ESTATUS_INSPECCION_MATERIAL = 1 
			AND INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = @PP_K_TIPO_INSPECCION_MATERIAL

			SET @VP_MENSAJE = @VP_K_INSPECCION
		END

	--	////////////////////////////////////////////////
	SELECT	@VP_MENSAJE AS MENSAJE
			

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_GET_N_INSPECCION_LOTE_PIEL_X_TIPO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_GET_N_INSPECCION_LOTE_PIEL_X_TIPO]
GO

/*
 EXEC	[dbo].[PG_GET_N_INSPECCION_LOTE_PIEL_X_TIPO] 0, 144 , 1191 , 6
*/

CREATE PROCEDURE [dbo].[PG_GET_N_INSPECCION_LOTE_PIEL_X_TIPO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ITEM						INT,
	@PP_K_TIPO_INSPECCION_MATERIAL	INT
	
AS

	DECLARE @VP_MENSAJE VARCHAR(255) = ''

	-- //////////////////////////////////////////////////
	DECLARE	@VP_N_K_INSPECCION_MATERIAL INT = 0
	SELECT	@VP_N_K_INSPECCION_MATERIAL = COUNT(K_INSPECCION_MATERIAL)
	FROM	[INSPECCION_MATERIAL] (NOLOCK)
	WHERE	K_ITEM = @PP_K_ITEM
	AND	K_TIPO_INSPECCION_MATERIAL = @PP_K_TIPO_INSPECCION_MATERIAL 
	AND K_ESTATUS_INSPECCION_MATERIAL = 1 -- ACTIVA

	IF @VP_N_K_INSPECCION_MATERIAL IS NULL
		SET @VP_N_K_INSPECCION_MATERIAL = 0
	-- ===========================

	IF @VP_N_K_INSPECCION_MATERIAL = 0
		BEGIN
			DECLARE @VP_D_TIPO_INSPECCION VARCHAR(100) = ''

			SELECT @VP_D_TIPO_INSPECCION	= D_TIPO_INSPECCION_MATERIAL		
			FROM TIPO_INSPECCION_MATERIAL (NOLOCK)
			WHERE K_TIPO_INSPECCION_MATERIAL = @PP_K_TIPO_INSPECCION_MATERIAL 

			SET @VP_MENSAJE = 'Primero debe dar de alta la Inspeccion tipo ' +  @VP_D_TIPO_INSPECCION + '.'
		END

	SELECT	@VP_MENSAJE AS MENSAJE
			

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL_RESULTADO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_RESULTADO]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_RESULTADO] 0, 144,   5635 , 1191 , 107791          
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_RESULTADO] 0, 144,   5634 , 1191 , 900101          
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_RESULTADO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT
	
AS

	-- //////////////////////////////////////////////////
	SELECT	[INSPECCION_LOTE_PIEL_RESULTADO].*
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_RESULTADO] (NOLOCK)
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO






-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL_RESULTADO_LOG]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_RESULTADO_LOG]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_RESULTADO_LOG] 0, 144,  5635 , 1191 , 107791
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_RESULTADO_LOG] 0, 144,  5634 , 1191 , 900101
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_RESULTADO_LOG]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT
	
AS

	-- ///////////////////////////////////////////
	SELECT	
			[INSPECCION_LOTE_PIEL_RESULTADO_LOG].*,
			D_USUARIO_PEARL				AS D_USUARIO_CAMBIO,
			D_ESTATUS_INSPECCION_LOTE_PIEL,
			ISNULL(INSPECCION, 'N/A') AS INSPECCION
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_RESULTADO_LOG] (NOLOCK)
	LEFT JOIN INSPECCION_MATERIAL (NOLOCK) ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = [INSPECCION_LOTE_PIEL_RESULTADO_LOG].K_INSPECCION_MATERIAL
	INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL (NOLOCK) ON [INSPECCION_LOTE_PIEL_RESULTADO_LOG].K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
	INNER JOIN ESTATUS_INSPECCION_LOTE_PIEL (NOLOCK) ON ESTATUS_INSPECCION_LOTE_PIEL.K_ESTATUS_INSPECCION_LOTE_PIEL = [INSPECCION_LOTE_PIEL_RESULTADO_LOG].K_ESTATUS_INSPECCION_LOTE_PIEL
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		[INSPECCION_LOTE_PIEL_RESULTADO_LOG].K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
