-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[DATA_02]
-- // MODULO:			QA INSPECCION DE MATERIAL
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	20/AGO/2020
-- //////////////////////////////////////////////////////////////  

USE [DATA_02PRUEBAS]
GO

-- //////////////////////////////////////////////////////////////



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_INCINSP_SQL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_INCINSP_SQL]
GO
/*
 EXEC	[dbo].[PG_LI_INCINSP_SQL] 0,0, '', '2021/03/10', '2021/03/15', '( TODOS )', '( TODOS )', '( TODOS )', '( TODOS )'
*/


CREATE PROCEDURE [dbo].[PG_LI_INCINSP_SQL]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_BUSCAR						VARCHAR(200),
	-- ===========================
	@PP_F_INICIO					DATE,
	@PP_F_FIN						DATE,
	@PP_COLOR						VARCHAR(50),
	@PP_ESTATUS						VARCHAR(10),
	@PP_ACEPTADO					VARCHAR(10),
	@PP_DEFECTO						VARCHAR(50)
AS

	-- ///////////////////////////////////////////
	SELECT	ID					AS K_INSPECCION_LOTE,
			[dbo].[CONVERT_INT_TO_DATE]([Date])	AS FECHA,
			PACKING_NO,
			[Description]		AS COLOR,
			LTRIM(RTRIM(Lot))	AS LOTE,
			Lot_size			AS CANTIDAD_LOTE,
			Sample_size			AS CANTIDAD_MUESTRA,
			[Status]			AS ESTATUS,
			Accepted			AS ACEPTADO,
			Thickness			AS THICKNESS,
			Defecto				AS DEFECTO
	FROM	IncInsp_sql
	WHERE 	( LOT				LIKE '%'+@PP_BUSCAR+'%'
			OR	PACKING_NO		LIKE '%'+@PP_BUSCAR+'%' )
	-- =============================
	AND		[DATE] >= [dbo].[CONVERT_DATE_TO_INT](@PP_F_INICIO, 'yyyyMMdd')
	AND		[DATE] <= [dbo].[CONVERT_DATE_TO_INT](@PP_F_FIN, 'yyyyMMdd') 	
	AND		( @PP_COLOR = '( TODOS )'		OR	LTRIM(RTRIM([Description])) = @PP_COLOR  )
	AND		( @PP_ESTATUS = '( TODOS )'		OR	LTRIM(RTRIM([STATUS])) = @PP_ESTATUS )
	AND		( @PP_ACEPTADO = '( TODOS )'	OR	LTRIM(RTRIM(Accepted)) = @PP_ACEPTADO )
	AND		( @PP_DEFECTO = '( TODOS )'		OR	LTRIM(RTRIM(Defecto)) = @PP_DEFECTO )
	ORDER BY	[DATE]	DESC
	
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INCINSP_SQL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INCINSP_SQL]
GO
/*
 EXEC	[dbo].[PG_SK_INCINSP_SQL] 0,0, 5631
*/


CREATE PROCEDURE [dbo].[PG_SK_INCINSP_SQL]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_INSPECCION_LOTE			INT
AS

	-- ///////////////////////////////////////////
	SELECT	ID					AS K_INSPECCION_LOTE,
			[dbo].[CONVERT_INT_TO_DATE]([Date])	AS FECHA,
			PACKING_NO,
			LTRIM(RTRIM(Lot))	AS LOTE,
			Description			AS COLOR,
			LTRIM(RTRIM(item_desc_1)) AS DESCRIPCION,
			upc_cd AS K_ITEM,
			IncInsp_sql.Lot_size	AS CANTIDAD_LOTE,
			Sample_size			AS CANTIDAD_MUESTRA,
			Status				AS ESTATUS,
			Accepted			AS ACEPTADO,
			Thickness			AS THICKNESS,
			Defecto				AS DEFECTO
	FROM	IncInsp_sql
	INNER JOIN IMITMIDX_SQL ON  LTRIM(RTRIM(ITEM_NO)) =  [Description]
	WHERE 	ID = @PP_K_INSPECCION_LOTE

	
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO





IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_PIEL_X_LOTE_CON_OPCION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_PIEL_X_LOTE_CON_OPCION]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_PIEL_X_LOTE_CON_OPCION] 0, 144 ,  5635 , 1191 , 107791 , 0 , 1 , 1 
 EXEC	[dbo].[PG_SK_INSPECCION_PIEL_X_LOTE_CON_OPCION] 0, 144 ,  5635 , 1191 , 107791 , 28 , 0 , 1 
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_PIEL_X_LOTE_CON_OPCION]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_INSPECCION_MATERIAL		INT,
	@PP_PRIMER_INSPECCION			INT, --#0 Cuando se abre ficha, #1 cuando se oprime adelande o atras 
	@PP_TIPO_MOVIMIENTO				INT --#0 ANTERIOR, #1 SIGUIENTE
AS

	-- ////////////////////////////////////////////////
	DECLARE @VP_N_INSPECCION_X_ITEM INT = 0
	SELECT @VP_N_INSPECCION_X_ITEM = COUNT(K_INSPECCION_MATERIAL)
	FROM INSPECCION_MATERIAL
	WHERE K_ITEM = @PP_K_ITEM
	AND		INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = 1 -- ACTIVA

	IF @VP_N_INSPECCION_X_ITEM IS NULL
		SET @VP_N_INSPECCION_X_ITEM = 0
		
	-- ////////////////////////////////////////////////
	IF @PP_TIPO_MOVIMIENTO = 1 -- SIGUIENTE
		SELECT	TOP 1
				INSPECCION_MATERIAL.*,
				INSPECCION_OPCION.*,
				D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
				D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
				K_USUARIO_PEARL AS D_USUARIO_CAMBIO,
				ISNULL(OPCION_SELECCIONADA, '') AS OPCION_SELECCIONADA,
				ISNULL(ACEPTADO, '') AS ACEPTADO,
				ISNULL(COMENTARIO, '') AS COMENTARIO,
				@VP_N_INSPECCION_X_ITEM AS TOTAL_INSPECCION
				-- =============================	
		FROM	INSPECCION_MATERIAL
				-- =============================
				INNER JOIN ESTATUS_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL
				INNER JOIN TIPO_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
				INNER JOIN INSPECCION_OPCION ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
				INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL ON INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
				-- =============================
				LEFT  JOIN INSPECCION_LOTE_PIEL ON INSPECCION_LOTE_PIEL.K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
						AND INSPECCION_LOTE_PIEL.K_ITEM = INSPECCION_MATERIAL.K_ITEM
						AND	INSPECCION_LOTE_PIEL.K_IMPORTACION_LOTE_PIEL = @PP_K_LOTE_IMPORTACION
						AND INSPECCION_LOTE_PIEL.LOTE = @PP_LOTE
				-- =============================
		WHERE	INSPECCION_MATERIAL.K_ITEM=@PP_K_ITEM
		AND		INSPECCION_MATERIAL.K_INSPECCION_MATERIAL > ( CASE	WHEN @PP_PRIMER_INSPECCION = 1	THEN 0
															ELSE @PP_K_INSPECCION_MATERIAL END )
		-- =============================
		AND		ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = 1 -- ACTIVA
		-- =============================
		ORDER BY INSPECCION_MATERIAL.K_INSPECCION_MATERIAL ASC

	-- ////////////////////////////////////////////////
	IF @PP_TIPO_MOVIMIENTO = 0 -- ANTERIOR
		SELECT	TOP 1
				INSPECCION_MATERIAL.*,
				INSPECCION_OPCION.*,
				D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
				D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
				K_USUARIO_PEARL AS D_USUARIO_CAMBIO,
				ISNULL(OPCION_SELECCIONADA, '') AS OPCION_SELECCIONADA,
				ISNULL(ACEPTADO, '') AS ACEPTADO,
				ISNULL(COMENTARIO, '') AS COMENTARIO,
				@VP_N_INSPECCION_X_ITEM AS TOTAL_INSPECCION
				-- =============================	
		FROM	INSPECCION_MATERIAL
				-- =============================
				INNER JOIN ESTATUS_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL
				INNER JOIN TIPO_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
				INNER JOIN INSPECCION_OPCION ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
				INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL ON INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
				-- =============================
				LEFT  JOIN INSPECCION_LOTE_PIEL ON INSPECCION_LOTE_PIEL.K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
						AND INSPECCION_LOTE_PIEL.K_ITEM = INSPECCION_MATERIAL.K_ITEM
						AND	INSPECCION_LOTE_PIEL.K_IMPORTACION_LOTE_PIEL = @PP_K_LOTE_IMPORTACION
						AND INSPECCION_LOTE_PIEL.LOTE = @PP_LOTE
				-- =============================
		WHERE	INSPECCION_MATERIAL.K_ITEM=@PP_K_ITEM
		AND		INSPECCION_MATERIAL.K_INSPECCION_MATERIAL < ( CASE	WHEN @PP_PRIMER_INSPECCION = 1	THEN 0
																	ELSE @PP_K_INSPECCION_MATERIAL END )
		-- =============================
		AND		ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = 1 -- ACTIVA
		-- =============================
		ORDER BY INSPECCION_MATERIAL.K_INSPECCION_MATERIAL DESC


		-- ////////////////////////////////////////////////
	IF @PP_TIPO_MOVIMIENTO = 2 -- PARA ACTUALIZAR INSPECCION
		SELECT	TOP 1
				INSPECCION_MATERIAL.*,
				INSPECCION_OPCION.*,
				D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
				D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
				K_USUARIO_PEARL AS D_USUARIO_CAMBIO,
				ISNULL(OPCION_SELECCIONADA, '') AS OPCION_SELECCIONADA,
				ISNULL(ACEPTADO, '') AS ACEPTADO,
				ISNULL(COMENTARIO, '') AS COMENTARIO,
				@VP_N_INSPECCION_X_ITEM AS TOTAL_INSPECCION
				-- =============================	
		FROM	INSPECCION_MATERIAL
				-- =============================
				INNER JOIN ESTATUS_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL
				INNER JOIN TIPO_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
				INNER JOIN INSPECCION_OPCION ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
				INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL ON INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
				-- =============================
				LEFT  JOIN INSPECCION_LOTE_PIEL ON INSPECCION_LOTE_PIEL.K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
						AND INSPECCION_LOTE_PIEL.K_ITEM = INSPECCION_MATERIAL.K_ITEM
						AND	INSPECCION_LOTE_PIEL.K_IMPORTACION_LOTE_PIEL = @PP_K_LOTE_IMPORTACION
						AND INSPECCION_LOTE_PIEL.LOTE = @PP_LOTE
				-- =============================
		WHERE	INSPECCION_MATERIAL.K_ITEM = @PP_K_ITEM
		AND		INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL 
		-- =============================
		ORDER BY INSPECCION_MATERIAL.K_INSPECCION_MATERIAL DESC

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL] 0, 144,  5635 , 1191 , 107791 , 28 
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_INSPECCION_MATERIAL		INT
	
AS

	-- ///////////////////////////////////////////
	SELECT	
			[INSPECCION_LOTE_PIEL].*,
			INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL]
	INNER JOIN INSPECCION_MATERIAL ON [INSPECCION_LOTE_PIEL].K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
			AND [INSPECCION_LOTE_PIEL].K_ITEM = INSPECCION_MATERIAL.K_ITEM
	INNER JOIN	TIPO_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		[INSPECCION_LOTE_PIEL].K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		[INSPECCION_LOTE_PIEL].K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] 0, 144,   5635 , 1191 , 107791 , 29 , 1 
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] 0, 144,   5635 , 1191 , 107791 , 29 , 2
 EXEC	[dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD] 0, 144,   5635 , 1191 , 107791 , 29 , 3 
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_LOTE_IMPORTACION			INT,
	@PP_K_ITEM						INT,
	@PP_LOTE						INT,
	@PP_K_INSPECCION_MATERIAL		INT,
	@PP_POSICION_PIEL				INT
	
AS

	-- ///////OBTIENE EL VALOR DEL GORSS - SUAVIDAD QUE MAS SE REPITE//////////////////
	DECLARE @VP_VALOR_REPETIDO DECIMAL(13,2) = 0
	DECLARE @VP_N_VALOR_REPETIDO INT = 0

	SELECT TOP 1 @VP_VALOR_REPETIDO = [VALOR], 
			@VP_N_VALOR_REPETIDO = COUNT(*) 
	FROM INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD 
	WHERE [K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND K_ITEM = @PP_K_ITEM
	AND LOTE = @PP_LOTE
	AND K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL			
	GROUP BY [VALOR]
	ORDER BY COUNT(*) DESC

	-- //////////////////////////////////////////////////
	SELECT	@VP_VALOR_REPETIDO AS VALOR_REPETIDO,
			[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD].*
	-- =============================	
	FROM	[INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD]
	-- =============================
	WHERE	[K_IMPORTACION_LOTE_PIEL] = @PP_K_LOTE_IMPORTACION
	AND		K_ITEM = @PP_K_ITEM
	AND		LOTE = @PP_LOTE
	AND		K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL
	AND		[POSICION_PIEL] = @PP_POSICION_PIEL
	ORDER BY ZONA ASC

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
