
USE DATA_02Pruebas

SELECT TOP 1000	* FROM	IncInsp_sql
WHERE sample_size = 3	--LTRIM(RTRIM(Lot)) = '034451' 
ORDER BY Date DESC

SELECT DISTINCT [STATUS] FROM	IncInsp_sql 

select * from PPMS_PEARL.DBO.def where descripcion='NATURAL'

SELECT * FROM TIPO_INSPECCION_MATERIAL 

SELECT * FROM IncInsp_sql ORDER BY ID DESC 

--UPDATE IncInsp_sql
--	SET Description = 'FWLNPX7'
--WHERE ID =    5635

SELECT * FROM INSPECCION_MATERIAL WHERE K_ITEM = 1191 AND K_ESTATUS_INSPECCION_MATERIAL = 1

SELECT * FROM INSPECCION_OPCION WHERE K_INSPECCION_MATERIAL IN (SELECT K_INSPECCION_MATERIAL FROM INSPECCION_MATERIAL WHERE K_ITEM = 1191 AND K_ESTATUS_INSPECCION_MATERIAL = 1)

SELECT * FROM INSPECCION_LOTE_PIEL

SELECT * FROM INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD


SELECT	[VALOR], 
		 COUNT(*) 
			FROM INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD 
			WHERE [K_IMPORTACION_LOTE_PIEL] = 5635
			AND K_ITEM = 1191
			AND LOTE = 107791
			AND K_INSPECCION_MATERIAL = 29			
			GROUP BY [VALOR]
			--HAVING Count(*) > 0
			ORDER BY Count(*) DESC


SELECT * FROM IMITMIDX_SQL WHERE upc_cd = '1191'

SELECT *  FROM IMITMIDX_SQL WHERE UPC_CD = 69

SELECT * FROM COMPRAS.dbo.ITEM WHERE K_ITEM = 69


SELECT * FROM BD_GENERAL.DBO.USUARIO_PEARL

	select * from BD_GENERAL.dbo.TIPO_GRUPO_APROBADOR WHERE K_TIPO_GRUPO_APROBADOR IN  (180, 200)
	
	SELECT *
								FROM	BD_GENERAL.dbo.USUARIO_PEARL AS USERS
								INNER	JOIN	BD_GENERAL.dbo.GRUPO_APROBADOR GP_APROB ON GP_APROB.K_USUARIO=USERS.K_USUARIO_PEARL
								WHERE   GP_APROB.S_GRUPO_APROBADOR = 'MHI_MQU_LR'
								--AND		GP_APROB.K_TIPO_GRUPO_APROBADOR = 180
								AND		K_ESTATUS_GRUPO_APROBADOR = 1

SELECT	* 
FROM	BD_GENERAL.DBO.[GRUPO_APROBADOR] 
INNER	JOIN BD_GENERAL.DBO.USUARIO_PEARL ON [GRUPO_APROBADOR].K_USUARIO = USUARIO_PEARL.K_USUARIO_PEARL
WHERE	D_GRUPO_APROBADOR = 'QA MADIFICAR INSPECCION MATERIAL'
AND		K_ESTATUS_GRUPO_APROBADOR = 1 -- ACTIVO
AND		K_TIPO_GRUPO_APROBADOR = 150 --  MODIFICAR INSPECCION MATERIAL QA


















