
USE DATA_02Pruebas

select * from PPMS_PEARL.DBO.def where descripcion='NATURAL'

SELECT top 100  * FROM	IncInsp_sql --order by id desc
WHERE ID IN(6552, 5635, 5634)

--USE DATA_02Pruebas
--UPDATE IncInsp_sql
--	SET PACKING_NO = 'PLG-(PLM)-040521'
--	--Status = '-',
--	--	Accepted = '-',
--	--	Thickness = NULL,
--	--	Defecto = NULL,
--	--	sample_size = 3
--WHERE ID IN( 5635, 5634)

SELECT CONVERT(VARCHAR(10),GETDATE(), 5)

SELECT PART_NUMBER_ITEM_PEARL,INSPECCION_MATERIAL.* 
FROM INSPECCION_MATERIAL 
INNER JOIN COMPRAS.dbo.ITEM ON  ITEM.K_ITEM = INSPECCION_MATERIAL.K_ITEM 
WHERE  K_ESTATUS_INSPECCION_MATERIAL = 1
AND K_CLASS_ITEM = 3
AND ITEM.K_ITEM IN (2477
,2467
,2437)
ORDER BY PART_NUMBER_ITEM_PEARL, K_INSPECCION_MATERIAL

SELECT INSPECCION_OPCION.*, INSPECCION_MATERIAL.*
FROM INSPECCION_MATERIAL 
INNER JOIN INSPECCION_OPCION ON INSPECCION_OPCION.K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
where INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = 8
AND OPCION_1 = ''

SELECT * FROM INSPECCION_OPCION WHERE K_INSPECCION_MATERIAL IN (447)

--update  INSPECCION_OPCION 
--set OPCION_1 = 'Si',
--	OPCION_2 = 'No'
--WHERE K_INSPECCION_MATERIAL IN (268
--,272
--,355
--,450)

SELECT * FROM   INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD WHERE K_IMPORTACION_LOTE_PIEL = 7031

SELECT * FROM INSPECCION_LOTE_PIEL_MARCA_NATURAL

SELECT * FROM INSPECCION_LOTE_PIEL 

SELECT * FROM [INSPECCION_LOTE_PIEL_RESULTADO]  

SELECT * FROM [INSPECCION_LOTE_PIEL_RESULTADO_LOG]


SELECT * FROM TIPO_INSPECCION_MATERIAL 
SELECT * FROM ESTATUS_INSPECCION_LOTE_PIEL

SELECT * FROM IncInsp_sql where id IN( 5635, 5634)

SELECT *
	FROM PPMS_PEARL.DBO.def 
	WHERE -- DESCRIPCION = 'NATURAL'
	defecto IN ('BROCHE', 'CHICA', 'FIERRO', 'GALLETA', 'PERFORADA', 'PERFORADO OBSTRUIDO', 'PIEL EQUIVOCADA', 'SIN AYUDA VISUAL', 'CORTADA', 'NUMEROS', 'FLANK' )
ORDER BY DEFECTO

--UPDATE PPMS_PEARL.DBO.def 
--	SET descripcion = 'NATURAL'
--	WHERE -- DESCRIPCION = 'NATURAL'
--	defecto IN ('PIEL SIN CUERPO', 'ACARTONADA', 'VACIO')
--ORDER BY DEFECTO

--UPDATE PPMS_PEARL.DBO.def 
--SET DESCRIPCION = NULL
--WHERE -- DESCRIPCION = 'NATURAL'
--	defecto IN ('BROCHE', 'CHICA', 'FIERRO', 'GALLETA', 'PERFORADA', 'PERFORADO OBSTRUIDO', 'PIEL EQUIVOCADA', 'SIN AYUDA VISUAL', 'CORTADA', 'NUMEROS', 'FLANK' )

SELECT	[VALOR], COUNT(*) 
FROM INSPECCION_LOTE_PIEL_GROSS_SUAVIDAD 
WHERE [K_IMPORTACION_LOTE_PIEL] = 5635 AND K_ITEM = 1191 AND LOTE = 107791 AND K_INSPECCION_MATERIAL = 31			
GROUP BY [VALOR]
--HAVING Count(*) > 0
ORDER BY Count(*) DESC

SELECT * FROM IMITMIDX_SQL WHERE upc_cd = '1191'

SELECT *  FROM IMITMIDX_SQL WHERE UPC_CD = 69

SELECT * FROM COMPRAS_Pruebas.dbo.ITEM WHERE K_CLASS_ITEM = 3
SELECT * FROM COMPRAS.dbo.ITEM WHERE  K_CLASS_ITEM = 3

SELECT * FROM BD_GENERAL.DBO.USUARIO_PEARL

SELECT * FROM BD_GENERAL.dbo.TIPO_GRUPO_APROBADOR WHERE K_TIPO_GRUPO_APROBADOR IN  (180, 200)
	
SELECT * FROM	BD_GENERAL.dbo.USUARIO_PEARL AS USERS
INNER	JOIN	BD_GENERAL.dbo.GRUPO_APROBADOR GP_APROB ON GP_APROB.K_USUARIO=USERS.K_USUARIO_PEARL
WHERE   GP_APROB.S_GRUPO_APROBADOR = 'MHI_MQU_LR'
--AND		GP_APROB.K_TIPO_GRUPO_APROBADOR = 180
AND		K_ESTATUS_GRUPO_APROBADOR = 1

SELECT	* FROM	BD_GENERAL.DBO.[GRUPO_APROBADOR] 
INNER	JOIN BD_GENERAL.DBO.USUARIO_PEARL ON [GRUPO_APROBADOR].K_USUARIO = USUARIO_PEARL.K_USUARIO_PEARL
WHERE	D_GRUPO_APROBADOR = 'QA MADIFICAR INSPECCION MATERIAL'
AND		K_ESTATUS_GRUPO_APROBADOR = 1 -- ACTIVO
AND		K_TIPO_GRUPO_APROBADOR = 150 --  MODIFICAR INSPECCION MATERIAL QA

















