-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[DATA_02Pruebas]
-- // MODULO:			QA INSPECCION DE MATERIAL
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	01/SEP/2020
-- //////////////////////////////////////////////////////////////  

USE [DATA_02Pruebas]
GO

-- //////////////////////////////////////////////////////////////



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_NUMERO_PARTE_X_K_ORDEN_COMPRA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_NUMERO_PARTE_X_K_ORDEN_COMPRA]
GO
/*
 EXEC	[dbo].[PG_LI_NUMERO_PARTE_X_K_ORDEN_COMPRA] 0,0, 78

*/
CREATE PROCEDURE [dbo].PG_LI_NUMERO_PARTE_X_K_ORDEN_COMPRA
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA				INT
	-- ===========================
AS

	DECLARE @VP_MENSAJE				VARCHAR(300) = ''
	-- ///////////////////////////////////////////
	
	SELECT	TOP (5000)  
		HEADER_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER AS ORDEN_COMPRA,
		VENDOR.D_VENDOR AS PROVEDOR,
		CUS_NO AS CLIENTE,
		K_PO_PRICE_LOG	AS K_PO_PRICE,
		S_CURRENCY,
		ITEM.K_CURRENCY,
		S_UNIT_OF_MEASURE,
		PART_NUMBER_ITEM_VENDOR,
		PART_NUMBER_ITEM_PEARL,
		D_ITEM,
		DETAILS_PURCHASE_ORDER.QUANTITY_ORDER AS QUANTITY,
		DETAILS_PURCHASE_ORDER.UNIT_PRICE AS PRICE_ITEM,
		TOTAL_PRICE as TOTAL_ITEM,
		DETAILS_PURCHASE_ORDER.*
	FROM	COMPRAS.dbo.DETAILS_PURCHASE_ORDER
	INNER JOIN	COMPRAS.dbo.ITEM		ON	DETAILS_PURCHASE_ORDER.K_ITEM=ITEM.K_ITEM
	INNER JOIN	BD_GENERAL.DBO.UNIT_OF_MEASURE ON ITEM.K_UNIT_OF_ITEM=UNIT_OF_MEASURE.K_UNIT_OF_MEASURE
	INNER JOIN	BD_GENERAL.DBO.CURRENCY	ON	ITEM.K_CURRENCY=CURRENCY.K_CURRENCY
	INNER JOIN	COMPRAS.dbo.HEADER_PURCHASE_ORDER ON DETAILS_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER = COMPRAS.dbo.HEADER_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER
	INNER JOIN	COMPRAS.dbo.VENDOR ON HEADER_PURCHASE_ORDER.K_VENDOR = VENDOR.K_VENDOR
	INNER JOIN	COMPRAS.dbo.DETAILS_BLANKET_PURCHASE_ORDER ON HEADER_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER = DETAILS_BLANKET_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER
	INNER JOIN	ARCUSFIL_SQL ON DETAILS_BLANKET_PURCHASE_ORDER.K_CUSTOMER = ARCUSFIL_SQL.A4GLIdentity
	WHERE		DETAILS_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER=@PP_K_ORDEN_COMPRA
	ORDER BY	K_DETAILS_PURCHASE_ORDER

	
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_NUMERO_PARTE_X_K_DETALLE_ORDEN]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_NUMERO_PARTE_X_K_DETALLE_ORDEN]
GO
/*
 EXEC	[dbo].[PG_SK_NUMERO_PARTE_X_K_DETALLE_ORDEN] 0,0, 78, 3
*/


CREATE PROCEDURE [dbo].[PG_SK_NUMERO_PARTE_X_K_DETALLE_ORDEN]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA				INT,
	@PP_K_DETALLE_ORDEN				INT
	-- ===========================
AS
	-- ///////////////////////////////////////////

	SELECT	TOP (5000)  
		HEADER_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER AS ORDEN_COMPRA,
		VENDOR.D_VENDOR AS PROVEDOR,
		CUS_NO AS CLIENTE,
		(SELECT COUNT(K_INSPECCION_MATERIAL) FROM INSPECCION_MATERIAL WHERE NUMERO_PARTE=PART_NUMBER_ITEM_PEARL) AS TOTAL_INSPECCION,
		K_PO_PRICE_LOG	AS K_PO_PRICE,
		S_CURRENCY,
		ITEM.K_CURRENCY,
		S_UNIT_OF_MEASURE,
		PART_NUMBER_ITEM_VENDOR,
		PART_NUMBER_ITEM_PEARL,
		D_ITEM,
		DETAILS_PURCHASE_ORDER.QUANTITY_ORDER AS QUANTITY,
		DETAILS_PURCHASE_ORDER.UNIT_PRICE AS PRICE_ITEM,
		TOTAL_PRICE as TOTAL_ITEM,
		DETAILS_PURCHASE_ORDER.*
	FROM	COMPRAS.dbo.DETAILS_PURCHASE_ORDER
	INNER JOIN	COMPRAS.dbo.ITEM		ON	DETAILS_PURCHASE_ORDER.K_ITEM=ITEM.K_ITEM
	INNER JOIN	BD_GENERAL.DBO.UNIT_OF_MEASURE ON ITEM.K_UNIT_OF_ITEM=UNIT_OF_MEASURE.K_UNIT_OF_MEASURE
	INNER JOIN	BD_GENERAL.DBO.CURRENCY	ON	ITEM.K_CURRENCY=CURRENCY.K_CURRENCY
	INNER JOIN	COMPRAS.dbo.HEADER_PURCHASE_ORDER ON DETAILS_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER = COMPRAS.dbo.HEADER_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER
	INNER JOIN	COMPRAS.dbo.VENDOR ON HEADER_PURCHASE_ORDER.K_VENDOR = VENDOR.K_VENDOR
	INNER JOIN	COMPRAS.dbo.DETAILS_BLANKET_PURCHASE_ORDER ON HEADER_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER = DETAILS_BLANKET_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER
	INNER JOIN	ARCUSFIL_SQL ON DETAILS_BLANKET_PURCHASE_ORDER.K_CUSTOMER = ARCUSFIL_SQL.A4GLIdentity
	WHERE		DETAILS_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER=@PP_K_ORDEN_COMPRA
	AND	DETAILS_PURCHASE_ORDER.K_DETAILS_PURCHASE_ORDER = @PP_K_DETALLE_ORDEN
	ORDER BY	K_DETAILS_PURCHASE_ORDER

	
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
