-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[DATA_02Pruebas]
-- // MODULO:			QA INSPECCION DE MATERIAL
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	01/SEP/2020
-- //////////////////////////////////////////////////////////////  

USE [DATA_02]
GO

-- //////////////////////////////////////////////////////////////



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_ITEM_X_K_ORDEN_COMPRA_PEDIDO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_ITEM_X_K_ORDEN_COMPRA_PEDIDO]
GO
/* 
 EXEC	[dbo].[PG_LI_ITEM_X_K_ORDEN_COMPRA_PEDIDO] 0,0,  '2' , 1
*/
CREATE PROCEDURE [dbo].[PG_LI_ITEM_X_K_ORDEN_COMPRA_PEDIDO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA_PEDIDO		VARCHAR(100),
	@PP_K_ENTREGA					INT
	-- ===========================
AS

	DECLARE @VP_MENSAJE				VARCHAR(300) = ''
	-- ///////////////////////////////////////////
	
	
	SELECT	DISTINCT
		DETAILS_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER AS K_ORDEN_COMPRA,
		DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO AS K_ORDEN_COMPRA_PEDIDO,
		DETAILS_BPO_RECIBO.K_ENTREGA,
		DETAILS_BPO_RECIBO.K_ITEM,
		DETAILS_BPO_RECIBO.LOTE_PEARL,
		LTRIM(RTRIM(PROD_CAT))		AS PRODUCTO_CATEGORIA,
		-- ===========================	-- ===========================
		S_UNIT_OF_MEASURE,
		PART_NUMBER_ITEM_VENDOR,
		PART_NUMBER_ITEM_PEARL,
		LTRIM(RTRIM(TRADEMARK_ITEM)) AS D_ITEM,
		D_VENDOR AS PROVEDOR,
		--cus_no AS CLIENTE,
		-- ===========================	-- ===========================
		(SELECT SUM(RECIBO.QUANTITY_RECEIVED) 
		FROM COMPRAS.dbo.DETAILS_BPO_RECIBO  RECIBO
		WHERE RECIBO.K_ORDEN_COMPRA_PEDIDO = DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO
		AND	RECIBO.K_ENTREGA = DETAILS_BPO_RECIBO.K_ENTREGA
		AND	RECIBO.K_ITEM = DETAILS_BPO_RECIBO.K_ITEM
		AND	RECIBO.LOTE_PEARL = DETAILS_BPO_RECIBO.LOTE_PEARL ) AS QUANTITY,
		-- ===========================
			( CASE WHEN ACEPTADO = 1	THEN 'ACEPTADO'
				WHEN ACEPTADO = 0	THEN 'RECHAZADO'
				ELSE 'PENDIENTE' END ) AS ESTATUS,
		-- ===========================
		(CASE WHEN F_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO IS NULL THEN '-'
			ELSE CONVERT(VARCHAR(10),F_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO) END) AS F_INSPECCION,
		-- =============================	
		(CASE WHEN [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_USUARIO_ALTA IS NULL THEN '-'
			ELSE (	SELECT D_USUARIO_PEARL 
					FROM BD_GENERAL.DBO.USUARIO_PEARL 
					WHERE K_USUARIO_PEARL =  [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_USUARIO_ALTA ) END ) AS USUARIO_INSPECCION
	FROM		COMPRAS.dbo.DETAILS_BPO_RECIBO
	INNER JOIN	COMPRAS.dbo.DETAILS_BPO_PEDIDO  ON	DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO = DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO AND DETAILS_BPO_RECIBO.K_ITEM = DETAILS_BPO_PEDIDO.K_ITEM
	INNER JOIN	COMPRAS.dbo.HEADER_BPO_PEDIDO  ON	DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO = HEADER_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO
	INNER JOIN	COMPRAS.dbo.ITEM ON	DETAILS_BPO_PEDIDO.K_ITEM=ITEM.K_ITEM
	INNER JOIN	BD_GENERAL.DBO.UNIT_OF_MEASURE ON ITEM.K_UNIT_OF_ITEM = UNIT_OF_MEASURE.K_UNIT_OF_MEASURE
	INNER JOIN	COMPRAS.dbo.VENDOR ON HEADER_BPO_PEDIDO.K_VENDOR = VENDOR.K_VENDOR 
	INNER JOIN	COMPRAS.dbo.DETAILS_BLANKET_PURCHASE_ORDER  ON	DETAILS_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER = DETAILS_BLANKET_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER
	INNER JOIN	ARCUSFIL_SQL ON DETAILS_BLANKET_PURCHASE_ORDER.K_CUSTOMER = ARCUSFIL_SQL.A4GLIdentity
				-- =============================
	INNER JOIN IMITMIDX_SQL ON  ITEM.K_ITEM = IMITMIDX_SQL.upc_cd
	LEFT JOIN	[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO] ON [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_ORDEN_COMPRA_PEDIDO = DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO
				AND  [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_ENTREGA = DETAILS_BPO_RECIBO.K_ENTREGA
				AND [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_ITEM = ITEM.K_ITEM
				AND [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].LOTE_PEARL = DETAILS_BPO_RECIBO.LOTE_PEARL
	WHERE		DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO 
	AND			DETAILS_BPO_RECIBO.K_ENTREGA = @PP_K_ENTREGA
	ORDER BY K_ENTREGA DESC
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_ITEM_X_K_ORDEN_COMPRA_PEDIDO_ENTREGA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_ITEM_X_K_ORDEN_COMPRA_PEDIDO_ENTREGA]
GO

/*
 EXEC	[dbo].[PG_SK_ITEM_X_K_ORDEN_COMPRA_PEDIDO_ENTREGA] 0,0,  '00296-00001' , 1 , 82, 201000001
*/

CREATE PROCEDURE [dbo].[PG_SK_ITEM_X_K_ORDEN_COMPRA_PEDIDO_ENTREGA]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA_PEDIDO		VARCHAR(100),
	@PP_K_ENTREGA					INT,
	@PP_K_ITEM						INT,
	@PP_LOTE_PEARL					INT
	-- ===========================
AS
	-- ///////////////////////////////////////////

	SELECT	DISTINCT
		DETAILS_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER AS K_ORDEN_COMPRA,
		DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO AS K_ORDEN_COMPRA_PEDIDO,
		DETAILS_BPO_RECIBO.K_ENTREGA,
		DETAILS_BPO_RECIBO.K_ITEM,
		DETAILS_BPO_RECIBO.LOTE_PEARL,
		LTRIM(RTRIM(PROD_CAT))		AS PRODUCTO_CATEGORIA,
		-- ===========================	-- ===========================
		S_UNIT_OF_MEASURE,
		PART_NUMBER_ITEM_VENDOR,
		PART_NUMBER_ITEM_PEARL,
		LTRIM(RTRIM(TRADEMARK_ITEM)) AS D_ITEM,
		D_VENDOR AS PROVEDOR,
		cus_no AS CLIENTE,
		-- ===========================	-- ===========================
		(SELECT SUM(RECIBO.QUANTITY_RECEIVED) 
		FROM COMPRAS.dbo.DETAILS_BPO_RECIBO  RECIBO
		WHERE RECIBO.K_ORDEN_COMPRA_PEDIDO = DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO
		AND	RECIBO.K_ENTREGA = DETAILS_BPO_RECIBO.K_ENTREGA
		AND	RECIBO.K_ITEM = DETAILS_BPO_RECIBO.K_ITEM
		AND	RECIBO.LOTE_PEARL = DETAILS_BPO_RECIBO.LOTE_PEARL ) AS QUANTITY,
		-- ===========================
		( CASE WHEN ACEPTADO = 1	THEN 'ACEPTADO'
				WHEN ACEPTADO = 0	THEN 'RECHAZADO'
				ELSE 'PENDIENTE' END ) AS ESTATUS,
		-- ===========================
		(CASE WHEN F_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO IS NULL THEN '-'
			ELSE CONVERT(VARCHAR(10),F_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO) END) AS F_INSPECCION,
		-- =============================	
		(CASE WHEN [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_USUARIO_ALTA IS NULL THEN '-'
			ELSE (	SELECT D_USUARIO_PEARL 
					FROM BD_GENERAL.DBO.USUARIO_PEARL 
					WHERE K_USUARIO_PEARL =  [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_USUARIO_ALTA ) END ) AS USUARIO_INSPECCION
	FROM		COMPRAS.dbo.DETAILS_BPO_RECIBO
	INNER JOIN	COMPRAS.dbo.DETAILS_BPO_PEDIDO  ON	DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO = DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO AND DETAILS_BPO_RECIBO.K_ITEM = DETAILS_BPO_PEDIDO.K_ITEM
	INNER JOIN	COMPRAS.dbo.HEADER_BPO_PEDIDO  ON	DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO = HEADER_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO
	INNER JOIN	COMPRAS.dbo.ITEM ON	DETAILS_BPO_PEDIDO.K_ITEM=ITEM.K_ITEM
	INNER JOIN	BD_GENERAL.DBO.UNIT_OF_MEASURE ON ITEM.K_UNIT_OF_ITEM = UNIT_OF_MEASURE.K_UNIT_OF_MEASURE
	INNER JOIN	COMPRAS.dbo.VENDOR ON HEADER_BPO_PEDIDO.K_VENDOR = VENDOR.K_VENDOR 
	INNER JOIN	COMPRAS.dbo.DETAILS_BLANKET_PURCHASE_ORDER  ON	DETAILS_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER = DETAILS_BLANKET_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER
	INNER JOIN	ARCUSFIL_SQL ON DETAILS_BLANKET_PURCHASE_ORDER.K_CUSTOMER = ARCUSFIL_SQL.A4GLIdentity
				-- =============================
	 INNER JOIN IMITMIDX_SQL ON  ITEM.K_ITEM = IMITMIDX_SQL.upc_cd
	LEFT JOIN	[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO] ON [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_ORDEN_COMPRA_PEDIDO = DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO
				AND [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_ENTREGA = DETAILS_BPO_RECIBO.K_ENTREGA
				AND [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_ITEM = ITEM.K_ITEM
				AND [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].LOTE_PEARL = DETAILS_BPO_RECIBO.LOTE_PEARL
	WHERE		DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO	
	AND			DETAILS_BPO_RECIBO.K_ENTREGA = @PP_K_ENTREGA				
	AND			DETAILS_BPO_RECIBO.K_ITEM = @PP_K_ITEM					
	AND			DETAILS_BPO_RECIBO.LOTE_PEARL = @PP_LOTE_PEARL			
	ORDER BY	K_ENTREGA DESC

	
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




---- //////////////////////////////////////////////////////////////
---- // STORED PROCEDURE ---> SELECT / FICHA
---- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_ORDEN_COMPRA_X_PEDIDO_PDF]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_ORDEN_COMPRA_X_PEDIDO_PDF]
GO

/*
 
 EXEC	[dbo].[PG_SK_ORDEN_COMPRA_X_PEDIDO_PDF] 0,0,  '00296-00001' , 1 
*/

CREATE PROCEDURE [dbo].[PG_SK_ORDEN_COMPRA_X_PEDIDO_PDF]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA_PEDIDO		VARCHAR(100),
	@PP_K_ENTREGA					INT
	-- ===========================
	
AS

	DECLARE @VP_MENSAJE						VARCHAR(300) = ''
	-- ///////////////////////////////////////////

	SELECT	TOP 1
			DETAILS_BPO_RECIBO.*,
			D_VENDOR AS PROVEDOR
	-- =============================	
	FROM	COMPRAS.dbo.DETAILS_BPO_RECIBO  
		INNER JOIN	COMPRAS.dbo.DETAILS_BPO_PEDIDO  ON	DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO = DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO AND DETAILS_BPO_RECIBO.K_ITEM = DETAILS_BPO_PEDIDO.K_ITEM
	INNER JOIN	COMPRAS.dbo.HEADER_BPO_PEDIDO  ON	DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO = HEADER_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO
	INNER JOIN	COMPRAS.dbo.VENDOR ON HEADER_BPO_PEDIDO.K_VENDOR = VENDOR.K_VENDOR 
	-- =============================
	WHERE		DETAILS_BPO_RECIBO.K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO	
	AND			DETAILS_BPO_RECIBO.K_ENTREGA = @PP_K_ENTREGA				
	--AND			DETAILS_BPO_RECIBO.K_ITEM = @PP_K_ITEM					
	--AND			DETAILS_BPO_RECIBO.LOTE_PEARL = @PP_LOTE_PEARL			
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_ITEM_PENDIENTE_INSPECCION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_ITEM_PENDIENTE_INSPECCION]
GO
/* 
 EXEC	[dbo].[PG_LI_ITEM_PENDIENTE_INSPECCION] 0,0, 10 
*/
CREATE PROCEDURE [dbo].[PG_LI_ITEM_PENDIENTE_INSPECCION]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_STATUS_INVENTARIO			INT
	-- ===========================
AS

	DECLARE @VP_MENSAJE				VARCHAR(300) = ''
	-- ///////////////////////////////////////////
	-- SELECT * FROM STATUS_INVENTARIO
	SELECT	DISTINCT 
			K_ORDEN_COMPRA_PEDIDO,
			K_ENTREGA,
			ITEM.K_ITEM,
			PART_NUMBER_ITEM_PEARL,
			LTRIM(RTRIM(TRADEMARK_ITEM)) AS D_ITEM
	FROM	INVENTARIO
	INNER JOIN COMPRAS.dbo.ITEM AS ITEM ON ITEM.K_ITEM = INVENTARIO.K_ITEM
	WHERE K_STATUS_INVENTARIO = @PP_K_STATUS_INVENTARIO
	ORDER BY ITEM.K_ITEM
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
