-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[DATA_02Pruebas]
-- // MODULO:			QA INSPECCION DE MATERIAL
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	01/SEP/2020
-- //////////////////////////////////////////////////////////////  

USE [DATA_02Pruebas]
GO

-- //////////////////////////////////////////////////////////////



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_NUMERO_PARTE_X_K_ORDEN_COMPRA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_NUMERO_PARTE_X_K_ORDEN_COMPRA]
GO
/* 
 EXEC	[dbo].[PG_LI_NUMERO_PARTE_X_K_ORDEN_COMPRA] 0,0, '00019-00001'
*/
CREATE PROCEDURE [dbo].PG_LI_NUMERO_PARTE_X_K_ORDEN_COMPRA
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA_PEDIDO		VARCHAR(50)
	-- ===========================
AS

	DECLARE @VP_MENSAJE				VARCHAR(300) = ''
	-- ///////////////////////////////////////////
	
	
	SELECT	DISTINCT
		DETAILS_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER AS K_ORDEN_COMPRA,
		DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO AS ORDEN_COMPRA_PEDIDO,
		DETAILS_BPO_PEDIDO.K_DETAILS_BPO_PEDIDO	AS K_DETAILS_PURCHASE_ORDER,
		DETAILS_BPO_PEDIDO.K_ITEM,
		LTRIM(RTRIM(PROD_CAT))		AS PRODUCTO_CATEGORIA,
		-- ===========================	-- ===========================
		S_UNIT_OF_MEASURE,
		PART_NUMBER_ITEM_VENDOR,
		PART_NUMBER_ITEM_PEARL,
		D_ITEM,
		D_VENDOR AS PROVEDOR,
		cus_no AS CLIENTE,
		-- ===========================	-- ===========================
		QUANTITY_ORDER AS QUANTITY,
		-- ===========================
		(CASE WHEN ISNULL(INSPECCION_TERMINADA, 0) = 1
				THEN	'SI'
			ELSE 'NO' END ) AS INSPECCION_TERMINADA,
		-- ===========================
		( CASE WHEN ISNULL(INSPECCION_TERMINADA, 0) = 1 AND ISNULL(APROBACION_SISTEMA, 0) = 1
				THEN 'ACEPTADO SISTEMA'
			WHEN ISNULL(INSPECCION_TERMINADA, 0) = 1 AND ISNULL(APROBACION_SISTEMA, 0) = 0 AND ISNULL(APROBACION_MANUAL, 0) = 1
				THEN 'ACEPTADO MANUAL'
			WHEN ISNULL(INSPECCION_TERMINADA, 0) = 1 AND ISNULL(APROBACION_SISTEMA, 0) = 0 AND ISNULL(APROBACION_MANUAL, 0) = 0
				THEN 'RECHAZADO'
			WHEN ISNULL(INSPECCION_TERMINADA, 0) = 0 
				THEN 'PENDIENTE' END ) AS ESTATUS
		-- ===========================
				-- =============================	
	FROM		COMPRAS_PRUEBAS.dbo.DETAILS_BPO_PEDIDO
	INNER JOIN	COMPRAS_PRUEBAS.dbo.HEADER_BPO_PEDIDO  ON	DETAILS_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER=HEADER_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER
	INNER JOIN	COMPRAS_PRUEBAS.dbo.ITEM		ON	DETAILS_BPO_PEDIDO.K_ITEM=ITEM.K_ITEM
	INNER JOIN	BD_GENERAL.DBO.UNIT_OF_MEASURE ON ITEM.K_UNIT_OF_ITEM = UNIT_OF_MEASURE.K_UNIT_OF_MEASURE
	INNER JOIN	COMPRAS_PRUEBAS.dbo.VENDOR ON HEADER_BPO_PEDIDO.K_VENDOR = VENDOR.K_VENDOR 
	INNER JOIN	ARCUSFIL_SQL ON HEADER_BPO_PEDIDO.K_CUSTOMER = ARCUSFIL_SQL.A4GLIdentity
				-- =============================
	 INNER JOIN IMITMIDX_SQL ON  ITEM.K_ITEM = IMITMIDX_SQL.upc_cd
	LEFT JOIN	[INSPECCION_MATERIAL_ORDEN_RESULTADO] ON [INSPECCION_MATERIAL_ORDEN_RESULTADO].K_ORDEN_COMPRA = DETAILS_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER
				AND [INSPECCION_MATERIAL_ORDEN_RESULTADO].K_ITEM = ITEM.K_ITEM
				AND  [INSPECCION_MATERIAL_ORDEN_RESULTADO].ORDEN_COMPRA_PEDIDO = DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO

	WHERE		DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO=@PP_K_ORDEN_COMPRA_PEDIDO 
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_NUMERO_PARTE_X_K_DETALLE_ORDEN]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_NUMERO_PARTE_X_K_DETALLE_ORDEN]
GO
/*
 EXEC	[dbo].[PG_SK_NUMERO_PARTE_X_K_DETALLE_ORDEN] 0,0, 19,'00019-00001', 2
*/


CREATE PROCEDURE [dbo].[PG_SK_NUMERO_PARTE_X_K_DETALLE_ORDEN]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA				INT,
	@PP_ORDEN_COMPRA_PEDIDO			VARCHAR(50),
	@PP_K_DETALLE_ORDEN				INT
	-- ===========================
AS
	-- ///////////////////////////////////////////

	SELECT	DISTINCT
		DETAILS_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER AS K_ORDEN_COMPRA,
		DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO AS ORDEN_COMPRA_PEDIDO,
		DETAILS_BPO_PEDIDO.K_DETAILS_BPO_PEDIDO	AS K_DETAILS_PURCHASE_ORDER,
		DETAILS_BPO_PEDIDO.K_ITEM,
		-- ===========================
		S_UNIT_OF_MEASURE,
		PART_NUMBER_ITEM_VENDOR,
		PART_NUMBER_ITEM_PEARL,
		D_ITEM,
		D_VENDOR AS PROVEDOR,
		cus_no AS CLIENTE,
		-- ===========================
		QUANTITY_ORDER AS QUANTITY,
		-- ===========================
		(	SELECT COUNT(K_INSPECCION_MATERIAL) 
			FROM INSPECCION_MATERIAL 
			WHERE K_ITEM = DETAILS_BPO_PEDIDO.K_ITEM
			AND	K_ESTATUS_INSPECCION_MATERIAL = 1 /*ACTIVA*/ ) AS TOTAL_INSPECCION,
		-- ===========================
		ISNULL(( SELECT TOP 1 PORCENTAJE_APROBATORIO
			FROM INSPECCION_MATERIAL 
			WHERE K_ITEM=DETAILS_BPO_PEDIDO.K_ITEM
			AND	K_ESTATUS_INSPECCION_MATERIAL = 1 /*ACTIVA*/), 0) AS PORCENTAJE_APROBATORIO,
		-- ===========================
		ISNULL(( SELECT ISNULL(SUM(INSPECCION_PORCENTAJE), 0)
			FROM INSPECCION_MATERIAL 
			WHERE K_ITEM=DETAILS_BPO_PEDIDO.K_ITEM
			AND	K_ESTATUS_INSPECCION_MATERIAL = 1 /*ACTIVA*/), 0) AS TOTAL_PORCENTAJE_INSPECCIONAR,
		-- ===========================
		ISNULL([TOTAL_PORCENTAJE_ACUMULADO], 0.00) AS TOTAL_PORCENTAJE_ACUMULADO,
		-- ===========================
		(CASE WHEN ISNULL(INSPECCION_TERMINADA, 0) = 1
				THEN	'SI'
			ELSE 'NO' END ) AS INSPECCION_TERMINADA,
		-- ===========================
		( CASE WHEN ISNULL(INSPECCION_TERMINADA, 0) = 1 AND ISNULL(APROBACION_SISTEMA, 0) = 1
				THEN 'ACEPTADO SISTEMA'
			WHEN ISNULL(INSPECCION_TERMINADA, 0) = 1 AND ISNULL(APROBACION_SISTEMA, 0) = 0 AND ISNULL(APROBACION_MANUAL, 0) = 1
				THEN 'ACEPTADO MANUAL'
			WHEN ISNULL(INSPECCION_TERMINADA, 0) = 1 AND ISNULL(APROBACION_SISTEMA, 0) = 0 AND ISNULL(APROBACION_MANUAL, 0) = 0
				THEN 'RECHAZADO'
			WHEN ISNULL(INSPECCION_TERMINADA, 0) = 0 
				THEN 'PENDIENTE' END ) AS ESTATUS
		-- ===========================
				-- =============================	
	FROM		COMPRAS_PRUEBAS.dbo.DETAILS_BPO_PEDIDO
	INNER JOIN	COMPRAS_PRUEBAS.dbo.HEADER_BPO_PEDIDO  ON	DETAILS_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER=HEADER_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER
	INNER JOIN	COMPRAS_PRUEBAS.dbo.ITEM		ON	DETAILS_BPO_PEDIDO.K_ITEM=ITEM.K_ITEM
	INNER JOIN	BD_GENERAL.DBO.UNIT_OF_MEASURE ON ITEM.K_UNIT_OF_ITEM = UNIT_OF_MEASURE.K_UNIT_OF_MEASURE
	INNER JOIN	COMPRAS_PRUEBAS.dbo.VENDOR ON HEADER_BPO_PEDIDO.K_VENDOR = VENDOR.K_VENDOR 
	INNER JOIN	ARCUSFIL_SQL ON HEADER_BPO_PEDIDO.K_CUSTOMER = ARCUSFIL_SQL.A4GLIdentity
				-- =============================
	LEFT JOIN	[INSPECCION_MATERIAL_ORDEN_RESULTADO] ON [INSPECCION_MATERIAL_ORDEN_RESULTADO].K_ORDEN_COMPRA = DETAILS_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER
				AND [INSPECCION_MATERIAL_ORDEN_RESULTADO].K_ITEM = ITEM.K_ITEM
				AND  [INSPECCION_MATERIAL_ORDEN_RESULTADO].ORDEN_COMPRA_PEDIDO = DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO

	WHERE		DETAILS_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO=@PP_ORDEN_COMPRA_PEDIDO
	AND			DETAILS_BPO_PEDIDO.K_DETAILS_BPO_PEDIDO = @PP_K_DETALLE_ORDEN
	AND			DETAILS_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER = @PP_K_ORDEN_COMPRA
	ORDER BY	K_DETAILS_BPO_PEDIDO

	
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_ORDEN_COMPRA_X_PEDIDO_PDF]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_ORDEN_COMPRA_X_PEDIDO_PDF]
GO

/*
 EXEC	[dbo].[PG_SK_ORDEN_COMPRA_X_PEDIDO_PDF] 0,0, '00019-00001'
*/

CREATE PROCEDURE [dbo].[PG_SK_ORDEN_COMPRA_X_PEDIDO_PDF]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_ORDEN_COMPRA_PEDIDO			VARCHAR(50)
	
AS

	DECLARE @VP_MENSAJE						VARCHAR(300) = ''
	-- ///////////////////////////////////////////

	SELECT	
			HEADER_BPO_PEDIDO.*,
			D_VENDOR AS PROVEDOR
	-- =============================	
	FROM	COMPRAS_PRUEBAS.dbo.HEADER_BPO_PEDIDO  
	INNER JOIN	COMPRAS_PRUEBAS.dbo.VENDOR ON HEADER_BPO_PEDIDO.K_VENDOR = VENDOR.K_VENDOR 
	-- =============================
	WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
