-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[DATA_02Pruebas]
-- // MODULO:			QA INSPECCION DE MATERIAL
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	04/SEP/2020
-- //////////////////////////////////////////////////////////////  

USE [DATA_02Pruebas]
GO

-- //////////////////////////////////////////////////////////////




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN] 0,0, 10, '10-001', 35, 1
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA				INT,
	@PP_ORDEN_COMPRA_PEDIDO			VARCHAR(50),
	@PP_K_ITEM						INT,
	@PP_K_INSPECCION_MATERIAL		INT
	
AS

	DECLARE @VP_MENSAJE						VARCHAR(300) = ''
	-- ///////////////////////////////////////////

	SELECT	
			[INSPECCION_MATERIAL_ORDEN].*,
			INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	-- =============================	
	FROM	[INSPECCION_MATERIAL_ORDEN]
	INNER JOIN INSPECCION_MATERIAL ON [INSPECCION_MATERIAL_ORDEN].K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
			AND [INSPECCION_MATERIAL_ORDEN].K_ITEM = INSPECCION_MATERIAL.K_ITEM
	INNER JOIN	TIPO_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	-- =============================
	WHERE	K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
	AND		ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
	AND		[INSPECCION_MATERIAL_ORDEN].K_ITEM = @PP_K_ITEM
	AND		[INSPECCION_MATERIAL_ORDEN].K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_RESULTADO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_RESULTADO]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_RESULTADO] 0,0, 19, '00019-00001', 36
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_RESULTADO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA				INT,
	@PP_ORDEN_COMPRA_PEDIDO			VARCHAR(50),
	@PP_K_ITEM						INT
AS

	DECLARE @VP_MENSAJE						VARCHAR(300) = ''
	-- ///////////////////////////////////////////

	SELECT	
			[INSPECCION_MATERIAL_ORDEN_RESULTADO].*,
			-- ===========================
		( CASE WHEN ISNULL(INSPECCION_TERMINADA, 0) = 1 AND ISNULL(APROBACION_SISTEMA, 0) = 1
				THEN 'ACEPTADO SISTEMA'
			WHEN ISNULL(INSPECCION_TERMINADA, 0) = 1 AND ISNULL(APROBACION_SISTEMA, 0) = 0 AND ISNULL(APROBACION_MANUAL, 0) = 1
				THEN 'ACEPTADO MANUAL'
			WHEN ISNULL(INSPECCION_TERMINADA, 0) = 1 AND ISNULL(APROBACION_SISTEMA, 0) = 0 AND ISNULL(APROBACION_MANUAL, 0) = 0
				THEN 'RECHAZADO'
			WHEN ISNULL(INSPECCION_TERMINADA, 0) = 0 
				THEN 'PENDIENTE' END ) AS ESTATUS,
		-- ===========================
		PART_NUMBER_ITEM_PEARL
	-- =============================	
	FROM	[INSPECCION_MATERIAL_ORDEN_RESULTADO]
	INNER JOIN	COMPRAS_PRUEBAS.dbo.ITEM		ON	[INSPECCION_MATERIAL_ORDEN_RESULTADO].K_ITEM=ITEM.K_ITEM
	-- =============================
	WHERE	K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
	AND		ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
	AND		[INSPECCION_MATERIAL_ORDEN_RESULTADO].K_ITEM = @PP_K_ITEM
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_AUTORIZAR_MATERIAL_ORDEN]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_AUTORIZAR_MATERIAL_ORDEN]
GO

/*
 EXEC	[dbo].[PG_LI_AUTORIZAR_MATERIAL_ORDEN] 0,0, 19,'00019-00001',36
*/

CREATE PROCEDURE [dbo].[PG_LI_AUTORIZAR_MATERIAL_ORDEN]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA				INT,
	@PP_ORDEN_COMPRA_PEDIDO			VARCHAR(50),
	@PP_K_ITEM						INT
	
AS

	DECLARE @VP_MENSAJE						VARCHAR(300) = ''
	-- ///////////////////////////////////////////

	SELECT	--DISTINCT
			[INSPECCION_MATERIAL_ORDEN].*,
			INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL,
			INSPECCION_MATERIAL.INSPECCION,
			INSPECCION_MATERIAL.INSPECCION_PORCENTAJE,
			PART_NUMBER_ITEM_PEARL AS NUMERO_PARTE,
			-- =============================	
			( CASE WHEN K_TIPO_INSPECCION_MATERIAL = 2
						THEN OPCION_1
				ELSE 'N/A'	END )	AS VALOR_MINIMO,
			-- =============================	
			( CASE WHEN K_TIPO_INSPECCION_MATERIAL = 2
						THEN OPCION_2
				ELSE 'N/A'	END )	AS VALOR_MAXIMO,
			BD_GENERAL.dbo.USUARIO_PEARL.D_USUARIO_PEARL
			-- =============================	
	FROM	[INSPECCION_MATERIAL_ORDEN]
	INNER JOIN COMPRAS_PRUEBAS.dbo.ITEM ON [INSPECCION_MATERIAL_ORDEN].K_ITEM = ITEM.K_ITEM
	INNER JOIN INSPECCION_MATERIAL ON [INSPECCION_MATERIAL_ORDEN].K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
			AND [INSPECCION_MATERIAL_ORDEN].K_ITEM = INSPECCION_MATERIAL.K_ITEM
	INNER JOIN	INSPECCION_OPCION ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
	INNER JOIN	BD_GENERAL.dbo.USUARIO_PEARL ON	[INSPECCION_MATERIAL_ORDEN].K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
	-- =============================
	WHERE	[INSPECCION_MATERIAL_ORDEN].K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
	AND		[INSPECCION_MATERIAL_ORDEN].ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
	AND		[INSPECCION_MATERIAL_ORDEN].K_ITEM = @PP_K_ITEM
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_A_MODIFICAR]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_A_MODIFICAR]
GO
/*
 EXEC	[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_A_MODIFICAR] 0,0,1
*/


CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_A_MODIFICAR]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_INSPECCION_MATERIAL_ORDEN	INT
	-- ===========================
AS
	-- ///////////////////////////////////////////

	SELECT	TOP (5000)  
		INSPECCION_MATERIAL_ORDEN.K_INSPECCION_MATERIAL,
		INSPECCION_MATERIAL_ORDEN.K_ORDEN_COMPRA,
		INSPECCION_MATERIAL_ORDEN.ORDEN_COMPRA_PEDIDO,
		INSPECCION_MATERIAL_ORDEN.K_ITEM,
		VENDOR.D_VENDOR AS PROVEDOR,
		CUS_NO AS CLIENTE,
		-- ===========================
		PORCENTAJE_APROBATORIO,
		-- ===========================
		TOTAL_PORCENTAJE_ACUMULADO,
		-- ===========================
		PART_NUMBER_ITEM_VENDOR,
		PART_NUMBER_ITEM_PEARL,
		D_ITEM,
		(SELECT  TOP 1 QUANTITY_ORDER FROM COMPRAS_PRUEBAS.dbo.DETAILS_BPO_PEDIDO 
		WHERE K_HEADER_PURCHASE_ORDER = INSPECCION_MATERIAL_ORDEN.K_ORDEN_COMPRA
		AND K_ITEM = INSPECCION_MATERIAL_ORDEN.K_ITEM 
		AND K_ORDEN_COMPRA_PEDIDO = INSPECCION_MATERIAL_ORDEN.ORDEN_COMPRA_PEDIDO) 	AS QUANTITY
	FROM	INSPECCION_MATERIAL_ORDEN
	INNER JOIN	COMPRAS_PRUEBAS.dbo.ITEM		ON	INSPECCION_MATERIAL_ORDEN.K_ITEM=ITEM.K_ITEM

	INNER JOIN	COMPRAS_PRUEBAS.dbo.HEADER_BPO_PEDIDO ON INSPECCION_MATERIAL_ORDEN.K_ORDEN_COMPRA = COMPRAS_PRUEBAS.dbo.HEADER_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER

	INNER JOIN	COMPRAS_PRUEBAS.dbo.VENDOR ON HEADER_BPO_PEDIDO.K_VENDOR = VENDOR.K_VENDOR

	INNER JOIN	ARCUSFIL_SQL ON HEADER_BPO_PEDIDO.K_CUSTOMER = ARCUSFIL_SQL.A4GLIdentity

	LEFT JOIN	[INSPECCION_MATERIAL_ORDEN_RESULTADO] ON HEADER_BPO_PEDIDO.K_HEADER_PURCHASE_ORDER = [INSPECCION_MATERIAL_ORDEN_RESULTADO].K_ORDEN_COMPRA
				AND	ITEM.K_ITEM = [INSPECCION_MATERIAL_ORDEN_RESULTADO].K_ITEM
	WHERE	INSPECCION_MATERIAL_ORDEN.K_INSPECCION_MATERIAL_ORDEN = @PP_K_INSPECCION_MATERIAL_ORDEN
	ORDER BY	K_INSPECCION_MATERIAL_ORDEN

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO





IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_IN_INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_IN_INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]
GO


CREATE PROCEDURE [dbo].[PG_IN_INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA					INT,
	@PP_ORDEN_COMPRA_PEDIDO				VARCHAR(50),
	@PP_ORDEN_COMPRA_PEDIDO_ENTREGA		INT,
	@PP_K_ITEM							INT,
	@PP_LOCACION_DESTINO				VARCHAR(5)
	-- ===========================
AS

	

	INSERT INTO INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION	
					(					
						[K_ORDEN_COMPRA],							
						[ORDEN_COMPRA_PEDIDO],					
						[ORDEN_COMPRA_PEDIDO_ENTREGA],		
						[K_ITEM],				
						[LOCACION_DESTINO],							
						-- =================================
						[K_USUARIO_ALTA],
						[F_INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]	)
						-- ===========================
				VALUES	
					(	
						@PP_K_ORDEN_COMPRA,							
						@PP_ORDEN_COMPRA_PEDIDO,
						@PP_ORDEN_COMPRA_PEDIDO_ENTREGA,					
						@PP_K_ITEM,							
						@PP_LOCACION_DESTINO,		
						-- ===========================				
						@PP_K_USUARIO_ACCION, 
						GETDATE()	)	
		
		IF @@ROWCOUNT = 0
			RAISERROR ('ERROR SP: INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION', 16, 1 ) --MENSAJE - Severity -State.
	-- ///////////////////////////////////////////
		

	-- ///////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////

GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> INSERT
-- //////////////////////////////////////////////////////////////

--PG_IN_UP_INSPECCION_MATERIAL_ORDEN
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_IN_UP_INSPECCION_MATERIAL_ORDEN]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_IN_UP_INSPECCION_MATERIAL_ORDEN]
GO
/*
 EXECUTE [PG_IN_UP_INSPECCION_MATERIAL_ORDEN] 0,0,    78 , '200435AWT3' , 1 , 2 , '1.1' , '' 
*/
CREATE PROCEDURE [dbo].[PG_IN_UP_INSPECCION_MATERIAL_ORDEN]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================	
	@PP_K_ORDEN_COMPRA					INT,
	@PP_ORDEN_COMPRA_PEDIDO				VARCHAR(50),
	@PP_K_ITEM							INT,
	@PP_K_INSPECCION_MATERIAL			INT,
	@PP_TIPO_INSPECCION_MATERIAL		INT,
	-- ===========================	
	@PP_RESULTADO_INSPECCION			VARCHAR(255),
	@PP_COMENTARIO						VARCHAR(255)
	-- ============================			
AS			
	
	DECLARE @VP_MENSAJE		VARCHAR(300) = ''
	
	-- // SECCION#1 /////////////////////////////////////////////////////////// VALIDACIONES + REGLAS DE NEGOCIO 	
	
	DECLARE @VP_K_INSPECCION_MATERIAL_ORDEN	INT = 0
	
	--IF @VP_MENSAJE=''	
		--EXECUTE [dbo].[PG_RN_INSPECCION_MATERIAL_ORDEN_INSERT]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
		--													@PP_INSPECCION_PORCENTAJE, @PP_OPCION_1_PORCENTAJE,
		--													@PP_OPCION_2_PORCENTAJE, @PP_OPCION_3_PORCENTAJE,
		--													@PP_OPCION_4_PORCENTAJE, @PP_OPCION_5_PORCENTAJE,
		--													@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	-- // SECCION#2 ////////////////////////////////////////////////////////// ACCION A REALIZAR
	
	IF @VP_MENSAJE=''
		BEGIN
			BEGIN TRANSACTION 
			BEGIN TRY
				DECLARE @VP_OPCION_SELECCIONADA_ANTERIOR VARCHAR(255) = ''
				

				-- ///////SE VERIFICA SI YA EXISTE LA ORDEN CON ESE NUMERO DE PARTE Y ESA INSPECCION EN INSPECCION_MATERIAL_ORDEN//////////////////
				DECLARE @VP_N_INSPECCION_MATERIAL_ORDEN  INT = 0

				SELECT	@VP_N_INSPECCION_MATERIAL_ORDEN = COUNT([K_INSPECCION_MATERIAL_ORDEN])
				FROM	INSPECCION_MATERIAL_ORDEN
				WHERE	K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
				AND		ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
				AND		K_ITEM = @PP_K_ITEM
				AND		K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL
				
				IF 	@VP_N_INSPECCION_MATERIAL_ORDEN IS NULL
					SET @VP_N_INSPECCION_MATERIAL_ORDEN = 0

				-- ///////SI NO EXISTE UNA INSPECCION CON ESA ORDEN, NUMERO DE PARTE E INSPECCION SE INGRESA EL REGISTRO SI NO SE ACTUALIZA//////////////////
				IF @VP_N_INSPECCION_MATERIAL_ORDEN = 0
					BEGIN
						EXECUTE BD_GENERAL.dbo.[PG_SK_CATALOGO_K_MAX_GET] @PP_K_SISTEMA_EXE,
																				'DATA_02Pruebas', 'INSPECCION_MATERIAL_ORDEN', 'K_INSPECCION_MATERIAL_ORDEN',
																				@OU_K_TABLA_DISPONIBLE = @VP_K_INSPECCION_MATERIAL_ORDEN	OUTPUT

						-- ///////SE INSERTA LA INSPECCION DEL MATERIAL///////////////////////////////////////////////////////
						INSERT INTO [INSPECCION_MATERIAL_ORDEN]
							(	[K_INSPECCION_MATERIAL_ORDEN],
								-- ===========================
								[K_ORDEN_COMPRA],
								[ORDEN_COMPRA_PEDIDO],	
								[K_ITEM],
								[K_INSPECCION_MATERIAL],
								-- ===========================
								[OPCION_SELECCIONADA],
								[COMENTARIO],
								[F_INSPECCION_MATERIAL_ORDEN],
								-- ===========================
								[K_USUARIO_ALTA], [F_ALTA], [K_USUARIO_CAMBIO], [F_CAMBIO],
								[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]  )
						VALUES	
							(	@VP_K_INSPECCION_MATERIAL_ORDEN,
								-- ===========================	
								@PP_K_ORDEN_COMPRA,
								@PP_ORDEN_COMPRA_PEDIDO,
								@PP_K_ITEM,
								@PP_K_INSPECCION_MATERIAL,
								-- ===========================
								@PP_RESULTADO_INSPECCION,
								@PP_COMENTARIO,
								GETDATE(),
								-- ===========================
								@PP_K_USUARIO_ACCION, GETDATE(), @PP_K_USUARIO_ACCION, GETDATE(),
								0, NULL, NULL )

						IF @@ROWCOUNT = 0
							RAISERROR ('ERROR: No fue posible ingresar el registro en [INSPECCION_MATERIAL_ORDEN] ', 16, 1 ) --MENSAJE - Severity -State.
							--=====================================================
					END
				ELSE
					BEGIN
						-- ///////SI ES UNA INSPECCION TIPO 2 SE OBTIENE EL VALOR INGRESADO ANTERIORMENTE//////////////////
						IF @PP_TIPO_INSPECCION_MATERIAL = '2' --EVALUACION
							SELECT @VP_OPCION_SELECCIONADA_ANTERIOR = [OPCION_SELECCIONADA]
																	FROM	[INSPECCION_MATERIAL_ORDEN]
																	WHERE	K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
																	AND		ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
																	AND		K_ITEM = @PP_K_ITEM
																	AND		K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL

						-- ///////SI ACTUALIZA LA INSPECCION CON ESA ORDEN, NUMERO DE PARTE E INSPECCION EN [INSPECCION_MATERIAL_ORDEN]//////////////////
						UPDATE [INSPECCION_MATERIAL_ORDEN]
							SET	[OPCION_SELECCIONADA]			= @PP_RESULTADO_INSPECCION,
								[COMENTARIO]					= @PP_COMENTARIO,
								[F_INSPECCION_MATERIAL_ORDEN]	= GETDATE(),
								F_CAMBIO						= GETDATE(),
								K_USUARIO_CAMBIO				= @PP_K_USUARIO_ACCION
						WHERE	K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
						AND		ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
						AND		K_ITEM = @PP_K_ITEM
						AND		K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL
						
						IF @@ROWCOUNT = 0
							RAISERROR ('ERROR: No fue posible actualizar el registro en [INSPECCION_MATERIAL_ORDEN] ', 16, 1 ) --MENSAJE - Severity -State.

					END

				-- /////////////SE VERIFICA SI LA ORDEN Y EL NUMERO DE PARTE EXISTEN EN INSPECCION_MATERIAL_ORDEN_RESULTADO//////////////////////////////
				DECLARE @VP_N_INSPECCION_MATERIAL_ORDEN_RESULTADO INT = 0
				SELECT	@VP_N_INSPECCION_MATERIAL_ORDEN_RESULTADO = COUNT(K_INSPECCION_MATERIAL_ORDEN_RESULTADO)
																FROM	INSPECCION_MATERIAL_ORDEN_RESULTADO
																WHERE	K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
																AND		ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
																AND		K_ITEM = @PP_K_ITEM

				IF @VP_N_INSPECCION_MATERIAL_ORDEN_RESULTADO IS NULL
					SET @VP_N_INSPECCION_MATERIAL_ORDEN_RESULTADO = 0

				-- ///////SE OBTIENE EL PORCENTAJE APROBATORIO PARA EL NUMERO DE PARTE///////////////////////////////////////////////////////
				DECLARE @VP_PORCENTAJE_APROBATORIO DECIMAL(13,2) = 0
				SELECT TOP 1 @VP_PORCENTAJE_APROBATORIO = PORCENTAJE_APROBATORIO
														FROM INSPECCION_MATERIAL
														WHERE K_ITEM = @PP_K_ITEM

				IF @VP_PORCENTAJE_APROBATORIO IS NULL
					SET @VP_PORCENTAJE_APROBATORIO = 0

				-- ///////SE OBTIENE EL PORCENTAJE DE LA INSPECCION///////////////////////////////////////////////////////
				DECLARE @VP_PORCENTAJE_INSPECCION DECIMAL(13,2) = 0
				SELECT TOP 1 @VP_PORCENTAJE_INSPECCION = INSPECCION_PORCENTAJE
														FROM INSPECCION_MATERIAL
														WHERE K_ITEM = @PP_K_ITEM
														AND	K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL

				IF @VP_PORCENTAJE_INSPECCION IS NULL
					SET @VP_PORCENTAJE_INSPECCION = 0

				-- ///////SE OBTIENE EL PORCENTAJE ACUMULADO PARA EL NUMERO DE PARTE EN LA ORDEN///////////////////////////////////////////////////////
				DECLARE @VP_PORCENTAJE_ACUMULADO INT = 0
				SELECT	@VP_PORCENTAJE_ACUMULADO = TOTAL_PORCENTAJE_ACUMULADO
												FROM	[INSPECCION_MATERIAL_ORDEN_RESULTADO]
												WHERE	K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
												AND		ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
												AND		K_ITEM = @PP_K_ITEM
				 
				 IF @VP_PORCENTAJE_ACUMULADO IS NULL
					SET @VP_PORCENTAJE_ACUMULADO = 0

				
				-- ///////SE SUMA AL PORCENTAJE ACUMULADO POR ESE NUMERO DE PARTE EL PORCENTAJE DE LA INSPECCION PREVIA VALIDACION EN EL CASO 2///////////////////////////////////////////////////////
				IF @PP_TIPO_INSPECCION_MATERIAL = '1'
					SET @VP_PORCENTAJE_ACUMULADO = @VP_PORCENTAJE_ACUMULADO + @VP_PORCENTAJE_INSPECCION
				
				IF @PP_TIPO_INSPECCION_MATERIAL = '2'
					BEGIN
						DECLARE @VALOR_MINIMO DECIMAL(13,2) = 0
						DECLARE @VALOR_MAXIMO DECIMAL(13,2) = 0

						SELECT  @VALOR_MINIMO = CONVERT(DECIMAL(13,2),ISNULL(OPCION_1, 00)),
								@VALOR_MAXIMO = CONVERT(DECIMAL(13,2),ISNULL(OPCION_2, 00))
						FROM INSPECCION_OPCION
						WHERE [K_INSPECCION_MATERIAL] = @PP_K_INSPECCION_MATERIAL

						IF ( @VP_OPCION_SELECCIONADA_ANTERIOR <> '' AND @VP_OPCION_SELECCIONADA_ANTERIOR >= @VALOR_MINIMO AND @VP_OPCION_SELECCIONADA_ANTERIOR <= @VALOR_MAXIMO )
							SET @VP_PORCENTAJE_ACUMULADO = @VP_PORCENTAJE_ACUMULADO - @VP_PORCENTAJE_INSPECCION

						DECLARE @VP_VALOR_INSPECCION_DECIMAL DECIMAL(13,2) = CONVERT(DECIMAL(13,2), @PP_RESULTADO_INSPECCION)

						IF @VP_VALOR_INSPECCION_DECIMAL >= @VALOR_MINIMO AND @VP_VALOR_INSPECCION_DECIMAL <= @VALOR_MAXIMO
							SET @VP_PORCENTAJE_ACUMULADO = @VP_PORCENTAJE_ACUMULADO + @VP_PORCENTAJE_INSPECCION

					END

				-- /////////////SE EVALUA EL PORCENTAJE ACUMULADO CON EL PORCENTAJE APROBATORIO PARA APROBAR POR SISTEMA//////////////////////////////
				DECLARE @VP_APROBACION_SISTEMA INT = 0
				DECLARE @VP_APROBACION_MANUAL INT = 0

				IF @VP_PORCENTAJE_ACUMULADO >= @VP_PORCENTAJE_APROBATORIO
					SET @VP_APROBACION_SISTEMA = 1

				-- ///////SE VERIFICA SI EL NUMERO DE INSPECCIONES CONFIGURADAS SON IGUALES A LAS REALIZADAS PARA CERRAR LA INSPECCION DEL MATERIAL//////////////////
				DECLARE @VP_INSPECCION_TERMINADA		INT = 0
				DECLARE @VP_N_INSPECCION_CONFIGURADA	INT = 0
				DECLARE @VP_N_INSPECCION_REALIZADA		INT = 0

				SELECT @VP_N_INSPECCION_CONFIGURADA = COUNT(K_INSPECCION_MATERIAL)
				FROM INSPECCION_MATERIAL
				WHERE K_ITEM = @PP_K_ITEM
				AND K_ESTATUS_INSPECCION_MATERIAL = 1

				IF @VP_N_INSPECCION_CONFIGURADA IS NULL
					SET @VP_N_INSPECCION_CONFIGURADA = 0

				SELECT @VP_N_INSPECCION_REALIZADA = COUNT([K_INSPECCION_MATERIAL_ORDEN])
				FROM [INSPECCION_MATERIAL_ORDEN]
				WHERE K_ITEM = @PP_K_ITEM
				AND K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
				AND ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO

				IF @VP_N_INSPECCION_REALIZADA IS NULL
					SET @VP_N_INSPECCION_REALIZADA = 0

				IF @VP_N_INSPECCION_CONFIGURADA = @VP_N_INSPECCION_REALIZADA
					SET @VP_INSPECCION_TERMINADA = 1

				-- ///////SI NO EXISTE UNA INSPECCION CON ESA ORDEN, NUMERO DE PARTE SE INGRESA EL REGISTRO SI NO SE ACTUALIZA//////////////////
				IF @VP_N_INSPECCION_MATERIAL_ORDEN_RESULTADO = 0
					BEGIN
						-- ///////SE OBTIENE EL CONSECUTIVO DE LA PK DE LA TABLA PARA EL INSERT///////////////////////////////////////////////////////
						DECLARE @VP_K_INSPECCION_MATERIAL_ORDEN_RESULTADO	INT = 0
						EXECUTE BD_GENERAL.dbo.[PG_SK_CATALOGO_K_MAX_GET] @PP_K_SISTEMA_EXE,
																		'DATA_02Pruebas', 'INSPECCION_MATERIAL_ORDEN_RESULTADO', 'K_INSPECCION_MATERIAL_ORDEN_RESULTADO',
																		@OU_K_TABLA_DISPONIBLE = @VP_K_INSPECCION_MATERIAL_ORDEN_RESULTADO	OUTPUT

						-- ///////SE INSERTA LA INSPECCION DEL MATERIAL///////////////////////////////////////////////////////
						INSERT INTO [INSPECCION_MATERIAL_ORDEN_RESULTADO]
							(	[K_INSPECCION_MATERIAL_ORDEN_RESULTADO],
								[K_ORDEN_COMPRA],
								[ORDEN_COMPRA_PEDIDO],
								-- ===========================
								[K_ITEM],
								[PORCENTAJE_APROBATORIO],
								[TOTAL_PORCENTAJE_ACUMULADO],
								INSPECCION_TERMINADA,
								[APROBACION_SISTEMA],
								[APROBACION_MANUAL],
								--[COMENTARIO],
								[K_USUARIO_ALTA],
								[F_INSPECCION_MATERIAL_ORDEN_RESULTADO]	)
								-- ===========================
						VALUES	
							(	@VP_K_INSPECCION_MATERIAL_ORDEN_RESULTADO,
								-- ===========================	
								@PP_K_ORDEN_COMPRA,
								@PP_ORDEN_COMPRA_PEDIDO,
								@PP_K_ITEM,
								-- ===========================	
								@VP_PORCENTAJE_APROBATORIO,
								@VP_PORCENTAJE_ACUMULADO,
								-- ===========================	
								@VP_INSPECCION_TERMINADA,
								@VP_APROBACION_SISTEMA,
								@VP_APROBACION_MANUAL,
								--@PP_COMENTARIO,
								@PP_K_USUARIO_ACCION,
								GETDATE()	)

						IF @@ROWCOUNT = 0
							RAISERROR ('ERROR: No fue posible ingresar el registro en [INSPECCION_MATERIAL_ORDEN_RESULTADO] ', 16, 1 ) --MENSAJE - Severity -State.
							--=====================================================
					END
				ELSE
					BEGIN
						-- ///////SI ACTUALIZA LA INSPECCION CON ESA ORDEN Y NUEMERO DE PARTE EN [INSPECCION_MATERIAL_ORDEN]//////////////////
						UPDATE	[INSPECCION_MATERIAL_ORDEN_RESULTADO]
							SET	[PORCENTAJE_APROBATORIO]					= @VP_PORCENTAJE_APROBATORIO,
								[TOTAL_PORCENTAJE_ACUMULADO]				= @VP_PORCENTAJE_ACUMULADO,
								[INSPECCION_TERMINADA]						= @VP_INSPECCION_TERMINADA,
								[APROBACION_SISTEMA]						= @VP_APROBACION_SISTEMA,
								[APROBACION_MANUAL]							= @VP_APROBACION_MANUAL,
								--[COMENTARIO]								= @PP_COMENTARIO,
								[K_USUARIO_ALTA]							= @PP_K_USUARIO_ACCION,
								[F_INSPECCION_MATERIAL_ORDEN_RESULTADO]		= GETDATE()	
						WHERE K_ITEM = @PP_K_ITEM
						AND K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
						AND ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO

						IF @@ROWCOUNT = 0
							RAISERROR ('ERROR: No fue posible actualizar el registro en [INSPECCION_MATERIAL_ORDEN_RESULTADO] ', 16, 1 ) --MENSAJE - Severity -State.
					END

				-- ///////////SI LA INSPECCION HA TERMINADO SE INGRESA EL REGISTRO PARA LA DISPOSICION///////////////////////////////////////////////////
				IF @VP_INSPECCION_TERMINADA = 1
					BEGIN
						-- //////////////////////SE OBTIENE LA LOCACION MHI POR DEFAULT///////////////////////
						DECLARE @VP_LOCACION_DESTINO VARCHAR(5) = ''
							SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
								FROM	imlocfil_sql 
							WHERE A4GLIdentity = 4
													
						-- //////////////////////SE OBTIENE LA LOCACION MQU SI EL RESULTADO DE LA INSPECCION ES RECHAZADO///////////////////////
						IF @VP_APROBACION_SISTEMA = 0
							SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
							FROM	imlocfil_sql 
							WHERE A4GLIdentity = 6
							
						IF @VP_LOCACION_DESTINO IS NULL
							RAISERROR ('ERROR: No fue posible obtener la locacion en [imlocfil_sql] ', 16, 1 ) --MENSAJE - Severity -State.
							
						IF @VP_LOCACION_DESTINO NOT IN ('MHI','MQU')
							RAISERROR ('ERROR: Locacion no valida.', 16, 1 ) --MENSAJE - Severity -State.

						-- //////////////////////SE VALIDA NO QUE EXISTA EL MATERIAL EN LA TABLA DE DISPOCISION///////////////////////
						DECLARE @VP_N_MATERIAL_ESPERA_DISPOSICION INT = 0
						SELECT @VP_N_MATERIAL_ESPERA_DISPOSICION =  K_INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION
						FROM [INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]
						WHERE K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
						AND ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
						AND ORDEN_COMPRA_PEDIDO_ENTREGA = 1 -- PENDIENTE CARGAR DATO CORRECTO
						AND K_ITEM = @PP_K_ITEM

						IF @VP_N_MATERIAL_ESPERA_DISPOSICION > 0
							RAISERROR ('ERROR: El material esta dado de alta en [INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION] ', 16, 1 ) --MENSAJE - Severity -State.

						-- //////////////////////SE INGRESA EL REGISTRO EN LA TABLA PARA SU DISPOSICION///////////////////////
						EXECUTE [dbo].[PG_IN_INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																							@PP_K_ORDEN_COMPRA, @PP_ORDEN_COMPRA_PEDIDO, 1,
																							@PP_K_ITEM, @VP_LOCACION_DESTINO
						
						-- //////////////////////SE NOTIFICA A LOS RESPONSABLES DE LA LOCACION A DONDE VA EL MATERIAL///////////////////////
						EXECUTE [dbo].[PG_CONFIGURAR_CORREO_MATERIAL_INSPECCIONADO_DISPOSICION] @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																								@PP_K_ORDEN_COMPRA, @PP_ORDEN_COMPRA_PEDIDO, 1,
																								@PP_K_ITEM, @VP_LOCACION_DESTINO

					END
				-- //////////////////////////////////////////////////////////////

			COMMIT TRANSACTION 
			END TRY
	
			BEGIN CATCH
				/* Ocurrió un error, deshacemos los cambios*/ 
				ROLLBACK TRANSACTION
				DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
				SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
				SET @VP_MENSAJE = 'ERROR: //TRANSAC. PG_IN_UP_INSPECCION_MATERIAL_ORDEN // ' + @VP_ERROR_TRANS
			END CATCH
				
		END

	-- // SECCION#3 ////////////////////////////////////////////////////////// MENSAJE DE SALIDA
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Crear] la [INSPECCION_MATERIAL_ORDEN]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#INSP.'+CONVERT(VARCHAR(10),@VP_K_INSPECCION_MATERIAL_ORDEN)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'
	
		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @VP_K_INSPECCION_MATERIAL_ORDEN AS CLAVE

	-- //////////////////////////////////////////////////////////////

GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> INSERT
-- //////////////////////////////////////////////////////////////

--PG_IN_UP_INSPECCION_MATERIAL_ORDEN
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN]
GO
/*
 EXECUTE [PG_UP_INSPECCION_MATERIAL_ORDEN] 0,0,    10 , '10-001' , 35 , 2 , 2 , '0.9' , 'SE MODIFICO RESULTADO PORQUE SE CAPTURO MAL' 
*/
CREATE PROCEDURE [dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================	
	@PP_K_ORDEN_COMPRA					INT,
	@PP_ORDEN_COMPRA_PEDIDO				VARCHAR(50),
	@PP_K_ITEM							INT,
	@PP_K_INSPECCION_MATERIAL			INT,
	@PP_TIPO_INSPECCION_MATERIAL		INT,
	-- ===========================	
	@PP_RESULTADO_INSPECCION			VARCHAR(255),
	@PP_D_USUARIO_AUTORIZACION			VARCHAR(150),
	@PP_COMENTARIO						VARCHAR(255)
	-- ============================			
AS			
	
	DECLARE @VP_MENSAJE		VARCHAR(300) = ''
	
	-- // SECCION#1 /////////////////////////////////////////////////////////// VALIDACIONES + REGLAS DE NEGOCIO 	
	
	DECLARE @VP_K_INSPECCION_MATERIAL_ORDEN	INT = 0
	
	IF @VP_MENSAJE=''	
		--EXECUTE [dbo].[PG_RN_INSPECCION_MATERIAL_ORDEN_UPDATE]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
		--														@PP_INSPECCION_PORCENTAJE, @PP_OPCION_1_PORCENTAJE,
		--														@PP_OPCION_2_PORCENTAJE, @PP_OPCION_3_PORCENTAJE,
		--														@PP_OPCION_4_PORCENTAJE, @PP_OPCION_5_PORCENTAJE,
		--														@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	-- // SECCION#2 ////////////////////////////////////////////////////////// ACCION A REALIZAR
	
	IF @VP_MENSAJE=''
		BEGIN
			BEGIN TRANSACTION 
			BEGIN TRY
				DECLARE @VP_OPCION_SELECCIONADA_ANTERIOR VARCHAR(255) = ''
				
				-- ///////SI ES UNA INSPECCION TIPO 2 SE OBTIENE EL VALOR INGRESADO ANTERIORMENTE//////////////////
				SELECT @VP_OPCION_SELECCIONADA_ANTERIOR = [OPCION_SELECCIONADA]
														FROM	[INSPECCION_MATERIAL_ORDEN]
														WHERE	K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
														AND		ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
														AND		K_ITEM = @PP_K_ITEM
														AND		K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL

				-- ///////SI ACTUALIZA LA INSPECCION CON ESA ORDEN, NUMERO DE PARTE E INSPECCION EN [INSPECCION_MATERIAL_ORDEN]//////////////////
				UPDATE [INSPECCION_MATERIAL_ORDEN]
					SET	[OPCION_SELECCIONADA]			= @PP_RESULTADO_INSPECCION,
						[COMENTARIO]					= @PP_COMENTARIO,
						[F_INSPECCION_MATERIAL_ORDEN]	= GETDATE(),
						F_CAMBIO						= GETDATE(),
						K_USUARIO_CAMBIO				= @PP_K_USUARIO_ACCION
				WHERE	K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
				AND		ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
				AND		K_ITEM = @PP_K_ITEM
				AND		K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL
				
				IF @@ROWCOUNT = 0
					RAISERROR ('ERROR: No fue posible actualizar el registro en [INSPECCION_MATERIAL_ORDEN] ', 16, 1 ) --MENSAJE - Severity -State.

				-- ///////SE OBTIENE EL PORCENTAJE DE LA INSPECCION///////////////////////////////////////////////////////
				DECLARE @VP_PORCENTAJE_INSPECCION DECIMAL(13,2) = 0
				SELECT TOP 1 @VP_PORCENTAJE_INSPECCION = INSPECCION_PORCENTAJE
														FROM INSPECCION_MATERIAL
														WHERE K_ITEM = @PP_K_ITEM
														AND	K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL
																												
				-- ///////SE OBTIENE EL PORCENTAJE ACUMULADO PARA EL NUMERO DE PARTE EN LA ORDEN///////////////////////////////////////////////////////
				DECLARE @VP_PORCENTAJE_APROBATORIO DECIMAL(13,2) = 0
				DECLARE @VP_PORCENTAJE_ACUMULADO INT = 0
				DECLARE @VP_APROBACION_SISTEMA_ANTERIOR		INT = 0
				DECLARE @VP_APROBACION_MANUAL_ANTERIOR		INT = 0

				SELECT	@VP_PORCENTAJE_APROBATORIO		= PORCENTAJE_APROBATORIO,
						@VP_PORCENTAJE_ACUMULADO		= TOTAL_PORCENTAJE_ACUMULADO,
						@VP_APROBACION_SISTEMA_ANTERIOR = APROBACION_SISTEMA,
						@VP_APROBACION_MANUAL_ANTERIOR	= APROBACION_MANUAL
												FROM	[INSPECCION_MATERIAL_ORDEN_RESULTADO]
												WHERE	K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
												AND		ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
												AND		K_ITEM = @PP_K_ITEM
	
				IF @VP_PORCENTAJE_APROBATORIO IS NULL
					RAISERROR ('ERROR: No fue posible obtener datos en [INSPECCION_MATERIAL_ORDEN_RESULTADO] ', 16, 1 ) --MENSAJE - Severity -State.

				-- ///////SE SUMA AL PORCENTAJE ACUMULADO POR ESE NUMERO DE PARTE EL PORCENTAJE DE LA INSPECCION PREVIA VALIDACION EN EL CASO 2///////////////////////////////////////////////////////
				IF @PP_TIPO_INSPECCION_MATERIAL = '1'
					SET @VP_PORCENTAJE_ACUMULADO = @VP_PORCENTAJE_ACUMULADO + @VP_PORCENTAJE_INSPECCION
				
				IF @PP_TIPO_INSPECCION_MATERIAL = '2'
					BEGIN
						DECLARE @VALOR_MINIMO DECIMAL(13,2) = 0
						DECLARE @VALOR_MAXIMO DECIMAL(13,2) = 0

						SELECT  @VALOR_MINIMO = CONVERT(DECIMAL(13,2),ISNULL(OPCION_1, 00)),
								@VALOR_MAXIMO = CONVERT(DECIMAL(13,2),ISNULL(OPCION_2, 00))
						FROM INSPECCION_OPCION
						WHERE [K_INSPECCION_MATERIAL] = @PP_K_INSPECCION_MATERIAL

						IF ( @VP_OPCION_SELECCIONADA_ANTERIOR <> '' AND @VP_OPCION_SELECCIONADA_ANTERIOR >= @VALOR_MINIMO AND @VP_OPCION_SELECCIONADA_ANTERIOR <= @VALOR_MAXIMO )
							SET @VP_PORCENTAJE_ACUMULADO = @VP_PORCENTAJE_ACUMULADO - @VP_PORCENTAJE_INSPECCION

						DECLARE @VP_VALOR_INSPECCION_DECIMAL DECIMAL(13,2) = CONVERT(DECIMAL(13,2), @PP_RESULTADO_INSPECCION)

						IF @VP_VALOR_INSPECCION_DECIMAL >= @VALOR_MINIMO AND @VP_VALOR_INSPECCION_DECIMAL <= @VALOR_MAXIMO
							SET @VP_PORCENTAJE_ACUMULADO = @VP_PORCENTAJE_ACUMULADO + @VP_PORCENTAJE_INSPECCION

					END

				-- /////////////SE EVALUA EL PORCENTAJE ACUMULADO CON EL PORCENTAJE APROBATORIO PARA APROBAR POR SISTEMA//////////////////////////////
				DECLARE @VP_APROBACION_SISTEMA				INT = 0
				DECLARE @VP_APROBACION_SISTEMA_NUEVO		INT = 0
				DECLARE @VP_APROBACION_MANUAL				INT = 0
				DECLARE @VP_APROBACION_MANUAL_NUEVO			INT = @VP_APROBACION_MANUAL_ANTERIOR
				DECLARE @VP_TIPO_INSPECCION_MATERIAL_LOG	INT = 3 --MODIFICAR INSPECCION

				IF @VP_PORCENTAJE_ACUMULADO >= @VP_PORCENTAJE_APROBATORIO
					BEGIN
						SET @VP_APROBACION_SISTEMA = 1
						SET @VP_APROBACION_SISTEMA_NUEVO = @VP_APROBACION_SISTEMA
						SET @VP_APROBACION_MANUAL_NUEVO = 0
					END

				-- ///////////////////SE OBTIENE EL USUARIO QUE AUTORIZO EL CAMBIO////////////// 
				DECLARE @VP_K_USUARIO_AUTORIZACION INT = 0
				SELECT  @VP_K_USUARIO_AUTORIZACION = K_USUARIO
				FROM	BD_GENERAL.DBO.[GRUPO_APROBADOR] 
				INNER	JOIN [BD_GENERAL].dbo.USUARIO_PEARL ON [GRUPO_APROBADOR].K_USUARIO = USUARIO_PEARL.K_USUARIO_PEARL
				WHERE	D_USUARIO_PEARL = @PP_D_USUARIO_AUTORIZACION	
				AND		D_GRUPO_APROBADOR = 'QA MADIFICAR INSPECCION MATERIAL'
				AND		K_ESTATUS_GRUPO_APROBADOR = 1 -- ACTIVO
				AND		K_TIPO_GRUPO_APROBADOR = 150 --  MODIFICAR INSPECCION MATERIAL QA

				IF @VP_K_USUARIO_AUTORIZACION IS NULL
					RAISERROR ('ERROR: No fue posible obtener usuario aprobador en [GRUPO_APROBADOR] ', 16, 1 ) --MENSAJE - Severity -State. 

				-- ///////////////////INGRESO EL LOG DEL CAMBIO REALIZADO EN LA INSPECCION DEL MATERIAL////////////// 
				EXECUTE [dbo].[PG_IN_INSPECCION_MATERIAL_LOG]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																@VP_TIPO_INSPECCION_MATERIAL_LOG, @PP_K_ORDEN_COMPRA,
																@PP_ORDEN_COMPRA_PEDIDO, @PP_K_ITEM, @PP_K_INSPECCION_MATERIAL, 
																@VP_OPCION_SELECCIONADA_ANTERIOR, @PP_RESULTADO_INSPECCION,
																@VP_APROBACION_SISTEMA_ANTERIOR, @VP_APROBACION_SISTEMA_NUEVO, 
																@VP_APROBACION_MANUAL_ANTERIOR, @VP_APROBACION_MANUAL_NUEVO, 
																@VP_K_USUARIO_AUTORIZACION, @PP_COMENTARIO
				
				-- ///////SI ACTUALIZA LA INSPECCION CON ESA ORDEN Y NUEMERO DE PARTE EN [INSPECCION_MATERIAL_ORDEN]//////////////////
				UPDATE	[INSPECCION_MATERIAL_ORDEN_RESULTADO]
					SET	[TOTAL_PORCENTAJE_ACUMULADO]				= @VP_PORCENTAJE_ACUMULADO,
						[APROBACION_SISTEMA]						= @VP_APROBACION_SISTEMA,
						[APROBACION_MANUAL]							= @VP_APROBACION_MANUAL,
						[COMENTARIO]								= @PP_COMENTARIO,
						[K_USUARIO_ALTA]							= @PP_K_USUARIO_ACCION,
						[F_INSPECCION_MATERIAL_ORDEN_RESULTADO]		= GETDATE()	
				WHERE K_ITEM = @PP_K_ITEM
				AND K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
				AND ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO

				IF @@ROWCOUNT = 0
					RAISERROR ('ERROR: No fue posible actualizar el registro en [INSPECCION_MATERIAL_ORDEN_RESULTADO] ', 16, 1 ) --MENSAJE - Severity -State.
				
				-- ///////////SI LA INSPECCION HA TERMINADO SE INGRESA EL REGISTRO PARA LA DISPOSICION///////////////////////////////////////////////////
				IF ( @VP_APROBACION_SISTEMA_ANTERIOR <> @VP_APROBACION_SISTEMA_NUEVO OR @VP_APROBACION_MANUAL_ANTERIOR <> @VP_APROBACION_MANUAL_NUEVO )
					BEGIN
						-- //////////////////////SE OBTIENE LA LOCACION MHI POR DEFAULT///////////////////////
						DECLARE @VP_LOCACION_DESTINO VARCHAR(5) = ''
							SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
								FROM	imlocfil_sql 
							WHERE A4GLIdentity = 4
													
						-- //////////////////////SE OBTIENE LA LOCACION MQU SI EL RESULTADO DE LA INSPECCION ES RECHAZADO///////////////////////
						IF @VP_APROBACION_SISTEMA_NUEVO = 0 AND @VP_APROBACION_MANUAL_NUEVO = 0
							SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
							FROM	imlocfil_sql 
							WHERE A4GLIdentity = 6
							
						IF @VP_LOCACION_DESTINO IS NULL
							RAISERROR ('ERROR: No fue posible obtener la locacion en [imlocfil_sql] ', 16, 1 ) --MENSAJE - Severity -State.
							
						IF @VP_LOCACION_DESTINO NOT IN ('MHI','MQU')
							RAISERROR ('ERROR: Locacion no valida.', 16, 1 ) --MENSAJE - Severity -State.

						-- //////////////////////SE VALIDA QUE EXISTA EL MATERIAL EN LA TABLA DE DISPOCISION///////////////////////
						DECLARE @VP_N_MATERIAL_ESPERA_DISPOSICION INT = 0
						SELECT @VP_N_MATERIAL_ESPERA_DISPOSICION =  K_INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION
						FROM [INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]
						WHERE K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
						AND ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
						AND ORDEN_COMPRA_PEDIDO_ENTREGA = 1 -- PENDIENTE CARGAR DATO CORRECTO
						AND K_ITEM = @PP_K_ITEM

						IF ( @VP_N_MATERIAL_ESPERA_DISPOSICION IS NULL OR @VP_N_MATERIAL_ESPERA_DISPOSICION = 0 )
							RAISERROR ('ERROR: No se encontro el material en [INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION] ', 16, 1 ) --MENSAJE - Severity -State.
						
						-- //////////////////////SE VALIDA EL ESTATUS DEL MATERIAL EN LA TABLA DE DISPOCISION///////////////////////
						DECLARE @VP_K_ESTATUS_MATERIAL_DISPOSICION INT = 0
						DECLARE @VP_LOCACION_MATERIAL_DISPOSICION VARCHAR(5) = ''
						SELECT	@VP_K_ESTATUS_MATERIAL_DISPOSICION =  K_ESTATUS_MATERIAL_DISPOSICION,
								@VP_LOCACION_MATERIAL_DISPOSICION = LOCACION_DESTINO
						FROM [INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]
						WHERE K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
						AND ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
						AND ORDEN_COMPRA_PEDIDO_ENTREGA = 1 -- PENDIENTE CARGAR DATO CORRECTO
						AND K_ITEM = @PP_K_ITEM

						IF @VP_K_ESTATUS_MATERIAL_DISPOSICION <> 0 -- EN ESPERA DE DISPOCISION
							BEGIN
								DECLARE @VP_ERROR VARCHAR(255) = 'ERROR: El material se proceso o esta siendo procesado por '+ @VP_LOCACION_MATERIAL_DISPOSICION
								RAISERROR (@VP_ERROR, 16, 1 ) --MENSAJE - Severity -State.
							END

						-- //////////////////////SE ACTUALIZA LA LOCACION A DONDE SE LE DARA DISPOCISION AL MATERIAL///////////////////////
						UPDATE [INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]
							SET LOCACION_DESTINO = @VP_LOCACION_DESTINO
						WHERE K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
						AND ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
						AND ORDEN_COMPRA_PEDIDO_ENTREGA = 1 -- PENDIENTE CARGAR DATO CORRECTO
						AND K_ITEM = @PP_K_ITEM

						-- //////////////////////SE NOTIFICA A LOS RESPONSABLES DE LA LOCACION A DONDE VA EL MATERIAL///////////////////////
						EXECUTE [dbo].[PG_CONFIGURAR_CORREO_MATERIAL_INSPECCIONADO_DISPOSICION] @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																								@PP_K_ORDEN_COMPRA, @PP_ORDEN_COMPRA_PEDIDO, 1,
																								@PP_K_ITEM, @VP_LOCACION_DESTINO

					END
				-- //////////////////////////////////////////////////////////////

			COMMIT TRANSACTION 
			END TRY
	
			BEGIN CATCH
				/* Ocurrió un error, deshacemos los cambios*/ 
				ROLLBACK TRANSACTION
				DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
				SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
				SET @VP_MENSAJE = 'ERROR: //TRANSAC. PG_UP_INSPECCION_MATERIAL_ORDEN // ' + @VP_ERROR_TRANS
			END CATCH
				
		END

	-- // SECCION#3 ////////////////////////////////////////////////////////// MENSAJE DE SALIDA
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Crear] la [INSPECCION_MATERIAL_ORDEN]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#INSP.'+CONVERT(VARCHAR(10),@VP_K_INSPECCION_MATERIAL_ORDEN)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'
	
		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @VP_K_INSPECCION_MATERIAL_ORDEN AS CLAVE

	-- //////////////////////////////////////////////////////////////

GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN_RESULTADO_APROBACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN_RESULTADO_APROBACION]
GO


CREATE PROCEDURE [dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN_RESULTADO_APROBACION]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA			INT,
	@PP_ORDEN_COMPRA_PEDIDO		VARCHAR(50),
	@PP_K_ITEM					INT,
	@PP_APROBACION				INT,
	@PP_D_USUARIO_AUTORIZACION	VARCHAR(150),
	@PP_COMENTARIO				VARCHAR(255)
AS

	DECLARE @VP_MENSAJE		VARCHAR(300) = ''

	-- // SECCION#1 /////////////////////////////////////////////////////////// VALIDACIONES + REGLAS DE NEGOCIO 
	
	IF @VP_MENSAJE=''
		--EXECUTE [dbo].[PG_RN_INSPECCION_MATERIAL_DELETE]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
		--									@PP_K_INSPECCION_MATERIAL, 
		--									@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	-- // SECCION#2 ////////////////////////////////////////////////////////// ACCION A REALIZAR

	IF @VP_MENSAJE=''
		BEGIN
			BEGIN TRANSACTION 
			BEGIN TRY
				DECLARE @VP_TIPO_INSPECCION_MATERIAL_LOG	INT = 1 -- APROBAR INSPECCION
				DECLARE @VP_APROBACION_SISTEMA_ANTERIOR		INT = 0
				DECLARE @VP_APROBACION_SISTEMA_NUEVO		INT = 0
				DECLARE @VP_APROBACION_MANUAL_ANTERIOR		INT = 0
				DECLARE @VP_APROBACION_MANUAL_NUEVO			INT = 0
				-- ===========================
				IF @PP_APROBACION = 0
					SET @VP_TIPO_INSPECCION_MATERIAL_LOG = 2 -- RECHAZAR INSPECCION
				-- ===========================

					SELECT	@VP_APROBACION_SISTEMA_ANTERIOR = APROBACION_SISTEMA,
							@VP_APROBACION_SISTEMA_NUEVO    = APROBACION_SISTEMA,
							@VP_APROBACION_MANUAL_ANTERIOR	= APROBACION_MANUAL,
							@VP_APROBACION_MANUAL_NUEVO		= APROBACION_MANUAL
															FROM	[INSPECCION_MATERIAL_ORDEN_RESULTADO]
															WHERE	K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
															AND		ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
															AND		K_ITEM = @PP_K_ITEM
															
				IF @PP_APROBACION = 0 AND @VP_APROBACION_SISTEMA_ANTERIOR = 1
					SET @VP_APROBACION_SISTEMA_NUEVO = 0
				-- ===========================

				-- ///////////////////SE VALIDA QUE EL ESTATUS ANTERIOR NO SEA IGUAL AL NUEVO////////////// 
				IF @PP_APROBACION = 0 AND @VP_APROBACION_SISTEMA_ANTERIOR = 0 AND @VP_APROBACION_MANUAL_ANTERIOR = 0
					RAISERROR ('ERROR: El material ya se encuentra Rechazado en [INSPECCION_MATERIAL_ORDEN_RESULTADO] ', 16, 1 ) --MENSAJE - Severity -State. 

				IF ( @PP_APROBACION = 1 AND @VP_APROBACION_SISTEMA_ANTERIOR = 1 OR @VP_APROBACION_MANUAL_ANTERIOR = 1 )
					RAISERROR ('ERROR: El material ya se encuentra Aceptado en [INSPECCION_MATERIAL_ORDEN_RESULTADO] ', 16, 1 ) --MENSAJE - Severity -State. 

				SET @VP_APROBACION_MANUAL_NUEVO = @PP_APROBACION
				
				-- ///////////////////SE OBTIENE EL USUARIO QUE AUTORIZO EL CAMBIO////////////// 
				DECLARE @VP_K_USUARIO_AUTORIZACION INT = 0
				SELECT  @VP_K_USUARIO_AUTORIZACION = K_USUARIO
				FROM	BD_GENERAL.DBO.[GRUPO_APROBADOR] 
				INNER	JOIN [BD_GENERAL].dbo.USUARIO_PEARL ON [GRUPO_APROBADOR].K_USUARIO = USUARIO_PEARL.K_USUARIO_PEARL
				WHERE	D_USUARIO_PEARL = @PP_D_USUARIO_AUTORIZACION	
				AND		D_GRUPO_APROBADOR = 'QA MADIFICAR INSPECCION MATERIAL'
				AND		K_ESTATUS_GRUPO_APROBADOR = 1 -- ACTIVO
				AND		K_TIPO_GRUPO_APROBADOR = 150 --  MODIFICAR INSPECCION MATERIAL QA

				IF @VP_K_USUARIO_AUTORIZACION IS NULL
					RAISERROR ('ERROR: No fue posible obtener usuario aprobador en [GRUPO_APROBADOR] ', 16, 1 ) --MENSAJE - Severity -State. 

				-- ///////////////////INGRESO EL LOG DEL CAMBIO REALIZADO EN LA INSPECCION DEL MATERIAL////////////// 
				EXECUTE [dbo].[PG_IN_INSPECCION_MATERIAL_LOG]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																@VP_TIPO_INSPECCION_MATERIAL_LOG, @PP_K_ORDEN_COMPRA,
																@PP_ORDEN_COMPRA_PEDIDO, @PP_K_ITEM, 0, '', '',
																@VP_APROBACION_SISTEMA_ANTERIOR, @VP_APROBACION_SISTEMA_NUEVO, 
																@VP_APROBACION_MANUAL_ANTERIOR, @VP_APROBACION_MANUAL_NUEVO, 
																@VP_K_USUARIO_AUTORIZACION, @PP_COMENTARIO

				-- ///////////////////SE ACTUALIZA EL DATO//////////////////////////////////////////////////
				UPDATE [INSPECCION_MATERIAL_ORDEN_RESULTADO]
					SET [APROBACION_SISTEMA]						= ( CASE WHEN @PP_APROBACION = 0 AND @VP_APROBACION_SISTEMA_ANTERIOR = 1THEN @PP_APROBACION
																			ELSE [APROBACION_SISTEMA] END ),
						[APROBACION_MANUAL]							= @PP_APROBACION,
						[COMENTARIO]								= @PP_COMENTARIO,
						[K_USUARIO_ALTA]							= @PP_K_USUARIO_ACCION,
						[F_INSPECCION_MATERIAL_ORDEN_RESULTADO]		= GETDATE()	
				WHERE K_ITEM = @PP_K_ITEM
				AND K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
				AND ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO

				IF @@ROWCOUNT = 0
					RAISERROR ('ERROR: No se Actualizo el estatus de la inspección', 16, 1 ) --MENSAJE - Severity -State.
				
				-- ///////////SI LA INSPECCION HA TERMINADO SE INGRESA EL REGISTRO PARA LA DISPOSICION///////////////////////////////////////////////////
				IF ( @VP_APROBACION_SISTEMA_ANTERIOR <> @VP_APROBACION_SISTEMA_NUEVO OR @VP_APROBACION_MANUAL_ANTERIOR <> @VP_APROBACION_MANUAL_NUEVO )
					BEGIN
						-- //////////////////////SE OBTIENE LA LOCACION MHI POR DEFAULT///////////////////////
						DECLARE @VP_LOCACION_DESTINO VARCHAR(5) = ''
							SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
								FROM	imlocfil_sql 
							WHERE A4GLIdentity = 4
													
						-- //////////////////////SE OBTIENE LA LOCACION MQU SI EL RESULTADO DE LA INSPECCION ES RECHAZADO///////////////////////
						IF @VP_APROBACION_SISTEMA_NUEVO = 0 AND @VP_APROBACION_MANUAL_NUEVO = 0
							SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
							FROM	imlocfil_sql 
							WHERE A4GLIdentity = 6
							
						IF @VP_LOCACION_DESTINO IS NULL
							RAISERROR ('ERROR: No fue posible obtener la locacion en [imlocfil_sql] ', 16, 1 ) --MENSAJE - Severity -State.
							
						IF @VP_LOCACION_DESTINO NOT IN ('MHI','MQU')
							RAISERROR ('ERROR: Locacion no valida.', 16, 1 ) --MENSAJE - Severity -State.

						-- //////////////////////SE VALIDA QUE EXISTA EL MATERIAL EN LA TABLA DE DISPOCISION///////////////////////
						DECLARE @VP_N_MATERIAL_ESPERA_DISPOSICION INT = 0
						SELECT @VP_N_MATERIAL_ESPERA_DISPOSICION =  K_INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION
						FROM [INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]
						WHERE K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
						AND ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
						AND ORDEN_COMPRA_PEDIDO_ENTREGA = 1 -- PENDIENTE CARGAR DATO CORRECTO
						AND K_ITEM = @PP_K_ITEM

						IF ( @VP_N_MATERIAL_ESPERA_DISPOSICION IS NULL OR @VP_N_MATERIAL_ESPERA_DISPOSICION = 0 )
							RAISERROR ('ERROR: No se encontro el material en [INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION] ', 16, 1 ) --MENSAJE - Severity -State.
						
						-- //////////////////////SE VALIDA EL ESTATUS DEL MATERIAL EN LA TABLA DE DISPOCISION///////////////////////
						DECLARE @VP_K_ESTATUS_MATERIAL_DISPOSICION INT = 0
						DECLARE @VP_LOCACION_MATERIAL_DISPOSICION VARCHAR(5) = ''
						SELECT	@VP_K_ESTATUS_MATERIAL_DISPOSICION =  K_ESTATUS_MATERIAL_DISPOSICION,
								@VP_LOCACION_MATERIAL_DISPOSICION = LOCACION_DESTINO
						FROM [INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]
						WHERE K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
						AND ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
						AND ORDEN_COMPRA_PEDIDO_ENTREGA = 1 -- PENDIENTE CARGAR DATO CORRECTO
						AND K_ITEM = @PP_K_ITEM

						IF @VP_K_ESTATUS_MATERIAL_DISPOSICION <> 0 -- EN ESPERA DE DISPOCISION
							BEGIN
								DECLARE @VP_ERROR VARCHAR(255) = 'ERROR: El material se proceso o esta siendo procesado por '+ @VP_LOCACION_MATERIAL_DISPOSICION
								RAISERROR (@VP_ERROR, 16, 1 ) --MENSAJE - Severity -State.
							END

						-- //////////////////////SE ACTUALIZA LA LOCACION A DONDE SE LE DARA DISPOCISION AL MATERIAL///////////////////////
						UPDATE [INSPECCION_MATERIAL_ORDEN_ESPERA_DISPOSICION]
							SET LOCACION_DESTINO = @VP_LOCACION_DESTINO
						WHERE K_ORDEN_COMPRA = @PP_K_ORDEN_COMPRA
						AND ORDEN_COMPRA_PEDIDO = @PP_ORDEN_COMPRA_PEDIDO
						AND ORDEN_COMPRA_PEDIDO_ENTREGA = 1 -- PENDIENTE CARGAR DATO CORRECTO
						AND K_ITEM = @PP_K_ITEM

						-- //////////////////////SE NOTIFICA A LOS RESPONSABLES DE LA LOCACION A DONDE VA EL MATERIAL///////////////////////
						EXECUTE [dbo].[PG_CONFIGURAR_CORREO_MATERIAL_INSPECCIONADO_DISPOSICION] @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																								@PP_K_ORDEN_COMPRA, @PP_ORDEN_COMPRA_PEDIDO, 1,
																								@PP_K_ITEM, @VP_LOCACION_DESTINO

					END
				-- //////////////////////////////////////////////////////////////
			COMMIT TRANSACTION 
			END TRY
	
			BEGIN CATCH
				/* Ocurrió un error, deshacemos los cambios*/ 
				ROLLBACK TRANSACTION
				DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
				SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
				SET @VP_MENSAJE = 'ERROR: //TRANSAC. PG_UP_INSPECCION_MATERIAL_ORDEN_RESULTADO // ' + @VP_ERROR_TRANS
			END CATCH
		
		END

	-- // SECCION#3 ////////////////////////////////////////////////////////// MENSAJE DE SALIDA
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Actualizar] la [INSPECCION_MATERIAL]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#PART.'+ CONVERT(VARCHAR(10),@PP_K_ITEM) +']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'

		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_ITEM AS CLAVE

	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////	
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
