USE DATA_02PRUEBAS

SELECT * FROM IMITMIDX_SQL 

SELECT * FROM INSPECCION_MATERIAL

SELECT * FROM INSPECCION_OPCION_MULTIPLE

SELECT * FROM [INSPECCION_MATERIAL_RESULTADO]	

SELECT * FROM IMITMIDX_SQL WHERE item_no = '200435AWT3'

SELECT * FROM	COMPRAS.dbo.HEADER_PURCHASE_ORDER

SELECT * FROM	COMPRAS.dbo.VENDOR

SELECT * FROM COMPRAS.dbo.DETAILS_PURCHASE_ORDER

SELECT * FROM COMPRAS.dbo.ITEM	

SELECT * FROM COMPRAS.dbo.DETAILS_BLANKET_PURCHASE_ORDER

SELECT * FROM ARCUSFIL_SQL

SELECT	TOP (5000)  HEADER_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER AS ORDEN_COMPRA,
					VENDOR.D_VENDOR AS PROVEEDOR,
					K_PO_PRICE_LOG	AS K_PO_PRICE,
					S_CURRENCY,
					ITEM.K_CURRENCY,
					S_UNIT_OF_MEASURE,
					PART_NUMBER_ITEM_VENDOR,
					PART_NUMBER_ITEM_PEARL,
					D_ITEM,
					DETAILS_PURCHASE_ORDER.QUANTITY_ORDER AS QUANTITY,
					DETAILS_PURCHASE_ORDER.UNIT_PRICE AS PRICE_ITEM, --PRICE_ITEM,
					TOTAL_PRICE as TOTAL_ITEM,
					DETAILS_PURCHASE_ORDER.*
		FROM	COMPRAS.dbo.DETAILS_PURCHASE_ORDER
		INNER JOIN	COMPRAS.dbo.ITEM		ON	DETAILS_PURCHASE_ORDER.K_ITEM=ITEM.K_ITEM
		INNER JOIN	BD_GENERAL.DBO.UNIT_OF_MEASURE ON ITEM.K_UNIT_OF_ITEM=UNIT_OF_MEASURE.K_UNIT_OF_MEASURE
		INNER JOIN	BD_GENERAL.DBO.CURRENCY	ON	ITEM.K_CURRENCY=CURRENCY.K_CURRENCY
		INNER JOIN	COMPRAS.dbo.HEADER_PURCHASE_ORDER ON DETAILS_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER = COMPRAS.dbo.HEADER_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER
		INNER JOIN	COMPRAS.dbo.VENDOR ON HEADER_PURCHASE_ORDER.K_VENDOR = VENDOR.K_VENDOR
		WHERE		DETAILS_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER=1
		ORDER BY	K_DETAILS_PURCHASE_ORDER


