
USE DATA_02PRUEBAS

SELECT * FROM TIPO_INSPECCION_MATERIAL

SELECT * FROM INSPECCION_MATERIAL

SELECT * FROM INSPECCION_OPCION

SELECT * FROM [INSPECCION_MATERIAL_ORDEN]	

SELECT * FROM [INSPECCION_MATERIAL_ORDEN_RESULTADO]	

SELECT * FROM INSPECCION_MATERIAL_LOG	

SELECT * FROM TIPO_INSPECCION_MATERIAL_LOG

SELECT * FROM IMITMIDX_SQL WHERE PUR_OR_MFG = 'R'

SELECT * FROM COMPRAS_PRUEBAS.DBO.HEADER_PURCHASE_ORDER 

SELECT * FROM	COMPRAS_PRUEBAS.dbo.HEADER_BPO_PEDIDO  

SELECT * FROM COMPRAS_PRUEBAS.dbo.DETAILS_BPO_PEDIDO

SELECT * FROM	COMPRAS_PRUEBAS.dbo.VENDOR

SELECT * FROM IMITMIDX_SQL WHERE PUR_OR_MFG = 'R'

SELECT * FROM COMPRAS_PRUEBAS.dbo.ITEM WHERE K_CLASS_ITEM = 2 -- ROW MATERIAL

SELECT * FROM COMPRAS_PRUEBAS.dbo.DETAILS_BLANKET_PURCHASE_ORDER WHERE K_HEADER_PURCHASE_ORDER = 16

SELECT * FROM ARCUSFIL_SQL





-- ==================FORMA FO_AUTORIZAR_INSPECCION_MATERIAL============================
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 300, 150,	144	-- FEG		/ BT_EDIT	
EXECUTE [dbo].[PG_CI_SISTEMA_CONTROL_PERMISO] 0, 0, 301, 151,	144	-- FEG		/ BTN_GUARDAR_INSPECCION


