
USE DATA_02PRUEBAS

SELECT * FROM TIPO_INSPECCION_MATERIAL

SELECT * FROM INSPECCION_MATERIAL

SELECT * FROM INSPECCION_OPCION

SELECT * FROM [INSPECCION_MATERIAL_ORDEN]	

SELECT * FROM [INSPECCION_MATERIAL_ORDEN_RESULTADO]	

SELECT * FROM IMITMIDX_SQL WHERE PUR_OR_MFG = 'R'

SELECT * FROM	COMPRAS.dbo.HEADER_PURCHASE_ORDER

SELECT * FROM	COMPRAS.dbo.VENDOR

SELECT * FROM COMPRAS.dbo.DETAILS_PURCHASE_ORDER

SELECT * FROM IMITMIDX_SQL WHERE PUR_OR_MFG = 'R'

SELECT * FROM COMPRAS_Pruebas.dbo.ITEM WHERE K_CLASS_ITEM = 2 -- ROW MATERIAL

SELECT * FROM COMPRAS.dbo.DETAILS_BLANKET_PURCHASE_ORDER

SELECT * FROM ARCUSFIL_SQL



