-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[DATA_02]
-- // MODULO:			QA INSPECCION DE MATERIAL
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	04/SEP/2020
-- //////////////////////////////////////////////////////////////  

USE [DATA_02]
GO

-- //////////////////////////////////////////////////////////////




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA] 0,0, '00296-00001' , 1 , 82 , 201000002 , 8
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA_PEDIDO		VARCHAR(50),
	@PP_K_ENTREGA					INT,
	@PP_K_ITEM						INT,
	@PP_LOTE_PEARL					INT,
	@PP_K_INSPECCION_MATERIAL		INT
	
AS

	DECLARE @VP_MENSAJE						VARCHAR(300) = ''
	-- ///////////////////////////////////////////

	SELECT	
			[INSPECCION_MATERIAL_ORDEN_COMPRA].*,
			INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	-- =============================	
	FROM	[INSPECCION_MATERIAL_ORDEN_COMPRA]
	INNER JOIN INSPECCION_MATERIAL ON [INSPECCION_MATERIAL_ORDEN_COMPRA].K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
			AND [INSPECCION_MATERIAL_ORDEN_COMPRA].K_ITEM = INSPECCION_MATERIAL.K_ITEM
	INNER JOIN	TIPO_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	-- =============================
	WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
	AND		K_ENTREGA = @PP_K_ENTREGA
	AND		[INSPECCION_MATERIAL_ORDEN_COMPRA].K_ITEM = @PP_K_ITEM
	AND		LOTE_PEARL = @PP_LOTE_PEARL
	AND		[INSPECCION_MATERIAL_ORDEN_COMPRA].K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]
GO

/*
 EXEC	[dbo].[PG_LI_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO] 0,0, '2', 1, 69, 30001 
*/

CREATE PROCEDURE [dbo].[PG_LI_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA_PEDIDO		VARCHAR(100),
	@PP_K_ENTREGA					INT,
	@PP_K_ITEM						INT,
	@PP_LOTE_PEARL					INT
AS

	DECLARE @VP_MENSAJE						VARCHAR(300) = ''
	-- ///////////////////////////////////////////

	SELECT	[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].*,
		-- ===========================
		PART_NUMBER_ITEM_PEARL
	-- =============================	
	FROM	[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]
	INNER JOIN	COMPRAS.dbo.ITEM		ON	[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_ITEM=ITEM.K_ITEM
	-- =============================
	WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
	AND		K_ENTREGA = @PP_K_ENTREGA
	AND		[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_ITEM	= @PP_K_ITEM
	AND		LOTE_PEARL	= @PP_LOTE_PEARL

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO






-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////
-- USE DATA_02
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO] 0,0, '00296-00001', 1, 82, -1 -- 201000002 
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA_PEDIDO	VARCHAR(100),
	@PP_K_ENTREGA					INT,
	@PP_K_ITEM						INT,
	@PP_LOTE_PEARL					INT
AS

	DECLARE @VP_MENSAJE						VARCHAR(300) = ''
	-- ///////////////////////////////////////////

	SELECT	
			[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].*,
			-- ===========================
		( CASE WHEN ACEPTADO = 1
				THEN 'ACEPTADO'
			WHEN ACEPTADO = 0 
				THEN 'RECHAZADO'
			ELSE 'PENDIENTE' END ) AS ESTATUS,
		-- ===========================
		PART_NUMBER_ITEM_PEARL
	-- =============================	
	FROM	[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]
	INNER JOIN	COMPRAS.dbo.ITEM		ON	[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_ITEM=ITEM.K_ITEM
	-- =============================
		WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
	AND			K_ENTREGA = @PP_K_ENTREGA
	AND			[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_ITEM =  ( CASE WHEN @PP_K_ITEM = -1 THEN [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO].K_ITEM
																				ELSE @PP_K_ITEM END )
	AND			LOTE_PEARL = ( CASE WHEN @PP_LOTE_PEARL = -1 THEN LOTE_PEARL
									ELSE @PP_LOTE_PEARL END )
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////
-- USE DATA_02
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_AUTORIZAR_INSPECCION_MATERIAL_ORDEN_COMPRA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_AUTORIZAR_INSPECCION_MATERIAL_ORDEN_COMPRA]
GO

/*
 EXEC	[dbo].[PG_LI_AUTORIZAR_INSPECCION_MATERIAL_ORDEN_COMPRA] 0,0, '00296-00001', 1, 82, 201000001
*/

CREATE PROCEDURE [dbo].[PG_LI_AUTORIZAR_INSPECCION_MATERIAL_ORDEN_COMPRA]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA_PEDIDO		VARCHAR(100),
	@PP_K_ENTREGA					INT,
	@PP_K_ITEM						INT,
	@PP_LOTE_PEARL					INT
	
AS

	DECLARE @VP_MENSAJE						VARCHAR(300) = ''
	-- ///////////////////////////////////////////

	SELECT	
			[INSPECCION_MATERIAL_ORDEN_COMPRA].*,
			INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL,
			INSPECCION_MATERIAL.INSPECCION,
			PART_NUMBER_ITEM_PEARL AS NUMERO_PARTE,
			LTRIM(RTRIM(TRADEMARK_ITEM)) AS D_ITEM,
			-- =============================	
			( CASE WHEN K_TIPO_INSPECCION_MATERIAL = 2
						THEN OPCION_1
				ELSE 'N/A'	END )	AS VALOR_MINIMO,
			-- =============================	
			( CASE WHEN K_TIPO_INSPECCION_MATERIAL = 2
						THEN OPCION_2
				ELSE 'N/A'	END )	AS VALOR_MAXIMO,
			-- =============================
			( CASE WHEN ACEPTADO = 1
						THEN 'SI'
				ELSE 'NO'	END )	AS ESTATUS,
			-- =============================
			BD_GENERAL.dbo.USUARIO_PEARL.D_USUARIO_PEARL,
			CONVERT(DATE, [INSPECCION_MATERIAL_ORDEN_COMPRA].F_CAMBIO) AS F_INSPECCION_ORDEN_COMPRA
			-- =============================	
	FROM	[INSPECCION_MATERIAL_ORDEN_COMPRA]
	INNER JOIN COMPRAS.dbo.ITEM ON [INSPECCION_MATERIAL_ORDEN_COMPRA].K_ITEM = ITEM.K_ITEM
	INNER JOIN INSPECCION_MATERIAL ON [INSPECCION_MATERIAL_ORDEN_COMPRA].K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
			AND [INSPECCION_MATERIAL_ORDEN_COMPRA].K_ITEM = INSPECCION_MATERIAL.K_ITEM
	INNER JOIN	INSPECCION_OPCION ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
	INNER JOIN	BD_GENERAL.dbo.USUARIO_PEARL ON	[INSPECCION_MATERIAL_ORDEN_COMPRA].K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
	-- =============================
	WHERE	[INSPECCION_MATERIAL_ORDEN_COMPRA].K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
	AND		[INSPECCION_MATERIAL_ORDEN_COMPRA].K_ENTREGA = @PP_K_ENTREGA
	AND		[INSPECCION_MATERIAL_ORDEN_COMPRA].K_ITEM = @PP_K_ITEM 
	AND		[INSPECCION_MATERIAL_ORDEN_COMPRA].LOTE_PEARL = @PP_LOTE_PEARL
	ORDER BY K_TIPO_INSPECCION_MATERIAL ASC
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////
-- USE DATA_02
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA_A_MODIFICAR]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA_A_MODIFICAR]
GO
/*
 EXEC	[dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA_A_MODIFICAR] 0,0,1
*/


CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_ORDEN_COMPRA_A_MODIFICAR]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_INSPECCION_MATERIAL_ORDEN_COMPRA	INT
	-- ===========================
AS
	-- ///////////////////////////////////////////

	SELECT	TOP (5000)  
		INSPECCION_MATERIAL_ORDEN_COMPRA.K_INSPECCION_MATERIAL,
		INSPECCION_MATERIAL_ORDEN_COMPRA.K_ORDEN_COMPRA,
		INSPECCION_MATERIAL_ORDEN_COMPRA.K_ORDEN_COMPRA_PEDIDO,
		INSPECCION_MATERIAL_ORDEN_COMPRA.K_ENTREGA,
		INSPECCION_MATERIAL_ORDEN_COMPRA.K_ITEM,
		LTRIM(RTRIM(TRADEMARK_ITEM)) AS D_ITEM,
		INSPECCION_MATERIAL_ORDEN_COMPRA.LOTE_PEARL,
		VENDOR.D_VENDOR AS PROVEDOR,
		CUS_NO AS CLIENTE,
		-- ===========================
		PART_NUMBER_ITEM_VENDOR,
		PART_NUMBER_ITEM_PEARL,
		D_ITEM,
		-- ===========================	-- ===========================
		(SELECT SUM(RECIBO.QUANTITY_RECEIVED) 
		FROM COMPRAS.dbo.DETAILS_BPO_RECIBO  RECIBO
		WHERE RECIBO.K_ORDEN_COMPRA_PEDIDO = INSPECCION_MATERIAL_ORDEN_COMPRA.K_ORDEN_COMPRA_PEDIDO
		AND	RECIBO.K_ENTREGA = INSPECCION_MATERIAL_ORDEN_COMPRA.K_ENTREGA
		AND	RECIBO.K_ITEM = INSPECCION_MATERIAL_ORDEN_COMPRA.K_ITEM
		AND	RECIBO.LOTE_PEARL = INSPECCION_MATERIAL_ORDEN_COMPRA.LOTE_PEARL ) AS QUANTITY
	FROM	INSPECCION_MATERIAL_ORDEN_COMPRA
	INNER JOIN	COMPRAS.dbo.ITEM		ON	INSPECCION_MATERIAL_ORDEN_COMPRA.K_ITEM=ITEM.K_ITEM
		
	INNER JOIN	COMPRAS.dbo.HEADER_BPO_PEDIDO ON INSPECCION_MATERIAL_ORDEN_COMPRA.K_ORDEN_COMPRA_PEDIDO = COMPRAS.dbo.HEADER_BPO_PEDIDO.K_ORDEN_COMPRA_PEDIDO
	INNER JOIN	COMPRAS.dbo.VENDOR ON HEADER_BPO_PEDIDO.K_VENDOR = VENDOR.K_VENDOR

	INNER JOIN	COMPRAS.dbo.DETAILS_BLANKET_PURCHASE_ORDER  ON	INSPECCION_MATERIAL_ORDEN_COMPRA.K_ORDEN_COMPRA = DETAILS_BLANKET_PURCHASE_ORDER.K_HEADER_PURCHASE_ORDER
		
	INNER JOIN	ARCUSFIL_SQL ON DETAILS_BLANKET_PURCHASE_ORDER.K_CUSTOMER = ARCUSFIL_SQL.A4GLIdentity

	WHERE	INSPECCION_MATERIAL_ORDEN_COMPRA.K_INSPECCION_MATERIAL_ORDEN_COMPRA = @PP_K_INSPECCION_MATERIAL_ORDEN_COMPRA
	ORDER BY	K_INSPECCION_MATERIAL_ORDEN_COMPRA

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> INSERT
-- //////////////////////////////////////////////////////////////
-- USE DATA_02
--PG_IN_UP_INSPECCION_MATERIAL_ORDEN_COMPRA
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_IN_UP_INSPECCION_MATERIAL_ORDEN_COMPRA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_IN_UP_INSPECCION_MATERIAL_ORDEN_COMPRA]
GO
/*
 EXECUTE [PG_IN_UP_INSPECCION_MATERIAL_ORDEN_COMPRA] 0,144,    296 , '00296-00001' , 1 , 82 , 201000002 , 9 , 2 , '1.1' , 1 , 'N/A' , 4 
*/
CREATE PROCEDURE [dbo].[PG_IN_UP_INSPECCION_MATERIAL_ORDEN_COMPRA]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================	
	@PP_K_ORDEN_COMPRA					INT,
	@PP_K_ORDEN_COMPRA_PEDIDO			VARCHAR(50),
	@PP_K_ENTREGA						INT,
	@PP_K_ITEM							INT,
	@PP_LOTE_PEARL						INT,
	@PP_K_INSPECCION_MATERIAL			INT,
	@PP_K_TIPO_INSPECCION_MATERIAL		INT,
	-- ===========================	
	@PP_RESULTADO_INSPECCION			VARCHAR(255),
	@PP_ACEPTADO						INT,
	@PP_COMENTARIO						VARCHAR(255),
	-- ============================	
	@PP_N_INSPECCION_CONFIGURADA		INT
AS			
	
	DECLARE @VP_MENSAJE		VARCHAR(300) = ''
	DECLARE @VP_K_INSPECCION_MATERIAL_ORDEN_COMPRA	INT = 0

	-- // SECCION#1 /////////////////////////////////////////////////////////// VALIDACIONES + REGLAS DE NEGOCIO 	
	--IF @VP_MENSAJE=''	
		--EXECUTE [dbo].[PG_RN_INSPECCION_MATERIAL_ORDEN_COMPRA_INSERT]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
		--													@PP_INSPECCION_PORCENTAJE, @PP_OPCION_1_PORCENTAJE,
		--													@PP_OPCION_2_PORCENTAJE, @PP_OPCION_3_PORCENTAJE,
		--													@PP_OPCION_4_PORCENTAJE, @PP_OPCION_5_PORCENTAJE,
		--													@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	-- // SECCION#2 ////////////////////////////////////////////////////////// ACCION A REALIZAR
	
	IF @VP_MENSAJE=''
		BEGIN
			BEGIN TRANSACTION 
			BEGIN TRY							
				
				-- ///////SI ES UNA INSPECCION TIPO 2 SE OBTIENE LOS PARAMETROS DE EVALUACION//////////////////
				IF @PP_K_TIPO_INSPECCION_MATERIAL = '2' --EVALUACION
					BEGIN
						DECLARE @VALOR_MINIMO DECIMAL(13,2) = 0
						DECLARE @VALOR_MAXIMO DECIMAL(13,2) = 0

						SELECT  @VALOR_MINIMO = CONVERT(DECIMAL(13,2),ISNULL(OPCION_1, 0)),
								@VALOR_MAXIMO = CONVERT(DECIMAL(13,2),ISNULL(OPCION_2, 0))
						FROM INSPECCION_OPCION
						WHERE [K_INSPECCION_MATERIAL] = @PP_K_INSPECCION_MATERIAL


						DECLARE @VP_VALOR_INSPECCION_DECIMAL DECIMAL(13,2) = CONVERT(DECIMAL(13,2), @PP_RESULTADO_INSPECCION)

						IF ( @VP_VALOR_INSPECCION_DECIMAL < @VALOR_MINIMO OR @VP_VALOR_INSPECCION_DECIMAL > @VALOR_MAXIMO )
							SET @PP_ACEPTADO = 0
					END

				-- ///////SE VERIFICA SI YA EXISTE LA ORDEN_COMPRA CON ESE NUMERO DE PARTE Y ESA INSPECCION EN INSPECCION_MATERIAL_ORDEN_COMPRA//////////////////
				DECLARE @VP_N_INSPECCION_MATERIAL_ORDEN_COMPRA  INT = 0

				SELECT	@VP_N_INSPECCION_MATERIAL_ORDEN_COMPRA = COUNT([K_INSPECCION_MATERIAL_ORDEN_COMPRA])
				FROM	INSPECCION_MATERIAL_ORDEN_COMPRA
				WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
				AND		K_ENTREGA = @PP_K_ENTREGA
				AND		K_ITEM = @PP_K_ITEM
				AND		LOTE_PEARL = @PP_LOTE_PEARL
				AND		K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL
				
				IF 	@VP_N_INSPECCION_MATERIAL_ORDEN_COMPRA IS NULL
					SET @VP_N_INSPECCION_MATERIAL_ORDEN_COMPRA = 0

				-- ///////SI NO EXISTE UNA INSPECCION CON ESA ORDEN_COMPRA, NUMERO DE PARTE E INSPECCION SE INGRESA EL REGISTRO SI NO SE ACTUALIZA//////////////////
				IF @VP_N_INSPECCION_MATERIAL_ORDEN_COMPRA = 0
					BEGIN
						EXECUTE BD_GENERAL.dbo.[PG_SK_CATALOGO_K_MAX_GET]	@PP_K_SISTEMA_EXE,
																			'DATA_02', 'INSPECCION_MATERIAL_ORDEN_COMPRA', 'K_INSPECCION_MATERIAL_ORDEN_COMPRA',
																			@OU_K_TABLA_DISPONIBLE = @VP_K_INSPECCION_MATERIAL_ORDEN_COMPRA	OUTPUT

						-- ///////SE INSERTA LA INSPECCION DEL MATERIAL///////////////////////////////////////////////////////
						INSERT INTO [INSPECCION_MATERIAL_ORDEN_COMPRA]
							(	[K_INSPECCION_MATERIAL_ORDEN_COMPRA],
								-- ===========================
								[K_ORDEN_COMPRA],
								[K_ORDEN_COMPRA_PEDIDO],
								[K_ENTREGA],
								[K_ITEM],
								[LOTE_PEARL],
								[K_INSPECCION_MATERIAL],
								-- ===========================
								[OPCION_SELECCIONADA],
								[ACEPTADO],
								[COMENTARIO],
								[F_ORDEN_COMPRA_INSPECCION_MATERIAL],
								-- ===========================
								[K_USUARIO_ALTA], [F_ALTA], [K_USUARIO_CAMBIO], [F_CAMBIO],
								[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]  )
						VALUES	
							(	@VP_K_INSPECCION_MATERIAL_ORDEN_COMPRA,
								-- ===========================	
								@PP_K_ORDEN_COMPRA,			
								@PP_K_ORDEN_COMPRA_PEDIDO,	
								@PP_K_ENTREGA,	
								@PP_K_ITEM,				
								@PP_LOTE_PEARL,
								@PP_K_INSPECCION_MATERIAL,
								-- ===========================	
								@PP_RESULTADO_INSPECCION,
								@PP_ACEPTADO,		
								@PP_COMENTARIO,					
								GETDATE(),
								-- ===========================
								@PP_K_USUARIO_ACCION, GETDATE(), @PP_K_USUARIO_ACCION, GETDATE(),
								0, NULL, NULL )

						IF @@ROWCOUNT = 0
							RAISERROR ('ERROR: No fue posible ingresar el registro en [INSPECCION_MATERIAL_ORDEN_COMPRA] ', 16, 1 ) --MENSAJE - Severity -State.
							--=====================================================
					END
				ELSE
					BEGIN
						-- ///////SI ACTUALIZA LA INSPECCION CON ESA ORDEN_COMPRA, NUMERO DE PARTE E INSPECCION EN [INSPECCION_MATERIAL_ORDEN_COMPRA]//////////////////
						UPDATE [INSPECCION_MATERIAL_ORDEN_COMPRA]
							SET	[OPCION_SELECCIONADA]					= @PP_RESULTADO_INSPECCION,
								[COMENTARIO]							= @PP_COMENTARIO,
								[ACEPTADO]								= @PP_ACEPTADO,
								[F_ORDEN_COMPRA_INSPECCION_MATERIAL]	= GETDATE(),
								F_CAMBIO								= GETDATE(),
								K_USUARIO_CAMBIO						= @PP_K_USUARIO_ACCION
						WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
						AND		K_ENTREGA = @PP_K_ENTREGA
						AND		K_ITEM = @PP_K_ITEM
						AND		LOTE_PEARL = @PP_LOTE_PEARL
						AND		K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL
						
						IF @@ROWCOUNT = 0
							RAISERROR ('ERROR: No fue posible actualizar la inspección en [INSPECCION_MATERIAL_ORDEN_COMPRA] ', 16, 1 ) --MENSAJE - Severity -State.

					END

				-- ///////SE OBTIENE EL NUMERO DE INSPECCIONES REALIZADAS//////////////////
				DECLARE @VP_N_INSPECCION_REALIZADA		INT = 0
				SELECT	@VP_N_INSPECCION_REALIZADA = COUNT([K_INSPECCION_MATERIAL_ORDEN_COMPRA])
				FROM	INSPECCION_MATERIAL_ORDEN_COMPRA
				WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
				AND		K_ENTREGA = @PP_K_ENTREGA
				AND		K_ITEM = @PP_K_ITEM
				AND		LOTE_PEARL = @PP_LOTE_PEARL

				IF @VP_N_INSPECCION_REALIZADA IS NULL
					SET @VP_N_INSPECCION_REALIZADA = 0

				-- /////// SI EL NUMERO DE INSPECCIONES CONFIGURADAS SON IGUALES A LAS REALIZADAS SE CIERRA LA INSPECCION DEL MATERIAL//////////////////
				IF @PP_N_INSPECCION_CONFIGURADA = @VP_N_INSPECCION_REALIZADA
					BEGIN
						-- ///////SE VERIFICA SI HAY UNA INSPECCION RECHAZADA PARA RECHAZAR LA INSPECCION COMPLETA///////////////////////////////////////////////////////
						DECLARE @VP_N_INSPECCION_RECHAZADA	INT = 0
						SELECT	@VP_N_INSPECCION_RECHAZADA	=	COUNT([K_INSPECCION_MATERIAL_ORDEN_COMPRA])
						FROM	INSPECCION_MATERIAL_ORDEN_COMPRA
						WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
						AND		K_ENTREGA = @PP_K_ENTREGA
						AND		K_ITEM = @PP_K_ITEM
						AND		LOTE_PEARL = @PP_LOTE_PEARL
						AND		ACEPTADO = 0

						IF @VP_N_INSPECCION_RECHAZADA IS NULL
							RAISERROR ('ERROR: No fue posible obtener el numero de inspecciones en [INSPECCION_MATERIAL_ORDEN_COMPRA] ', 16, 1 ) --MENSAJE - Severity -State.
						-- =================================

						DECLARE @VP_RESULTADO INT = 1
						IF @VP_N_INSPECCION_RECHAZADA > 0
							SET @VP_RESULTADO = 0

						-- ///////SE OBTIENE EL CONSECUTIVO DE LA PK DE LA TABLA PARA EL INSERT///////////////////////////////////////////////////////
						DECLARE @VP_K_INSPECCION_MATERIAL_ORDEN_RESULTADO	INT = 0
						EXECUTE BD_GENERAL.dbo.[PG_SK_CATALOGO_K_MAX_GET] @PP_K_SISTEMA_EXE,
																		'DATA_02', 'INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO', 'K_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO',
																		@OU_K_TABLA_DISPONIBLE = @VP_K_INSPECCION_MATERIAL_ORDEN_RESULTADO	OUTPUT

						-- ///////SE INSERTA LA INSPECCION DEL MATERIAL///////////////////////////////////////////////////////
						INSERT INTO [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]
							(	[K_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO],
								-- =================================
								[K_ORDEN_COMPRA],								
								[K_ORDEN_COMPRA_PEDIDO],							
								[K_ENTREGA],										
								[K_ITEM],										
								[LOTE_PEARL],									
								[ACEPTADO],										
								-- =================================	
								[K_USUARIO_ALTA],								
								[F_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]
								)
								-- ===========================
						VALUES	
							(	@VP_K_INSPECCION_MATERIAL_ORDEN_RESULTADO,
								-- ===========================	
								@PP_K_ORDEN_COMPRA,		
								@PP_K_ORDEN_COMPRA_PEDIDO,	
								@PP_K_ENTREGA,				
								@PP_K_ITEM,						
								@PP_LOTE_PEARL,
								@VP_RESULTADO,																																				
								@PP_K_USUARIO_ACCION,
								GETDATE()	)

						IF @@ROWCOUNT = 0
							RAISERROR ('ERROR: No fue posible ingresar la inspección en [INSPECCION_MATERIAL_ORDEN_RESULTADO] ', 16, 1 ) --MENSAJE - Severity -State.
							--=====================================================

						-- ///////////////////INGRESO EL LOG DEL RESULTADO DE LA INSPECCION DEL MATERIAL//////////////
						DECLARE @VP_TIPO_INSPECCION_MATERIAL_LOG	INT = 1 -- ACEPTADO POR SISTEMA 
						
						IF @VP_RESULTADO = 0
							SET @VP_TIPO_INSPECCION_MATERIAL_LOG = 2 -- RECHAZADO POR SISTEMA
						 
						EXECUTE [dbo].[PG_IN_INSPECCION_MATERIAL_ORDEN_COMPRA_LOG]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																					@VP_TIPO_INSPECCION_MATERIAL_LOG, @PP_K_ORDEN_COMPRA,
																					@PP_K_ORDEN_COMPRA_PEDIDO, @PP_K_ENTREGA, @PP_K_ITEM, @PP_LOTE_PEARL,
																					0, '', '', @PP_K_USUARIO_ACCION, @PP_COMENTARIO

						-- //////////////////////SE OBTIENE LA LOCACION MHI POR DEFAULT///////////////////////
						DECLARE @VP_K_LOCACION_DESTINO INT = 4 --MHI
						DECLARE @VP_LOCACION_DESTINO VARCHAR(5) = ''

						SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
							FROM	imlocfil_sql 
						WHERE A4GLIdentity = @VP_K_LOCACION_DESTINO 
													
						-- //////////////////////SE OBTIENE LA LOCACION MQU SI EL RESULTADO DE LA INSPECCION ES RECHAZADO///////////////////////
						IF @VP_RESULTADO = 0
							BEGIN
								SET @VP_K_LOCACION_DESTINO = 6 -- MQU
								SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
								FROM	imlocfil_sql 
								WHERE A4GLIdentity = @VP_K_LOCACION_DESTINO
							END
							
						IF @VP_LOCACION_DESTINO IS NULL
							RAISERROR ('ERROR: No fue posible obtener la locacion en [imlocfil_sql] ', 16, 1 ) --MENSAJE - Severity -State.
							
						IF @VP_LOCACION_DESTINO NOT IN ('MHI','MQU')
							RAISERROR ('ERROR: Locacion no valida.', 16, 1 ) --MENSAJE - Severity -State.

						-- //////////////////////SE TRANSFIERE EL MATERIAL A LA LOCACION QUE CORRESPONDA MHI/MQU///////////////////////
						EXECUTE [dbo].[PG_IN_INVENTARIO_X_INSPECCION_MATERIAL]  @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_ORDEN_COMPRA_PEDIDO, @PP_K_ENTREGA, 
																				@PP_K_ITEM, @PP_LOTE_PEARL, 0, @VP_K_LOCACION_DESTINO

						-- //////////////////////SE NOTIFICA A LOS RESPONSABLES DE LA LOCACION A DONDE VA EL MATERIAL///////////////////////
						EXECUTE [dbo].[PG_CONFIGURAR_CORREO_MATERIAL_INSPECCIONADO_DISPOSICION] @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																								@PP_K_ORDEN_COMPRA, @PP_K_ORDEN_COMPRA_PEDIDO,
																								@PP_K_ENTREGA, @PP_K_ITEM, @PP_LOTE_PEARL,
																								@VP_LOCACION_DESTINO

					END
				-- //////////////////////////////////////////////////////////////

			COMMIT TRANSACTION 
			END TRY
	
			BEGIN CATCH
				/* Ocurrió un error, deshacemos los cambios*/ 
				ROLLBACK TRANSACTION
				DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
				SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
				SET @VP_MENSAJE = 'ERROR: //TRANSAC. PG_IN_UP_INSPECCION_MATERIAL_ORDEN_COMPRA // ' + @VP_ERROR_TRANS
			END CATCH
				
		END

	-- // SECCION#3 ////////////////////////////////////////////////////////// MENSAJE DE SALIDA
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Crear] la [INSPECCION_MATERIAL_ORDEN]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#INSP.'+CONVERT(VARCHAR(10),@VP_K_INSPECCION_MATERIAL_ORDEN_COMPRA)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'
	
		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @VP_K_INSPECCION_MATERIAL_ORDEN_COMPRA AS CLAVE

	-- //////////////////////////////////////////////////////////////

GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> INSERT
-- //////////////////////////////////////////////////////////////

--PG_IN_UP_INSPECCION_MATERIAL_ORDEN
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN_COMPRA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN_COMPRA]
GO
/*
 EXECUTE [PG_UP_INSPECCION_MATERIAL_ORDEN] 0,0,    10 , '10-001' , 35 , 2 , 2 , '0.9' , 'SE MODIFICO RESULTADO PORQUE SE CAPTURO MAL' 
*/
CREATE PROCEDURE [dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN_COMPRA]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================	
	@PP_K_ORDEN_COMPRA					INT,
	@PP_K_ORDEN_COMPRA_PEDIDO			VARCHAR(50),
	@PP_K_ENTREGA						INT,
	@PP_K_ITEM							INT,
	@PP_LOTE_PEARL						INT,
	@PP_K_INSPECCION_MATERIAL			INT,
	@PP_K_TIPO_INSPECCION_MATERIAL		INT,
	-- ===========================	
	@PP_RESULTADO_INSPECCION			VARCHAR(255),
	@PP_ACEPTADO						INT,
	@PP_COMENTARIO						VARCHAR(255),
	@PP_D_USUARIO_AUTORIZACION			VARCHAR(150)
	-- ============================			
AS			
	
	DECLARE @VP_MENSAJE		VARCHAR(300) = ''
	
	-- // SECCION#1 /////////////////////////////////////////////////////////// VALIDACIONES + REGLAS DE NEGOCIO 	
	
	DECLARE @VP_K_INSPECCION_MATERIAL_ORDEN	INT = 0
	
	IF @VP_MENSAJE=''	
		--EXECUTE [dbo].[PG_RN_INSPECCION_MATERIAL_ORDEN_UPDATE]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
		--														@PP_INSPECCION_PORCENTAJE, @PP_OPCION_1_PORCENTAJE,
		--														@PP_OPCION_2_PORCENTAJE, @PP_OPCION_3_PORCENTAJE,
		--														@PP_OPCION_4_PORCENTAJE, @PP_OPCION_5_PORCENTAJE,
		--														@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	-- // SECCION#2 ////////////////////////////////////////////////////////// ACCION A REALIZAR
	
	IF @VP_MENSAJE=''
		BEGIN
			BEGIN TRANSACTION 
			BEGIN TRY
				DECLARE @VP_OPCION_SELECCIONADA_ANTERIOR VARCHAR(255) = ''
			
				-- ///////SI ES UNA INSPECCION TIPO 2 SE OBTIENE EL VALOR INGRESADO ANTERIORMENTE//////////////////
				SELECT	@VP_OPCION_SELECCIONADA_ANTERIOR = [OPCION_SELECCIONADA]
				FROM	[INSPECCION_MATERIAL_ORDEN_COMPRA]
				WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
				AND		K_ENTREGA = @PP_K_ENTREGA
				AND		K_ITEM = @PP_K_ITEM
				AND		LOTE_PEARL = @PP_LOTE_PEARL
				AND		K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL

				IF @VP_OPCION_SELECCIONADA_ANTERIOR IS NULL
					RAISERROR ('ERROR: No fue posible obtener el resultado de la inspeccion en [INSPECCION_MATERIAL_ORDEN_COMPRA] ', 16, 1 ) --MENSAJE - Severity -State. 

				-- ///////SI ES UNA INSPECCION TIPO 2 SE OBTIENE LOS PARAMETROS DE EVALUACION//////////////////
				IF @PP_K_TIPO_INSPECCION_MATERIAL = '2' --EVALUACION
					BEGIN
						DECLARE @VALOR_MINIMO DECIMAL(13,2) = 0
						DECLARE @VALOR_MAXIMO DECIMAL(13,2) = 0

						SELECT  @VALOR_MINIMO = CONVERT(DECIMAL(13,2),ISNULL(OPCION_1, 0)),
								@VALOR_MAXIMO = CONVERT(DECIMAL(13,2),ISNULL(OPCION_2, 0))
						FROM INSPECCION_OPCION
						WHERE [K_INSPECCION_MATERIAL] = @PP_K_INSPECCION_MATERIAL


						DECLARE @VP_VALOR_INSPECCION_DECIMAL DECIMAL(13,2) = CONVERT(DECIMAL(13,2), @PP_RESULTADO_INSPECCION)

						IF ( @VP_VALOR_INSPECCION_DECIMAL < @VALOR_MINIMO OR @VP_VALOR_INSPECCION_DECIMAL > @VALOR_MAXIMO )
							SET @PP_ACEPTADO = 0
					END

				-- ///////SI ACTUALIZA LA INSPECCION CON ESA ORDEN_COMPRA, NUMERO DE PARTE E INSPECCION EN [INSPECCION_MATERIAL_ORDEN_COMPRA]//////////////////
				UPDATE [INSPECCION_MATERIAL_ORDEN_COMPRA]
					SET	[OPCION_SELECCIONADA]					= @PP_RESULTADO_INSPECCION,
						[COMENTARIO]							= @PP_COMENTARIO,
						[ACEPTADO]								= @PP_ACEPTADO,
						[F_ORDEN_COMPRA_INSPECCION_MATERIAL]	= GETDATE(),
						F_CAMBIO								= GETDATE(),
						K_USUARIO_CAMBIO						= @PP_K_USUARIO_ACCION
				WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
				AND		K_ENTREGA = @PP_K_ENTREGA
				AND		K_ITEM = @PP_K_ITEM
				AND		LOTE_PEARL = @PP_LOTE_PEARL
				AND		K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL
				
				IF @@ROWCOUNT = 0
					RAISERROR ('ERROR: No fue posible actualizar la inspección en [INSPECCION_MATERIAL_ORDEN_COMPRA] ', 16, 1 ) --MENSAJE - Severity -State.

				-- ///////////////////SE OBTIENE EL USUARIO QUE AUTORIZO EL CAMBIO////////////// 
				DECLARE @VP_K_USUARIO_AUTORIZACION INT = 0
				SELECT  @VP_K_USUARIO_AUTORIZACION = K_USUARIO
				FROM	BD_GENERAL.DBO.[GRUPO_APROBADOR] 
				INNER	JOIN [BD_GENERAL].dbo.USUARIO_PEARL ON [GRUPO_APROBADOR].K_USUARIO = USUARIO_PEARL.K_USUARIO_PEARL
				WHERE	D_USUARIO_PEARL = @PP_D_USUARIO_AUTORIZACION	
				AND		D_GRUPO_APROBADOR = 'QA MADIFICAR INSPECCION MATERIAL'
				AND		K_ESTATUS_GRUPO_APROBADOR = 1 -- ACTIVO
				AND		K_TIPO_GRUPO_APROBADOR = 150 --  MODIFICAR INSPECCION MATERIAL QA

				IF @VP_K_USUARIO_AUTORIZACION IS NULL
					RAISERROR ('ERROR: No fue posible obtener usuario aprobador en [GRUPO_APROBADOR] ', 16, 1 ) --MENSAJE - Severity -State. 

				-- ///////////////////INGRESO EL LOG DEL RESULTADO DE LA INSPECCION DEL MATERIAL//////////////
				DECLARE @VP_TIPO_INSPECCION_MATERIAL_LOG	INT = 5 -- MODIFICACION INSPECCION MANUAL
				 
				EXECUTE [dbo].[PG_IN_INSPECCION_MATERIAL_ORDEN_COMPRA_LOG]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																			@VP_TIPO_INSPECCION_MATERIAL_LOG, @PP_K_ORDEN_COMPRA,
																			@PP_K_ORDEN_COMPRA_PEDIDO, @PP_K_ENTREGA, @PP_K_ITEM, @PP_LOTE_PEARL,
																			@PP_K_INSPECCION_MATERIAL, @VP_OPCION_SELECCIONADA_ANTERIOR,
																			@PP_RESULTADO_INSPECCION, @VP_K_USUARIO_AUTORIZACION, @PP_COMENTARIO

				-- ///////SE OBTIENE EL RESULTADO DE LA INSPECCION ANTERIOR EN [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]//////////////////
				DECLARE @VP_ACEPTADO_ACTUAL VARCHAR(255) = ''
				SELECT	@VP_ACEPTADO_ACTUAL = ACEPTADO
				FROM	[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]
				WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
				AND		K_ENTREGA = @PP_K_ENTREGA
				AND		K_ITEM = @PP_K_ITEM
				AND		LOTE_PEARL = @PP_LOTE_PEARL

				-- ///////SE VERIFICA SI HAY UNA INSPECCION RECHAZADA PARA RECHAZAR LA INSPECCION COMPLETA///////////////////////////////////////////////////////
				DECLARE @VP_N_RECHAZO	INT = 0
				SELECT	@VP_N_RECHAZO	=	COUNT([K_INSPECCION_MATERIAL_ORDEN_COMPRA])
				FROM	INSPECCION_MATERIAL_ORDEN_COMPRA
				WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
				AND		K_ENTREGA = @PP_K_ENTREGA
				AND		K_ITEM = @PP_K_ITEM
				AND		LOTE_PEARL = @PP_LOTE_PEARL
				AND		ACEPTADO = 0

				IF @VP_N_RECHAZO IS NULL
					RAISERROR ('ERROR: No fue posible obtener el numero de inspecciones en [INSPECCION_MATERIAL_ORDEN_COMPRA] ', 16, 1 ) --MENSAJE - Severity -State.
				-- =================================

				DECLARE @VP_ACEPTADO_NUEVO	INT = 1

				IF @VP_N_RECHAZO > 0
					SET @VP_ACEPTADO_NUEVO = 0

				IF @VP_ACEPTADO_ACTUAL <> @VP_ACEPTADO_NUEVO
					BEGIN
						-- ///////SE ACTUALIZA LA INSPECCION CON ESA ORDEN Y NUEMERO DE PARTE EN [INSPECCION_MATERIAL_ORDEN]//////////////////
						UPDATE	[INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]
							SET	[ACEPTADO]										= @VP_ACEPTADO_NUEVO,
								[K_USUARIO_ALTA]								= @PP_K_USUARIO_ACCION,
								[F_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]	= GETDATE()	
						WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
						AND		K_ENTREGA = @PP_K_ENTREGA
						AND		K_ITEM = @PP_K_ITEM
						AND		LOTE_PEARL = @PP_LOTE_PEARL

						IF @@ROWCOUNT = 0
							RAISERROR ('ERROR: No fue posible actualizar la inspección en [INSPECCION_MATERIAL_ORDEN_RESULTADO] ', 16, 1 ) --MENSAJE - Severity -State.
					
						-- ///////////////////INGRESO EL LOG DEL RESULTADO DE LA INSPECCION DEL MATERIAL//////////////
						--SELECT * FROM TIPO_INSPECCION_MATERIAL_ORDEN_COMPRA_LOG
						IF @VP_ACEPTADO_NUEVO = 1
							SET	@VP_TIPO_INSPECCION_MATERIAL_LOG = 1 -- APROBACION SISTEMA
						ELSE
							SET	@VP_TIPO_INSPECCION_MATERIAL_LOG = 2 -- RECHAZO SISTEMA

						SET	@PP_COMENTARIO = 'La modificación de la inspección: ' + CONVERT(VARCHAR(10), @PP_K_INSPECCION_MATERIAL) + ' cambio el Estatus del lote.'

						EXECUTE [dbo].[PG_IN_INSPECCION_MATERIAL_ORDEN_COMPRA_LOG]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																					@VP_TIPO_INSPECCION_MATERIAL_LOG, @PP_K_ORDEN_COMPRA,
																					@PP_K_ORDEN_COMPRA_PEDIDO, @PP_K_ENTREGA, @PP_K_ITEM, @PP_LOTE_PEARL,
																					0, '', '', @VP_K_USUARIO_AUTORIZACION, @PP_COMENTARIO

						-- //////////////////////SE OBTIENE LA LOCACION MHI POR DEFAULT///////////////////////
						DECLARE @VP_K_LOCACION_ORIGEN INT =  6 -- MQU
						DECLARE @VP_K_LOCACION_DESTINO INT = 4 --MHI
						DECLARE @VP_LOCACION_DESTINO VARCHAR(5) = ''

						SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
							FROM	imlocfil_sql 
						WHERE A4GLIdentity = @VP_K_LOCACION_DESTINO 
													
						-- //////////////////////SE OBTIENE LA LOCACION MQU SI EL RESULTADO DE LA INSPECCION ES RECHAZADO///////////////////////
						IF @VP_ACEPTADO_NUEVO = 0
							BEGIN
								SET @VP_K_LOCACION_ORIGEN =  4 --MHI
								SET @VP_K_LOCACION_DESTINO = 6 -- MQU
								
								SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
								FROM	imlocfil_sql 
								WHERE A4GLIdentity = @VP_K_LOCACION_DESTINO
							END

						IF @VP_LOCACION_DESTINO IS NULL
							RAISERROR ('ERROR: No fue posible obtener la locacion en [imlocfil_sql] ', 16, 1 ) --MENSAJE - Severity -State.
							
						IF @VP_LOCACION_DESTINO NOT IN ('MHI','MQU')
							RAISERROR ('ERROR: Locacion no valida.', 16, 1 ) --MENSAJE - Severity -State.

						-- //////////////////////SE TRANSFIERE EL MATERIAL A LA LOCACION QUE CORRESPONDA MHI/MQU///////////////////////
						EXECUTE [dbo].[PG_IN_INVENTARIO_X_INSPECCION_MATERIAL]  @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_ORDEN_COMPRA_PEDIDO, @PP_K_ENTREGA, 
																				@PP_K_ITEM, @PP_LOTE_PEARL, @VP_K_LOCACION_ORIGEN, @VP_K_LOCACION_DESTINO

						-- //////////////////////SE NOTIFICA A LOS RESPONSABLES DE LA LOCACION A DONDE VA EL MATERIAL///////////////////////
						EXECUTE [dbo].[PG_CONFIGURAR_CORREO_MATERIAL_INSPECCIONADO_DISPOSICION] @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																								@PP_K_ORDEN_COMPRA, @PP_K_ORDEN_COMPRA_PEDIDO,
																								@PP_K_ENTREGA, @PP_K_ITEM, @PP_LOTE_PEARL,
																								@VP_LOCACION_DESTINO
					END

				-- //////////////////////////////////////////////////////////////

			COMMIT TRANSACTION 
			END TRY
	
			BEGIN CATCH
				/* Ocurrió un error, deshacemos los cambios*/ 
				ROLLBACK TRANSACTION
				DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
				SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
				SET @VP_MENSAJE = 'ERROR: //TRANSAC. PG_UP_INSPECCION_MATERIAL_ORDEN // ' + @VP_ERROR_TRANS
			END CATCH
				
		END

	-- // SECCION#3 ////////////////////////////////////////////////////////// MENSAJE DE SALIDA
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Actualizar] la [INSPECCION_MATERIAL_ORDEN]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#INSP.'+CONVERT(VARCHAR(10),@VP_K_INSPECCION_MATERIAL_ORDEN)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'
	
		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @VP_K_INSPECCION_MATERIAL_ORDEN AS CLAVE

	-- //////////////////////////////////////////////////////////////

GO





-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN_RESULTADO_APROBACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN_RESULTADO_APROBACION]
GO
/*
	EXEC [PG_UP_INSPECCION_MATERIAL_ORDEN_RESULTADO_APROBACION] 0,0, 00296-00001 , '1' , 82 , 201000002 , 0 , 'franciscoe' , 'rechazo manual' 
*/

CREATE PROCEDURE [dbo].[PG_UP_INSPECCION_MATERIAL_ORDEN_RESULTADO_APROBACION]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA_PEDIDO	VARCHAR(100),
	@PP_K_ENTREGA				INT,
	@PP_K_ITEM					INT,
	@PP_LOTE_PEARL				INT,
	@PP_ACEPTADO				INT,
	@PP_D_USUARIO_AUTORIZACION	VARCHAR(150),
	@PP_COMENTARIO				VARCHAR(255)
AS

	DECLARE @VP_MENSAJE		VARCHAR(300) = ''

	-- // SECCION#1 /////////////////////////////////////////////////////////// VALIDACIONES + REGLAS DE NEGOCIO 
	
	IF @VP_MENSAJE=''
		--EXECUTE [dbo].[PG_RN_INSPECCION_MATERIAL_DELETE]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
		--									@PP_K_INSPECCION_MATERIAL, 
		--									@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	-- // SECCION#2 ////////////////////////////////////////////////////////// ACCION A REALIZAR

	IF @VP_MENSAJE=''
		BEGIN
			BEGIN TRANSACTION 
			BEGIN TRY
				DECLARE @VP_TIPO_INSPECCION_MATERIAL_LOG	INT = 3 -- APROBACION MANUAL
				
				-- ===========================
				IF @PP_ACEPTADO = 0
					SET @VP_TIPO_INSPECCION_MATERIAL_LOG = 4 -- RECHAZO MANUAL

				-- ===========================
				DECLARE @VP_ESTATUS_ACTUAL	INT = 0
				DECLARE @VP_K_ORDEN_COMPRA	INT = 0

				SELECT	@VP_ESTATUS_ACTUAL = ACEPTADO,
						@VP_K_ORDEN_COMPRA = K_ORDEN_COMPRA
				FROM	INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO
				WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
				AND		K_ENTREGA = @PP_K_ENTREGA
				AND		K_ITEM = @PP_K_ITEM
				AND		LOTE_PEARL = @PP_LOTE_PEARL
											
				IF @VP_ESTATUS_ACTUAL IS NULL
					RAISERROR ('ERROR: No fue posible obtener el estatus actual de la inspección en [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]', 16, 1 ) --MENSAJE - Severity -State. 
								
				-- ///////////////////SE VALIDA QUE EL ESTATUS ANTERIOR NO SEA IGUAL AL NUEVO////////////// 	
				IF @PP_ACEPTADO = 1 AND @VP_ESTATUS_ACTUAL = 1
					RAISERROR ('ERROR: El material ya se encuentra Aceptado en [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO] ', 16, 1 ) --MENSAJE - Severity -State. 
				-- ===========================

				
				IF @PP_ACEPTADO = 0 AND @VP_ESTATUS_ACTUAL = 0
					RAISERROR ('ERROR: El material ya se encuentra Rechazado en [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO] ', 16, 1 ) --MENSAJE - Severity -State. 

				-- ///////////////////SE OBTIENE EL USUARIO QUE AUTORIZO EL CAMBIO////////////// 
				DECLARE @VP_K_USUARIO_AUTORIZACION INT = 0
				SELECT  @VP_K_USUARIO_AUTORIZACION = K_USUARIO
				FROM	BD_GENERAL.DBO.[GRUPO_APROBADOR] 
				INNER	JOIN [BD_GENERAL].dbo.USUARIO_PEARL ON [GRUPO_APROBADOR].K_USUARIO = USUARIO_PEARL.K_USUARIO_PEARL
				WHERE	D_USUARIO_PEARL = @PP_D_USUARIO_AUTORIZACION	
				AND		D_GRUPO_APROBADOR = 'QA MADIFICAR INSPECCION MATERIAL'
				AND		K_ESTATUS_GRUPO_APROBADOR = 1 -- ACTIVO
				AND		K_TIPO_GRUPO_APROBADOR = 150 --  MODIFICAR INSPECCION MATERIAL QA

				IF @VP_K_USUARIO_AUTORIZACION IS NULL
					RAISERROR ('ERROR: No fue posible obtener usuario aprobador en [GRUPO_APROBADOR] ', 16, 1 ) --MENSAJE - Severity -State. 

				-- ///////////////////SE ACTUALIZA EL DATO//////////////////////////////////////////////////
				UPDATE INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO
					SET [ACEPTADO]										= @PP_ACEPTADO,
						[K_USUARIO_ALTA]								= @PP_K_USUARIO_ACCION,
						[F_INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]	= GETDATE()	
				WHERE	K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
				AND		K_ENTREGA = @PP_K_ENTREGA
				AND		K_ITEM = @PP_K_ITEM
				AND		LOTE_PEARL = @PP_LOTE_PEARL

				IF @@ROWCOUNT = 0
					RAISERROR ('ERROR: No fue posible actualizar el estatus de la inspección en [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]', 16, 1 ) --MENSAJE - Severity -State.
				
				-- //////////////////////SE INGRESA EL LOG///////////////////////
				EXECUTE [dbo].[PG_IN_INSPECCION_MATERIAL_ORDEN_COMPRA_LOG]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																			@VP_TIPO_INSPECCION_MATERIAL_LOG, @VP_K_ORDEN_COMPRA,
																			@PP_K_ORDEN_COMPRA_PEDIDO, @PP_K_ENTREGA, @PP_K_ITEM, @PP_LOTE_PEARL,
																			0, '', '', @VP_K_USUARIO_AUTORIZACION, @PP_COMENTARIO

				-- //////////////////////SE OBTIENE LA LOCACION MHI POR DEFAULT///////////////////////
				DECLARE @VP_K_LOCACION_ORIGEN INT =  6 -- MQU
				DECLARE @VP_K_LOCACION_DESTINO INT = 4 --MHI
				DECLARE @VP_LOCACION_DESTINO VARCHAR(5) = ''

				SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
					FROM	imlocfil_sql 
				WHERE A4GLIdentity = @VP_K_LOCACION_DESTINO 
											
				-- //////////////////////SE OBTIENE LA LOCACION MQU SI EL RESULTADO DE LA INSPECCION ES RECHAZADO///////////////////////
				IF @PP_ACEPTADO = 0
					BEGIN
						SET @VP_K_LOCACION_ORIGEN =  4 --MHI
						SET @VP_K_LOCACION_DESTINO = 6 -- MQU

						SELECT	@VP_LOCACION_DESTINO = LTRIM(RTRIM(LOC))
						FROM	imlocfil_sql 
						WHERE A4GLIdentity = @VP_K_LOCACION_DESTINO
					END
					
				IF @VP_LOCACION_DESTINO IS NULL
					RAISERROR ('ERROR: No fue posible obtener la locacion en [imlocfil_sql] ', 16, 1 ) --MENSAJE - Severity -State.
					
				IF @VP_LOCACION_DESTINO NOT IN ('MHI','MQU')
					RAISERROR ('ERROR: Locacion no valida.', 16, 1 ) --MENSAJE - Severity -State.

				-- //////////////////////SE TRANSFIERE EL MATERIAL A LA LOCACION QUE CORRESPONDA MHI/MQU///////////////////////
				EXECUTE [dbo].[PG_IN_INVENTARIO_X_INSPECCION_MATERIAL]  @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																		@PP_K_ORDEN_COMPRA_PEDIDO, @PP_K_ENTREGA, 
																		@PP_K_ITEM, @PP_LOTE_PEARL, @VP_K_LOCACION_ORIGEN, @VP_K_LOCACION_DESTINO

				-- //////////////////////SE NOTIFICA A LOS RESPONSABLES DE LA LOCACION A DONDE VA EL MATERIAL///////////////////////
				EXECUTE [dbo].[PG_CONFIGURAR_CORREO_MATERIAL_INSPECCIONADO_DISPOSICION] @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																						@VP_K_ORDEN_COMPRA, @PP_K_ORDEN_COMPRA_PEDIDO,
																						@PP_K_ENTREGA, @PP_K_ITEM, @PP_LOTE_PEARL,
																						@VP_LOCACION_DESTINO
				-- //////////////////////////////////////////////////////////////
			COMMIT TRANSACTION 
			END TRY
	
			BEGIN CATCH
				/* Ocurrió un error, deshacemos los cambios*/ 
				ROLLBACK TRANSACTION
				DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
				SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
				SET @VP_MENSAJE = 'ERROR: //TRANSAC. PG_UP_INSPECCION_MATERIAL_ORDEN_RESULTADO_APROBACION // ' + @VP_ERROR_TRANS
			END CATCH
		
		END

	-- // SECCION#3 ////////////////////////////////////////////////////////// MENSAJE DE SALIDA
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Actualizar] la [INSPECCION_MATERIAL]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#ITEM.'+ CONVERT(VARCHAR(10),@PP_K_ITEM) +']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'

		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_ITEM AS CLAVE

	-- //////////////////////////////////////////////////////////////
GO

-- //////////////////////////////////////////////////////////////	
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
