-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[DATA_02]
-- // MODULO:			QA INSPECCION DE MATERIAL
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	20/AGO/2020
-- //////////////////////////////////////////////////////////////  

USE [DATA_02]
GO

-- //////////////////////////////////////////////////////////////



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_INSPECCION_MATERIAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_INSPECCION_MATERIAL]
GO

/*
 EXEC	[dbo].[PG_LI_INSPECCION_MATERIAL] 0,0,  '' , 70 , 180 
*/

CREATE PROCEDURE [dbo].[PG_LI_INSPECCION_MATERIAL]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_BUSCAR							VARCHAR(200),
	-- ===========================
	@PP_K_ITEM							INT,
	@PP_K_ITEM_AGREGAR					INT
AS

	DECLARE @VP_MENSAJE				VARCHAR(300) = ''
	
	-- ///////////////////////////////////////////

	SELECT	
			INSPECCION_MATERIAL.*,
			0 AS COPIAR,
			PART_NUMBER_ITEM_PEARL AS NUMERO_PARTE,
			OPCION_1,
			OPCION_2,
			OPCION_3,
			OPCION_4,
			OPCION_5,
			D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
			D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
			K_USUARIO_PEARL AS D_USUARIO_CAMBIO
			-- =============================	
	FROM	INSPECCION_MATERIAL
	INNER JOIN INSPECCION_OPCION ON INSPECCION_OPCION.K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
	INNER JOIN COMPRAS.dbo.ITEM ON ITEM.K_ITEM = INSPECCION_MATERIAL.K_ITEM
	INNER JOIN ESTATUS_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL		
	INNER JOIN TIPO_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL ON INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
			-- =============================
	WHERE	(	D_TIPO_INSPECCION_MATERIAL				LIKE '%'+@PP_BUSCAR+'%'
			OR	INSPECCION								LIKE '%'+@PP_BUSCAR+'%' 
			OR	PART_NUMBER_ITEM_PEARL					LIKE '%'+@PP_BUSCAR+'%' )
			-- =============================
	AND		( @PP_K_ITEM = -1		OR	INSPECCION_MATERIAL.K_ITEM = @PP_K_ITEM )
	AND		INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = 1 --ACTIVA
	AND		INSPECCION_MATERIAL.K_ITEM <> @PP_K_ITEM_AGREGAR
			-- =============================
	ORDER BY	F_INSPECCION_MATERIAL, K_ITEM DESC
	
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_MATERIAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_MATERIAL] 0,144,1
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_INSPECCION_MATERIAL		INT
AS

	DECLARE @VP_MENSAJE						VARCHAR(300) = ''
	-- ///////////////////////////////////////////

	SELECT	
			INSPECCION_MATERIAL.*,
			INSPECCION_OPCION.*,
			D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
			D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
			K_USUARIO_PEARL AS D_USUARIO_CAMBIO
			-- =============================	
	FROM	INSPECCION_MATERIAL, ESTATUS_INSPECCION_MATERIAL,
			TIPO_INSPECCION_MATERIAL, INSPECCION_OPCION,
			BD_GENERAL.dbo.USUARIO_PEARL
			-- =============================
	WHERE	INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL
	AND		INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	AND		INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
	AND		INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
			-- =============================
	AND		INSPECCION_MATERIAL.K_INSPECCION_MATERIAL=@PP_K_INSPECCION_MATERIAL


	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_MATERIAL_X_K_ITEM_CON_OPCION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_X_K_ITEM_CON_OPCION]
GO

/*
 EXEC	[dbo].[PG_SK_INSPECCION_MATERIAL_X_K_ITEM_CON_OPCION] 0,0,   '00296-00001' , 1 , 82 , 201000002 ,  , 0 , 2 
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_X_K_ITEM_CON_OPCION]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ORDEN_COMPRA_PEDIDO		VARCHAR(50),
	@PP_K_ENTREGA					INT,
	@PP_K_ITEM						INT,
	@PP_LOTE_PEARL					INT,
	@PP_K_INSPECCION_MATERIAL		INT,
	@PP_PRIMER_INSPECCION			INT, --#0 Cuando se abre ficha, #1 cuando se oprime adelande o atras 
	@PP_TIPO_MOVIMIENTO				INT --#0 ANTERIOR, #1 SIGUIENTE
AS

	DECLARE @VP_MENSAJE						VARCHAR(300) = ''

	DECLARE @VP_N_INSPECCION_X_ITEM INT = 0

	-- ////////////////////////////////////////////////
	SELECT @VP_N_INSPECCION_X_ITEM = COUNT(K_INSPECCION_MATERIAL)
	FROM INSPECCION_MATERIAL
	WHERE K_ITEM = @PP_K_ITEM
	AND		INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = 1 -- ACTIVA

	IF @VP_N_INSPECCION_X_ITEM IS NULL
		SET @VP_N_INSPECCION_X_ITEM = 0
		
	-- ////////////////////////////////////////////////
	IF @PP_TIPO_MOVIMIENTO = 1 -- SIGUIENTE
		SELECT	TOP 1
				INSPECCION_MATERIAL.*,
				INSPECCION_OPCION.*,
				D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
				D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
				K_USUARIO_PEARL AS D_USUARIO_CAMBIO,
				ISNULL([INSPECCION_MATERIAL_ORDEN_COMPRA].OPCION_SELECCIONADA, '') AS OPCION_SELECCIONADA,
				ISNULL([INSPECCION_MATERIAL_ORDEN_COMPRA].ACEPTADO, '') AS ACEPTADO,
				ISNULL([INSPECCION_MATERIAL_ORDEN_COMPRA].COMENTARIO, '') AS COMENTARIO,
				@VP_N_INSPECCION_X_ITEM AS TOTAL_INSPECCION
				-- =============================	
		FROM	INSPECCION_MATERIAL
				-- =============================
				INNER JOIN ESTATUS_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL
				INNER JOIN TIPO_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
				INNER JOIN INSPECCION_OPCION ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
				INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL ON INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
				LEFT  JOIN [INSPECCION_MATERIAL_ORDEN_COMPRA] ON [INSPECCION_MATERIAL_ORDEN_COMPRA].K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
						AND	[INSPECCION_MATERIAL_ORDEN_COMPRA].K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
						AND	[INSPECCION_MATERIAL_ORDEN_COMPRA].K_ENTREGA = @PP_K_ENTREGA
						AND [INSPECCION_MATERIAL_ORDEN_COMPRA].K_ITEM = @PP_K_ITEM
						AND [INSPECCION_MATERIAL_ORDEN_COMPRA].LOTE_PEARL = @PP_LOTE_PEARL
				-- =============================
		WHERE	INSPECCION_MATERIAL.K_ITEM=@PP_K_ITEM
		AND		INSPECCION_MATERIAL.K_INSPECCION_MATERIAL > ( CASE	WHEN @PP_PRIMER_INSPECCION = 1	THEN 0
															ELSE @PP_K_INSPECCION_MATERIAL END )
		-- =============================
		AND		ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = 1 -- ACTIVA
		-- =============================
		ORDER BY INSPECCION_MATERIAL.K_INSPECCION_MATERIAL ASC

	-- ////////////////////////////////////////////////
	IF @PP_TIPO_MOVIMIENTO = 0 -- ANTERIOR
		SELECT	TOP 1
				INSPECCION_MATERIAL.*,
				INSPECCION_OPCION.*,
				D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
				D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
				K_USUARIO_PEARL AS D_USUARIO_CAMBIO,
				ISNULL([INSPECCION_MATERIAL_ORDEN_COMPRA].OPCION_SELECCIONADA, '') AS OPCION_SELECCIONADA,
				ISNULL([INSPECCION_MATERIAL_ORDEN_COMPRA].ACEPTADO, '') AS ACEPTADO,
				ISNULL([INSPECCION_MATERIAL_ORDEN_COMPRA].COMENTARIO, '') AS COMENTARIO,
				@VP_N_INSPECCION_X_ITEM AS TOTAL_INSPECCION
				-- =============================	
		FROM	INSPECCION_MATERIAL
				-- =============================
				INNER JOIN ESTATUS_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL
				INNER JOIN TIPO_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
				INNER JOIN INSPECCION_OPCION ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
				INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL ON INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
				LEFT  JOIN [INSPECCION_MATERIAL_ORDEN_COMPRA] ON [INSPECCION_MATERIAL_ORDEN_COMPRA].K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
						AND	[INSPECCION_MATERIAL_ORDEN_COMPRA].K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
						AND	[INSPECCION_MATERIAL_ORDEN_COMPRA].K_ENTREGA = @PP_K_ENTREGA
						AND [INSPECCION_MATERIAL_ORDEN_COMPRA].K_ITEM = @PP_K_ITEM
						AND [INSPECCION_MATERIAL_ORDEN_COMPRA].LOTE_PEARL = @PP_LOTE_PEARL
				-- =============================
		WHERE	INSPECCION_MATERIAL.K_ITEM=@PP_K_ITEM
		AND		INSPECCION_MATERIAL.K_INSPECCION_MATERIAL < ( CASE	WHEN @PP_PRIMER_INSPECCION = 1	THEN 0
																	ELSE @PP_K_INSPECCION_MATERIAL END )
		-- =============================
		AND		ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = 1 -- ACTIVA
		-- =============================
		ORDER BY INSPECCION_MATERIAL.K_INSPECCION_MATERIAL DESC


		-- ////////////////////////////////////////////////
	IF @PP_TIPO_MOVIMIENTO = 2 -- PARA ACTUALIZAR INSPECCION FO_AUTORIZAR_INSPECCION_MATERIAL
		SELECT	TOP 1
				INSPECCION_MATERIAL.*,
				INSPECCION_OPCION.*,
				D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
				D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
				K_USUARIO_PEARL AS D_USUARIO_CAMBIO,
				ISNULL([INSPECCION_MATERIAL_ORDEN_COMPRA].OPCION_SELECCIONADA, '') AS OPCION_SELECCIONADA,
				ISNULL([INSPECCION_MATERIAL_ORDEN_COMPRA].ACEPTADO, '') AS ACEPTADO,
				ISNULL([INSPECCION_MATERIAL_ORDEN_COMPRA].COMENTARIO, '') AS COMENTARIO,
				@VP_N_INSPECCION_X_ITEM AS TOTAL_INSPECCION
				-- =============================	
		FROM	INSPECCION_MATERIAL
				-- =============================
				INNER JOIN ESTATUS_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL
				INNER JOIN TIPO_INSPECCION_MATERIAL ON INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
				INNER JOIN INSPECCION_OPCION ON INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = INSPECCION_OPCION.K_INSPECCION_MATERIAL
				INNER JOIN BD_GENERAL.dbo.USUARIO_PEARL ON INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
				LEFT  JOIN [INSPECCION_MATERIAL_ORDEN_COMPRA] ON [INSPECCION_MATERIAL_ORDEN_COMPRA].K_INSPECCION_MATERIAL = INSPECCION_MATERIAL.K_INSPECCION_MATERIAL
						AND	[INSPECCION_MATERIAL_ORDEN_COMPRA].K_ORDEN_COMPRA_PEDIDO = @PP_K_ORDEN_COMPRA_PEDIDO
						AND	[INSPECCION_MATERIAL_ORDEN_COMPRA].K_ENTREGA = @PP_K_ENTREGA
						AND [INSPECCION_MATERIAL_ORDEN_COMPRA].K_ITEM = @PP_K_ITEM
						AND [INSPECCION_MATERIAL_ORDEN_COMPRA].LOTE_PEARL = @PP_LOTE_PEARL
				-- =============================
		WHERE	INSPECCION_MATERIAL.K_ITEM = @PP_K_ITEM
		AND		INSPECCION_MATERIAL.K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL 
		-- =============================
		ORDER BY INSPECCION_MATERIAL.K_INSPECCION_MATERIAL DESC

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_INSPECCION_MATERIAL_X_K_ITEM]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_X_K_ITEM]
GO

/*
SELECT * FROM INSPECCION_MATERIAL
 EXEC	[dbo].[PG_SK_INSPECCION_MATERIAL_X_K_ITEM] 0,0, 70
*/

CREATE PROCEDURE [dbo].[PG_SK_INSPECCION_MATERIAL_X_K_ITEM]
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_ITEM						INT
AS

	DECLARE @VP_MENSAJE				VARCHAR(300) = ''
	
	-- ///////////////////////////////////////////

	SELECT	
			INSPECCION_MATERIAL.*,
			D_ESTATUS_INSPECCION_MATERIAL, S_ESTATUS_INSPECCION_MATERIAL, 
			D_TIPO_INSPECCION_MATERIAL, S_TIPO_INSPECCION_MATERIAL, 
			D_USUARIO_PEARL AS D_USUARIO_CAMBIO
			-- =============================	
	FROM	INSPECCION_MATERIAL, ESTATUS_INSPECCION_MATERIAL,
			TIPO_INSPECCION_MATERIAL,
			BD_GENERAL.dbo.USUARIO_PEARL
			-- =============================
	WHERE	INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL
	AND		INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL = TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL
	AND		INSPECCION_MATERIAL.K_USUARIO_CAMBIO = BD_GENERAL.dbo.USUARIO_PEARL.K_USUARIO_PEARL
			-- =============================
	AND		K_ITEM=@PP_K_ITEM
	AND		ESTATUS_INSPECCION_MATERIAL.K_ESTATUS_INSPECCION_MATERIAL = 1 -- ACTIVA
	ORDER BY TIPO_INSPECCION_MATERIAL.K_TIPO_INSPECCION_MATERIAL 

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> INSERT
-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_IN_INSPECCION_MATERIAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_IN_INSPECCION_MATERIAL]
GO
/*
 EXECUTE [PG_IN_INSPECCION_MATERIAL] 0,0,   82 , 4 , 'Ingrese la ruta del archivo Test Result' , '' , '' , '' , '' , '' 
*/
CREATE PROCEDURE [dbo].[PG_IN_INSPECCION_MATERIAL]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================	
	@PP_K_ITEM							INT,
	@PP_K_TIPO_INSPECCION_MATERIAL		INT,
	-- ===========================	
	@PP_INSPECCION						VARCHAR(255),
	-- ============================		
	@PP_OPCION_1						VARCHAR(100),
	@PP_OPCION_2						VARCHAR(100),
	@PP_OPCION_3						VARCHAR(100),
	@PP_OPCION_4						VARCHAR(100),
	@PP_OPCION_5						VARCHAR(100)
AS			
	
	DECLARE @VP_MENSAJE		VARCHAR(300) = ''
	DECLARE @VP_K_INSPECCION_MATERIAL	INT = 0

	-- // SECCION#1 /////////////////////////////////////////////////////////// VALIDACIONES + REGLAS DE NEGOCIO 	
	IF @PP_K_TIPO_INSPECCION_MATERIAL = 4	
		EXECUTE [dbo].[PG_RN_INSPECCION_MATERIAL_INSERT]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
															@PP_K_ITEM, @PP_K_TIPO_INSPECCION_MATERIAL,
															@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	-- // SECCION#2 ////////////////////////////////////////////////////////// ACCION A REALIZAR
	
	IF @VP_MENSAJE=''
		BEGIN
			BEGIN TRANSACTION 
			BEGIN TRY
				
				EXECUTE BD_GENERAL.dbo.[PG_SK_CATALOGO_K_MAX_GET] @PP_K_SISTEMA_EXE,
																		'DATA_02', 'INSPECCION_MATERIAL', 'K_INSPECCION_MATERIAL',
																		@OU_K_TABLA_DISPONIBLE = @VP_K_INSPECCION_MATERIAL	OUTPUT

				-- ///////SE INSERTA LA INSPECCION DEL MATERIAL///////////////////////////////////////////////////////
				INSERT INTO [INSPECCION_MATERIAL]
					(	[K_INSPECCION_MATERIAL],
						-- ===========================
						[K_TIPO_INSPECCION_MATERIAL],
						[K_ESTATUS_INSPECCION_MATERIAL],
						[K_ITEM],
						-- ===========================
						[INSPECCION],
						[F_INSPECCION_MATERIAL],
						-- ===========================
						[K_USUARIO_ALTA], [F_ALTA], [K_USUARIO_CAMBIO], [F_CAMBIO],
						[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]  )
				VALUES	
					(	@VP_K_INSPECCION_MATERIAL,
						-- ===========================	
						@PP_K_TIPO_INSPECCION_MATERIAL,
						1, -- ACTIVA
						@PP_K_ITEM,
						-- ===========================
						@PP_INSPECCION,
						GETDATE(),
						-- ===========================
						@PP_K_USUARIO_ACCION, GETDATE(), @PP_K_USUARIO_ACCION, GETDATE(),
						0, NULL, NULL )

				IF @@ROWCOUNT = 0
					RAISERROR ('ERROR: No se ingreso la [INSPECCION_MATERIAL] ', 16, 1 ) --MENSAJE - Severity -State.
					--=====================================================
					
				-- /////////////SE INSERTAN LAS OPCIONES/PARAMETROS DEPENDIENDO DEL TIPO DE INSPECCION//////////////////////////////
				DECLARE @VP_K_INSPECCION_OPCION	INT = 0
				EXECUTE BD_GENERAL.dbo.[PG_SK_CATALOGO_K_MAX_GET] @PP_K_SISTEMA_EXE,
																'DATA_02', 'INSPECCION_OPCION', 'K_INSPECCION_OPCION',
																@OU_K_TABLA_DISPONIBLE = @VP_K_INSPECCION_OPCION	OUTPUT

				-- ///////SE INSERTA LA INSPECCION DEL MATERIAL///////////////////////////////////////////////////////
				INSERT INTO [INSPECCION_OPCION]
					(	[K_INSPECCION_OPCION],
						[K_INSPECCION_MATERIAL],
						-- ===========================
						[OPCION_1],
						[OPCION_2],
						[OPCION_3],
						[OPCION_4],
						[OPCION_5]	)
				VALUES	
					(	@VP_K_INSPECCION_OPCION,
						@VP_K_INSPECCION_MATERIAL,
						-- ===========================	
						@PP_OPCION_1,
						@PP_OPCION_2,
						@PP_OPCION_3,
						@PP_OPCION_4,
						@PP_OPCION_5	)
				
				IF @@ROWCOUNT = 0
					RAISERROR ('ERROR: No se ingreso la [INSPECCION_OPCION] ', 16, 1 ) --MENSAJE - Severity -State.
					--=====================================================
				-- //////////////////////////////////////////////////////////////

			COMMIT TRANSACTION 
			END TRY
	
			BEGIN CATCH
				/* Ocurrió un error, deshacemos los cambios*/ 
				ROLLBACK TRANSACTION
				DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
				SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
				SET @VP_MENSAJE = 'ERROR: //TRANSAC. PG_IN_INSPECCION_MATERIAL // ' + @VP_ERROR_TRANS
			END CATCH
				
		END

	-- // SECCION#3 ////////////////////////////////////////////////////////// MENSAJE DE SALIDA
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Crear] la [INSPECCION_MATERIAL]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#INSP.'+CONVERT(VARCHAR(10),@VP_K_INSPECCION_MATERIAL)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'
	
		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @VP_K_INSPECCION_MATERIAL AS CLAVE

	-- //////////////////////////////////////////////////////////////

GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> ACTUALIZAR / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_INSPECCION_MATERIAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_INSPECCION_MATERIAL]
GO
-- EXEC [PG_UP_INSPECCION_MATERIAL] 0,0,  1 , '200435AWT3' , 80.00 , 2 , 'Cual es el grosor del Hilo?' , 80 , '0.5' , '1' , '' , '' , '' 
CREATE PROCEDURE [dbo].[PG_UP_INSPECCION_MATERIAL]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_K_INSPECCION_MATERIAL			INT,
	-- ===========================	
	@PP_K_ITEM							INT,
	@PP_K_TIPO_INSPECCION_MATERIAL		INT,
	-- ===========================	
	@PP_INSPECCION						VARCHAR(255),
	-- ============================		
	@PP_OPCION_1						VARCHAR(100),
	@PP_OPCION_2						VARCHAR(100),
	@PP_OPCION_3						VARCHAR(100),
	@PP_OPCION_4						VARCHAR(100),
	@PP_OPCION_5						VARCHAR(100)
	-- ============================		
AS			

	DECLARE @VP_MENSAJE		VARCHAR(300) = ''

	-- // SECCION#1 /////////////////////////////////////////////////////////// VALIDACIONES + REGLAS DE NEGOCIO 	
	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_INSPECCION_MATERIAL_UPDATE]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
															@PP_K_ITEM, @PP_K_INSPECCION_MATERIAL,
															@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	IF ( @VP_MENSAJE = '' AND @PP_K_TIPO_INSPECCION_MATERIAL = 4 ) -- TEST RESULT
		BEGIN
					DECLARE @VP_N_INSPECCION_TEST_RESULT INT = 0
					SELECT	@VP_N_INSPECCION_TEST_RESULT = COUNT(K_INSPECCION_MATERIAL)
					FROM	[INSPECCION_MATERIAL]
					WHERE	K_INSPECCION_MATERIAL <> @PP_K_INSPECCION_MATERIAL
					AND		K_ITEM = @PP_K_ITEM
					AND		K_TIPO_INSPECCION_MATERIAL = 4  -- TEST RESULT
					AND		K_ESTATUS_INSPECCION_MATERIAL = 1 --ACTIVA

					IF @VP_N_INSPECCION_TEST_RESULT IS NULL 
						SET @VP_N_INSPECCION_TEST_RESULT = 0

					IF @VP_N_INSPECCION_TEST_RESULT > 0
						SET @VP_MENSAJE = 'Este tipo de inspeccion solo se puede agregar una vez'
		END
	-- // SECCION#2 ////////////////////////////////////////////////////////// ACCION A REALIZAR
	
	IF @VP_MENSAJE=''
		BEGIN
			BEGIN TRANSACTION 
			BEGIN TRY
				-- ///////SE ACTUALIZA LA INSPECCION DEL MATERIAL///////////////////////////////////////////////////////
				UPDATE	[INSPECCION_MATERIAL]
					SET			
						[K_ITEM]						    = @PP_K_ITEM,
						-- ===========================
						[K_TIPO_INSPECCION_MATERIAL]		= @PP_K_TIPO_INSPECCION_MATERIAL,
						[INSPECCION]						= @PP_INSPECCION,  
						-- ===========================
					    [F_CAMBIO]							= GETDATE(), 
						[K_USUARIO_CAMBIO]					= @PP_K_USUARIO_ACCION
						-- ===========================
				WHERE	K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL

				IF @@ROWCOUNT = 0
					RAISERROR ('ERROR: No fue posible actualizar la [INSPECCION_MATERIAL] ', 16, 1 ) --MENSAJE - Severity -State.
				--=====================================================	

				-- /////////////SE ACTUALIZAN LAS OPCIONES/PARAMETROS DEPENDIENDO DEL TIPO DE INSPECCION//////////////////////////////
				UPDATE	[INSPECCION_OPCION]
					SET	
						-- ===========================
						[OPCION_1]				= @PP_OPCION_1,
						[OPCION_2]				= @PP_OPCION_2,
						[OPCION_3]				= @PP_OPCION_3,
						[OPCION_4]				= @PP_OPCION_4,
						[OPCION_5]				= @PP_OPCION_5	
						-- ===========================
				WHERE	K_INSPECCION_MATERIAL=@PP_K_INSPECCION_MATERIAL

				IF @@ROWCOUNT = 0
					RAISERROR ('ERROR: No fue posible actualizar la [INSPECCION_OPCION] ', 16, 1 ) --MENSAJE - Severity -State.
				-- //////////////////////////////////////////////////////////////

			COMMIT TRANSACTION 
			END TRY
	
			BEGIN CATCH
				/* Ocurrió un error, deshacemos los cambios*/ 
				ROLLBACK TRANSACTION
				DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
				SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
				SET @VP_MENSAJE = 'ERROR: //TRANSAC. PG_UP_INSPECCION_MATERIAL // ' + @VP_ERROR_TRANS
			END CATCH
	
		END

	-- // SECCION#3 ////////////////////////////////////////////////////////// MENSAJE DE SALIDA
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Actualizar] la [INSPECCION_MATERIAL]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#INSP.'+CONVERT(VARCHAR(10),@PP_K_INSPECCION_MATERIAL)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'

		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_INSPECCION_MATERIAL AS CLAVE

	-- //////////////////////////////////////////////////////////////
	
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_DL_INSPECCION_MATERIAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_DL_INSPECCION_MATERIAL]
GO


CREATE PROCEDURE [dbo].[PG_DL_INSPECCION_MATERIAL]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_INSPECCION_MATERIAL	INT,
	@PP_K_ITEM					INT
AS

	DECLARE @VP_MENSAJE		VARCHAR(300) = ''

	-- // SECCION#1 /////////////////////////////////////////////////////////// VALIDACIONES + REGLAS DE NEGOCIO 
	
	IF @VP_MENSAJE=''
		--EXECUTE [dbo].[PG_RN_INSPECCION_MATERIAL_DELETE]	@PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
		--									@PP_K_INSPECCION_MATERIAL, 
		--									@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	-- // SECCION#2 ////////////////////////////////////////////////////////// ACCION A REALIZAR

	IF @VP_MENSAJE=''
		BEGIN
			BEGIN TRANSACTION 
			BEGIN TRY

				UPDATE [INSPECCION_MATERIAL]
					SET K_ESTATUS_INSPECCION_MATERIAL = 0
				WHERE	K_INSPECCION_MATERIAL = @PP_K_INSPECCION_MATERIAL
				AND		K_ITEM = @PP_K_ITEM

				IF @@ROWCOUNT = 0
					RAISERROR ('ERROR: No se Elimino la [INSPECCION_MATERIAL] ', 16, 1 ) --MENSAJE - Severity -State.
				-- //////////////////////////////////////////////////////////////

			COMMIT TRANSACTION 
			END TRY
	
			BEGIN CATCH
				/* Ocurrió un error, deshacemos los cambios*/ 
				ROLLBACK TRANSACTION
				DECLARE @VP_ERROR_TRANS NVARCHAR(4000);
				SET @VP_ERROR_TRANS = ERROR_MESSAGE() 
				SET @VP_MENSAJE = 'ERROR: //TRANSAC. PG_DL_INSPECCION_MATERIAL // ' + @VP_ERROR_TRANS
			END CATCH
		
		END

	-- // SECCION#3 ////////////////////////////////////////////////////////// MENSAJE DE SALIDA
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Borrar] la [INSPECCION_MATERIAL]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#INSP.'+CONVERT(VARCHAR(10),@PP_K_INSPECCION_MATERIAL)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'

		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_INSPECCION_MATERIAL AS CLAVE

	-- //////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
