
USE DATA_02

SELECT * FROM TIPO_INSPECCION_MATERIAL

SELECT * FROM INSPECCION_MATERIAL --WHERE K_ITEM = 82
--DELETE INSPECCION_MATERIAL
SELECT * FROM INSPECCION_OPCION
--DELETE INSPECCION_OPCION
SELECT * FROM [INSPECCION_MATERIAL_ORDEN_COMPRA]	

SELECT * FROM [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO]	

SELECT * FROM INSPECCION_MATERIAL_ORDEN_COMPRA_LOG


SELECT TIPO_INSPECCION_MATERIAL_ORDEN_COMPRA_LOG.D_TIPO_INSPECCION_MATERIAL_ORDEN_COMPRA_LOG, INSPECCION_MATERIAL_ORDEN_COMPRA_LOG.* 
FROM INSPECCION_MATERIAL_ORDEN_COMPRA_LOG
INNER JOIN TIPO_INSPECCION_MATERIAL_ORDEN_COMPRA_LOG ON INSPECCION_MATERIAL_ORDEN_COMPRA_LOG.K_TIPO_INSPECCION_MATERIAL_ORDEN_COMPRA_LOG = TIPO_INSPECCION_MATERIAL_ORDEN_COMPRA_LOG.K_TIPO_INSPECCION_MATERIAL_ORDEN_COMPRA_LOG

SELECT * FROM INVENTARIO 
WHERE K_ORDEN_COMPRA_PEDIDO = '00320-00001'  AND K_ENTREGA = 1 AND k_item = 70

--SELECT * FROM STATUS_INVENTARIO

SELECT * FROM FOLIO --WHERE K_FOLIO = 1

SELECT * FROM INVENTARIO_LOCACION

SELECT * FROM INVENTARIO_MOVIMIENTO

SELECT * FROM INVENTARIO_MOVIMIENTO_X_REGISTRO


/*
DELETE  [INSPECCION_MATERIAL_ORDEN_COMPRA]	--WHERE LOTE_PEARL = 201000001
DELETE [INSPECCION_MATERIAL_ORDEN_COMPRA_RESULTADO] --WHERE LOTE_PEARL = 201000001
DELETE INSPECCION_MATERIAL_ORDEN_COMPRA_LOG --WHERE LOTE_PEARL = 201000001
*/

SELECT * FROM IMITMIDX_SQL WHERE PUR_OR_MFG = 'R'

SELECT * FROM COMPRAS.DBO.DETAILS_BPO_PEDIDO 

SELECT * FROM COMPRAS.DBO.DETAILS_BLANKET_PURCHASE_ORDER WHERE K_HEADER_PURCHASE_ORDER IN (107, 333)

SELECT * FROM COMPRAS.DBO.HEADER_BPO_PEDIDO WHERE K_ORDEN_COMPRA_PEDIDO = 2

SELECT * FROM COMPRAS.DBO.DETAILS_BPO_PEDIDO WHERE K_ORDEN_COMPRA_PEDIDO = 2

SELECT * FROM COMPRAS.DBO.DETAILS_BPO_RECIBO WHERE K_ORDEN_COMPRA_PEDIDO = 2

SELECT * FROM	COMPRAS_PRUEBAS.dbo.VENDOR

SELECT *  FROM IMITMIDX_SQL WHERE UPC_CD = 69

SELECT * FROM COMPRAS.dbo.ITEM WHERE K_ITEM = 69

SELECT * FROM ARCUSFIL_SQL

SELECT * FROM BD_GENERAL.DBO.USUARIO_PEARL

	select * from BD_GENERAL.dbo.TIPO_GRUPO_APROBADOR WHERE K_TIPO_GRUPO_APROBADOR IN  (180, 200)
	
	SELECT *
								FROM	BD_GENERAL.dbo.USUARIO_PEARL AS USERS
								INNER	JOIN	BD_GENERAL.dbo.GRUPO_APROBADOR GP_APROB ON GP_APROB.K_USUARIO=USERS.K_USUARIO_PEARL
								WHERE   GP_APROB.S_GRUPO_APROBADOR = 'MHI_MQU_LR'
								--AND		GP_APROB.K_TIPO_GRUPO_APROBADOR = 180
								AND		K_ESTATUS_GRUPO_APROBADOR = 1

SELECT	* 
FROM	BD_GENERAL.DBO.[GRUPO_APROBADOR] 
INNER	JOIN BD_GENERAL.DBO.USUARIO_PEARL ON [GRUPO_APROBADOR].K_USUARIO = USUARIO_PEARL.K_USUARIO_PEARL
WHERE	D_GRUPO_APROBADOR = 'QA MADIFICAR INSPECCION MATERIAL'
AND		K_ESTATUS_GRUPO_APROBADOR = 1 -- ACTIVO
AND		K_TIPO_GRUPO_APROBADOR = 150 --  MODIFICAR INSPECCION MATERIAL QA












