

--	
--SELECT * FROM [PPMS_PEARL].[dbo].rechazos WHERE  fecha >= '20220301' AND mesa = ''

-- /////////SE CREA EL CURSOR PARA RECORRER LOS KITS EN LA ORDEN///////////////////////////////////////
			DECLARE @VP_ORDEN VARCHAR(50) = ''

			DECLARE CU_RECHAZO_SIN_MESA CURSOR 
			FOR SELECT DISTINCT ORDEN 
				FROM [PPMS_PEARL].[dbo].rechazos (NOLOCK)
				WHERE  fecha >= '20220301' AND mesa = ''

			OPEN CU_RECHAZO_SIN_MESA
			FETCH NEXT FROM CU_RECHAZO_SIN_MESA INTO @VP_ORDEN

			WHILE @@FETCH_STATUS = 0 
				BEGIN		
					DECLARE @VP_MESA VARCHAR(50) = ''	
					SELECT @VP_MESA = LTRIM(RTRIM(MACHINE))
					FROM DATA_02.DBO.ccjobhdr_sql (NOLOCK)
					WHERE jobno = @VP_ORDEN

					UPDATE [PPMS_PEARL].[dbo].rechazos 
						SET mesa = @VP_MESA
					WHERE orden = @VP_ORDEN --AND LTRIM(RTRIM(MESA)) = ''

					FETCH NEXT FROM CU_RECHAZO_SIN_MESA INTO @VP_ORDEN
				END
				
			CLOSE CU_RECHAZO_SIN_MESA
			DEALLOCATE CU_RECHAZO_SIN_MESA