

USE PPMS_PEARL

	SELECT * FROM numpart WHERE noparte = '200766DTX7'

	SELECT * FROM certificacion_rpt WHERE orden = 50011 order by id

	SELECT * FROM [PPMS_PEARL].[dbo].personal (NOLOCK) WHERE SELLO = '100'

	SELECT * FROM [PPMS_PEARL].[dbo].personal (NOLOCK) WHERE NORELOJ =14869

	 SELECT  * FROM	DATA_02.DBO.IMITMIDX_SQL WHERE item_no= 'UWALFBLWLCPT3'

	SELECT * --LTRIM(RTRIM(CUS.CUS_ITEM_NO)) 
	FROM DATA_02.DBO.cccusitm_sql (NOLOCK)  
	WHERE ITEM_NO = 'PWSBRB6VCCAD4' 
	ORDER BY versionno DESC

	SELECT * FROM	DATA_02.DBO.ccprdstr_sql (NOLOCK) WHERE ITEM_NO IN ( 'PWSBRB6VCCAD4') ORDER BY versionno DESC
	
	SELECT * --TOP 1 PRC_OR_DISC_1
	FROM	DATA_02.DBO.OEPRCFIL_SQL 
	WHERE	LTRIM(RTRIM(filler_0001)) LIKE '%' + 'IC3A0008VCCAD4' 
	AND LTRIM(RTRIM(filler_0001)) LIKE 'FAUR01' + '%'
	ORDER BY A4GLIdentity DESC

	SELECT * FROM HOWE.DBO.VISTA_GAFETES (NOLOCK) WHERE  EN_NUM_EMP = 13367

	SELECT * FROM BD_GENERAL.dbo.USUARIO_PEARL WHERE D_USUARIO_PEARL = 'CERTIFICACION'

	SELECT * FROM [PPMS_PEARL].[dbo].DEF WHERE clave IN ( 'gb' )

	-- //////////PPMS DE PRD////////////////////////////////////////////////////
	SELECT * FROM [DATA_02].dbo.ccjoblin_sql WHERE JOBNO IN ( '52816', '53401')

	SELECT * FROM  [PPMS_PEARL].[dbo].Perforacion where orden = '41841' AND noserie = '41841005' AND [status] = 'FINALIZADO'

	SELECT * FROM [PPMS_PEARL].[dbo].certificacion_rpt where orden = '52795' AND noserie_caja = '52318001' 

	SELECT * FROM [DATA_02].dbo.pearl_log WHERE screen_opt = 'Modificar defecto' and  movement = 'DL' AND hideno = 'GB'

	SELECT * FROM [DATA_02].dbo.ccjobhdr_sql WHERE jobno = '51823'

	SELECT SUM(OriginalQty * patternsper)
	FROM [DATA_02].dbo.ccjoblin_sql WHERE  jobno = '45250'
		
	SELECT	tipodef	AS TIPO_DEFECTO, 
			CLAVE	AS CLAVE_DEFECTO,  
			COUNT(ID) AS TOTAL_DEFECTO
	FROM [PPMS_PEARL].[dbo].Rechazos (NOLOCK)
	INNER JOIN [PPMS_PEARL].[dbo].DEF (NOLOCK) ON clave = Rechazos.defecto
	WHERE ORDEN = 48100
	AND noparte = '201025A' --'201024A'
	GROUP BY tipodef, CLAVE
	ORDER BY tipodef, CLAVE

	SELECT DISTINCT tipodef FROM [PPMS_PEARL].[dbo].DEF (NOLOCK) WHERE tipodef = 'NORMAL'

	SELECT * FROM [PPMS_PEARL].[dbo].personal (NOLOCK) WHERE SELLO = '100'

	SELECT * FROM DATA_02.DBO.cccuthst_sql WHERE jobno IN ( '52638')

	SELECT * FROM DATA_02.DBO.ccjobhdr_sql WHERE jobno IN ( '34867')
	SELECT * FROM DATA_02.DBO.pearl_log WHERE jobno IN ( '53400', '53401')

	SELECT DISTINCT(tipodef) FROM [PPMS_PEARL].[dbo].DEF WHERE tipodef IN ( 'PERFORADORA' )
	SELECT TOP 1000 * FROM [PPMS_PEARL].[dbo].rechazos --WHERE  fecha = '20220426' AND Status = 'L' AND defecto = 'MP'
	ORDER BY ID DESC

	-- 339 + 1814 = 2,153
	SELECT * --SUM(DEFECTOS) DEFECTO, SUM(MUESTRA) MUESTRA 
	FROM [PPMS_PEARL].DBO.[ORDEN_LIBERADA]  WHERE CONVERT(DATE, F_ALTA) = '2022-04-26' --ORDEN IN ( 53400 , 53401 ) 
	--AND 
	--F_LIBERACION = '2022-02-07' --and K_TIPO_ORDEN_LIBERADA = 2
	ORDER BY F_ALTA ASC 	

	SELECT RIGHT('000'+ CONVERT(VARCHAR(5), 1), 3)

	SELECT * FROM [PPMS_PEARL].[dbo].[QC] WHERE Order_No = '53401' -- ID IN (303022)

	SELECT * FROM [PPMS_PEARL].[dbo].[DEFECTOS] WHERE Orden = 50011 -- ID IN (303022)
	
	SELECT * FROM [BD_GENERAL].[dbo].USUARIO_PEARL WHERE K_USUARIO_PEARL = 82

	SELECT * FROM [PPMS_PEARL].[dbo].[QC] WHERE Order_No = '50011' -- ID IN (303022)
	
	SELECT LEFT(LTRIM(RTRIM('WLK')), 3)
	
	SELECT * --COUNT(ID) AS DEFECTOS
	FROM [PPMS_PEARL].[dbo].rechazos 
	WHERE orden IN (	SELECT ORDEN
						FROM [PPMS_PEARL].DBO.[ORDEN_LIBERADA]  
						WHERE F_LIBERACION = '2022-04-23'
						AND K_TIPO_ORDEN_LIBERADA = 1 --ORDEN = 50011
						--AND MESA = 'Table 79'
						--AND F_LIBERACION = '2022-01-24'
					)
	AND DEFECTO = 'LD'

	SELECT * 
	FROM [PPMS_PEARL].DBO.[ORDEN_LIBERADA]  
	WHERE  K_TIPO_ORDEN_LIBERADA = 1 --#1 NORMAL #2 FICTICIA --oRDEN = 39330 
	--AND F_LIBERACION >= '2022-01-01'
	--AND F_LIBERACION <= '2022-01-25'
	--AND MESA = 'Table 28'
	ORDER BY F_LIBERACION DESC

	SELECT	MESA, 
			SUM(MUESTRA), 
			SUM(DEFECTOS),
			( CASE WHEN SUM(MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM [PPMS_PEARL].[dbo].[ORDEN_LIBERADA] (NOLOCK)
	WHERE F_LIBERACION >= @PP_F_INICIAL
	AND F_LIBERACION <= @PP_F_FIN
	--AND DEFECTOS > 0
	AND MESA = 'Table 28'

	SELECT * FROM DATA_02.dbo.pearl_log WHERE jobno = '48100' -- screen_opt = 'RECHAZOS'

	select * from DATA_02.[dbo].ccjoblin_sql where jobno = '52318' 
	select * from DATA_02.[dbo].ccjobhdr_sql where jobno = '52318' 

	select * from [PPMS_PEARL].[dbo].Perforacion where orden = '52318' AND noserie = '52318001' AND [status] = 'FINALIZADO'

	select * from [PPMS_PEARL].[dbo].Perforacion where noserie = '52736008'
	select * from [PPMS_PEARL].[dbo].certificacion_rpt where noserie_caja = '52736008' 

	-- RPMRUSBRMCKDX9,Q60-S52795001*174926D%MAGN03#RUE0028@68971
		SELECT * --TOP 1  D_KIT_RUTA_EVENTO
		FROM KIT_RUTA (NOLOCK)
		INNER JOIN KIT_RUTA_EVENTO (NOLOCK) ON KIT_RUTA_EVENTO.K_KIT_RUTA_EVENTO = KIT_RUTA.K_KIT_RUTA_EVENTO
		WHERE KIT_RUTA.ITEM_NO = 'PWSSFBRWSPAX7'
		AND KIT_RUTA.MODELNO = 'FW2'
		AND KIT_RUTA.VERSIONNO = '0011'

	-- RPWD2RC6CNPDX9,Q30-S52736008*187562B%MAGN03#WDM0020@109471           
		SELECT * --TOP 1  D_KIT_RUTA_EVENTO
		FROM KIT_RUTA (NOLOCK)
		INNER JOIN KIT_RUTA_EVENTO (NOLOCK) ON KIT_RUTA_EVENTO.K_KIT_RUTA_EVENTO = KIT_RUTA.K_KIT_RUTA_EVENTO
		WHERE KIT_RUTA.ITEM_NO = 'PWD2RC6CNPDX9'
		AND KIT_RUTA.MODELNO = 'WDM'
		AND KIT_RUTA.VERSIONNO = '0020'

		SELECT * FROM [PPMS_PEARL].[dbo].Perforacion WHERE noserie = '52847001'
		SELECT * FROM [PPMS_PEARL].[dbo].certificacion_rpt WHERE noserie_caja = '52847001'

		SELECT * FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) WHERE SERIAL = '52923006'  
		ESTACION = 'QCPERF-002' AND CONVERT(DATE, F_LOG) = CONVERT(DATE, GETDATE())  
		ORDER BY  [K_MATERIAL_PROGRAMADO_LOG] DESC

		--////////////MEZCLAR KITS A ORDEN DE PRODUCCION DE DIFERENTES COLORES/////////////////////////////////////////////////////////
		
SELECT * FROM [DATA_02].dbo.ccjoblin_sql WHERE JOBNO IN ( '51877', '51878') ORDER BY jobno, Ser_No

SELECT * FROM [DATA_02].dbo.ccjobhdr_sql WHERE JOBNO IN ( '51877', '51878')

--///////////////////////////////////////////////////////////////////////////////////////
	SELECT * FROM [PPMS_PEARL].[dbo].rechazos WHERE  fecha >= '20220216' AND mesa = ''

DECLARE @PP_F_INICIAL	DATE = '2022-03-03',
		@PP_F_FIN		DATE  = '2022-03-03'

SELECT		LTRIM(RTRIM(DEF.defecto)) AS DEFECTO,
			COUNT(ID) AS TOTAL_DEFECTO 
	FROM [PPMS_PEARL].DBO.Rechazos (NOLOCK)
	INNER JOIN [PPMS_PEARL].[dbo].DEF (NOLOCK) ON Rechazos.defecto = clave
	WHERE orden IN (	SELECT ORDEN 
						FROM [PPMS_PEARL].DBO.[ORDEN_LIBERADA]  (NOLOCK)
						WHERE  K_TIPO_ORDEN_LIBERADA = 1 --#1 NORMAL #2 FICTICIA --oRDEN = 39330 
						AND F_LIBERACION >= @PP_F_INICIAL
						AND F_LIBERACION <= @PP_F_FIN
					)
	--AND DEF.clave = 'DL'
	GROUP BY DEF.defecto
	ORDER BY COUNT(ID) DESC

--SELECT	LTRIM(RTRIM(MESA)) AS MESA,
--			LTRIM(RTRIM(DEF.defecto)) AS DEFECTO,
--			COUNT(ID) AS CANTIDAD 
--	FROM [PPMS_PEARL].DBO.Rechazos (NOLOCK)
--	INNER JOIN [PPMS_PEARL].[dbo].DEF (NOLOCK) ON Rechazos.defecto = clave
--	WHERE orden IN (	SELECT ORDEN 
--						FROM [PPMS_PEARL].DBO.[ORDEN_LIBERADA]  (NOLOCK)
--						WHERE  K_TIPO_ORDEN_LIBERADA = 1 --#1 NORMAL #2 FICTICIA --oRDEN = 39330 
--						AND F_LIBERACION >= @PP_F_INICIAL
--						AND F_LIBERACION <= @PP_F_FIN
--					)
--	AND ( CASE WHEN TURNO = 3 THEN 3
--				WHEN TURNO = 2 THEN 2
--				ELSE 1 END ) = 2
--	AND DEF.clave = 'LD'
--	--AND mesa NOT IN ('Table 90', 'Table 91')
--	GROUP BY MESA, DEF.defecto
--	ORDER BY COUNT(ID) DESC

	SELECT	(SELECT LTRIM(RTRIM(MACHINE)) FROM DATA_02.DBO.ccjobhdr_sql WHERE JOBNO = ORDEN ) AS MESA,
			[PPMS_PEARL].DBO.Rechazos.*,
			
			--LTRIM(RTRIM(MESA)) AS MESA,
			--LTRIM(RTRIM(DEF.defecto)) AS DEFECTO,
			--COUNT(ID) AS CANTIDAD 
			( SELECT LEFT(CHANGELEVEL, 3) FROM DATA_02.dbo.ccjoblin_sql WHERE CONCAT(LTRIM(RTRIM(ccjoblin_sql.jobno)) , RIGHT('000' + CONVERT(VARCHAR(5), ccjoblin_sql.Ser_No), 3)) = Rechazos.noserie) AS MODELO
	FROM [PPMS_PEARL].DBO.Rechazos (NOLOCK)
	INNER JOIN [PPMS_PEARL].[dbo].DEF (NOLOCK) ON Rechazos.defecto = clave
	WHERE orden IN (	SELECT ORDEN 
						FROM [PPMS_PEARL].DBO.[ORDEN_LIBERADA]  (NOLOCK)
						WHERE  K_TIPO_ORDEN_LIBERADA = 1 --#1 NORMAL #2 FICTICIA --oRDEN = 39330 
						AND F_LIBERACION >= @PP_F_INICIAL
						AND F_LIBERACION <= @PP_F_FIN
					)
	--AND ( CASE WHEN TURNO = 3 THEN 3
	--			WHEN TURNO = 2 THEN 2
	--			ELSE 1 END ) = 2
	AND DEF.clave = 'LD'
	--AND mesa NOT IN ('Table 90', 'Table 91')
	--GROUP BY MESA, DEF.defecto
	ORDER BY turno -- COUNT(ID) DESC

