
USE DATA_02Pruebas

SELECT * FROM [8D] WHERE K_8D = 1

--UPDATE [8D] 
--SET DATE_CLOSED = GETDATE(),
--	COMMENT = 'Gracias equipo!'
--WHERE K_8D = 1

select  CONVERT(VARCHAR(10),GETDATE(), 105) 

SELECT * FROM [EXTERNAL_8D]
							
SELECT * FROM [8D_ROOT_CAUSE]
SELECT * FROM [8D_ROOT_CAUSE_ISHIKAWA_EVIDENCE]

SELECT * FROM [8D_SYMPTOM]
SELECT * FROM [8D_SYMPTOM_ACTION] WHERE K_8D = 2
SELECT * FROM [8D_SYMPTOM_EVIDENCE]
SELECT * FROM [8D_TEAM]
SELECT * FROM [8D_ROOT_CAUSE]

SELECT  D_USUARIO_PEARL
			FROM	BD_GENERAL.dbo.USUARIO_PEARL (NOLOCK)
			INNER	JOIN [8D] (NOLOCK)  ON [8D].K_USUARIO_ALTA = USUARIO_PEARL.K_USUARIO_PEARL
			WHERE 	[K_8D] = 2 

SELECT  CORREO_USUARIO_PEARL
										FROM	BD_GENERAL.dbo.USUARIO_PEARL (NOLOCK)
										INNER	JOIN [8D] (NOLOCK)  ON [8D].K_USUARIO_ALTA = USUARIO_PEARL.K_USUARIO_PEARL
										WHERE 	[K_8D] = 2
										AND ( CORREO_USUARIO_PEARL <> '' OR CORREO_USUARIO_PEARL <> 'SIN CORREO' )

SELECT	EN_NUM_EMP,
		CONCAT('(', EN_NUM_EMP, ') ', LTRIM(RTRIM(EP_NOMBRE)), ' ', LTRIM(RTRIM(EP_APELLIDO_PATERNO)), ' (', LTRIM(RTRIM(DP_DESC_DEPTO)), ')' ) 
FROM HOWE.dbo.VISTA_GAFETES (NOLOCK)
WHERE EN_CLASE_EMP < 4
ORDER BY DP_DEPTO

SELECT	* FROM HOWE.dbo.VISTA_GAFETES (NOLOCK)

SELECT	* FROM BD_GENERAL.dbo.USUARIO_PEARL (NOLOCK)

SELECT  CONCAT('8D', FORMAT(GETDATE(),'MMddyy'), '-', '1' )

SELECT SUBSTRING('8D083121-1', 10, 3 )