
USE DATA_02Pruebas

SELECT * FROM [8D] WHERE K_8D = 2

--UPDATE [8D] 
--SET K_RMA = 5
--WHERE K_8D = 2

SELECT * FROM [EXTERNAL_8D]
							
SELECT	EN_NUM_EMP,
		CONCAT('(', EN_NUM_EMP, ') ', LTRIM(RTRIM(EP_NOMBRE)), ' ', LTRIM(RTRIM(EP_APELLIDO_PATERNO)), ' (', LTRIM(RTRIM(DP_DESC_DEPTO)), ')' ) 
FROM HOWE.dbo.VISTA_GAFETES (NOLOCK)
WHERE EN_CLASE_EMP < 4
ORDER BY DP_DEPTO
