
SELECT * FROM [8D]

SELECT * FROM [EXTERNAL_8D]
							
SELECT	EN_NUM_EMP,
		CONCAT('(', EN_NUM_EMP, ') ', LTRIM(RTRIM(EP_NOMBRE)), ' ', LTRIM(RTRIM(EP_APELLIDO_PATERNO)), ' (', LTRIM(RTRIM(DP_DESC_DEPTO)), ')' ) 
FROM HOWE.dbo.VISTA_GAFETES (NOLOCK)
WHERE EN_CLASE_EMP < 4
ORDER BY DP_DEPTO

SELECT	*
FROM HOWE.dbo.VISTA_GAFETES (NOLOCK)
WHERE EN_CLASE_EMP < 4
ORDER BY DP_DEPTO