-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[PPMS_PEARL]
-- // MODULO:			PPM & CERTIFICACION REPORT
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	22/SEP/2021
-- //////////////////////////////////////////////////////////////  

USE [PPMS_PEARL]
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////
--	USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_DIA_X_TURNO_X_HORA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_DIA_X_TURNO_X_HORA]
GO

/*
	EXEC	[dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_DIA_X_TURNO_X_HORA] 0, 144, '2021-11-09', 2
*/

CREATE PROCEDURE [dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_DIA_X_TURNO_X_HORA]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_FIN					DATE,
	@PP_TURNO					INT
AS
	
	-- //////SE CREA TABLA TEMPORAL//////////////////////////////////////
	DECLARE @TBL_MATERIAL_REVISADO_DIA TABLE(
	SELLO			VARCHAR(100),
	INSPECTOR		VARCHAR(100),
	MUESTRA			INT,
	DEFECTOS		INT
	)

	-- //////SE INGRESAN LOS DATOS A LA TABLA TEMPORAL//////////////////////////////////////
	INSERT INTO @TBL_MATERIAL_REVISADO_DIA
	SELECT	SELLO_PAQ	AS SELLO,
			INSPECTOR_CAL	AS INSPECTOR, 
			SUM(total)	AS REVISADAS,
			( SUM(cant1) + SUM(cant2) + SUM(cant3)) AS DEFECTOS
	FROM certificacion_rpt (NOLOCK)
	INNER JOIN personal (NOLOCK) ON sello = sello_paq
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND personal.turno = @PP_TURNO
	AND insp_certi <> '' 
	GROUP BY SELLO_PAQ, INSPECTOR_CAL

	-- //////SE CREA TABLA TEMPORAL//////////////////////////////////////
	DECLARE @TBL_MATERIAL_REVISADO_X_DIA_TOTAL TABLE(
	INSPECTOR				VARCHAR(100),
	TOTAL_MUESTRA			INT,
	TOTAL_DEFECTOS			INT,
	TOTAL_PPMS				INT
	)

	-- /////////SE CALCULAS LOS TOTALES Y SE MUESTRA EL RESULTADO//////////////
	INSERT INTO @TBL_MATERIAL_REVISADO_X_DIA_TOTAL
	SELECT	(	SELECT TOP 1 CONCAT((SUBSTRING( CONCAT(EP_NOMBRE, ' '), 1, CHARINDEX(' ', CONCAT(EP_NOMBRE, ' ')))), ' ' + EP_APELLIDO_PATERNO)
				FROM HOWE.DBO.VISTA_GAFETES (NOLOCK)
				INNER JOIN personal (NOLOCK) ON LTRIM(RTRIM(inspector_cal)) =  LTRIM(RTRIM(INSPECTOR)) AND EN_NUM_EMP = noreloj	) AS INSPECTOR,
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @TBL_MATERIAL_REVISADO_DIA

	-- /////////SE MUESTRA EL RESULTADO//////////////
	SELECT INSPECTOR,		
		   TOTAL_MUESTRA,	
		   TOTAL_DEFECTOS,	
		   TOTAL_PPMS		
	FROM @TBL_MATERIAL_REVISADO_X_DIA_TOTAL
	WHERE INSPECTOR IS NOT NULL
	ORDER BY TOTAL_PPMS DESC
	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_CERTIFICACION_REPORT_CONCENTRADO_X_HORA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_CERTIFICACION_REPORT_CONCENTRADO_X_HORA]
GO

/*
	EXEC	[dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_DIA_X_TURNO_X_HORA] 0, 144, '2021-11-09', 1
	EXEC	[dbo].[PG_LI_CERTIFICACION_REPORT_CONCENTRADO_X_HORA] 0,0, '2021-11-01', '2021-11-09'
	EXEC	[dbo].[PG_LI_CERTIFICACION_DEFECTO_ACUMULADO_X_DIA_TURNO] 0,0, '2021-11-09', 2
*/

CREATE PROCEDURE [dbo].[PG_LI_CERTIFICACION_REPORT_CONCENTRADO_X_HORA]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_F_INICIAL						DATE,
	@PP_F_FIN							DATE
AS
	-- /////////SE CREA TABLA TEMPORAL PARA CONCENTRADO POR HORA//////////////
	DECLARE @VP_TBL_CERTIFICACION_CONCENTRADO_X_HORA TABLE(
		TITULO_1	VARCHAR(50),
		TITULO_2	VARCHAR(50),
		TITULO_3	VARCHAR(50),
		TITULO_4	VARCHAR(50)
	)

	SET NOCOUNT ON

	INSERT INTO @VP_TBL_CERTIFICACION_CONCENTRADO_X_HORA
	SELECT 'Fecha', 'Total Muestra', 'Suma Defectos', 'PPMS'

	-- /////////SE CREA TABLA TEMPORAL PARA LOS DATOS DE CERTIFICACION//////////////
	DECLARE @VP_TBL_CERTIFICACION TABLE(
		FECHA		DATE,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INSERTAN LOS DATOS A LA TABLA//////////////
	INSERT INTO @VP_TBL_CERTIFICACION
	SELECT	CONVERT(DATE, fecha) AS 'FECHA', 
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1)+ SUM(cant2)+ SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt (NOLOCK)
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	GROUP BY CONVERT(DATE, fecha)

	-- /////////SE CALCULAS LOS TOTALES//////////////
	INSERT INTO @VP_TBL_CERTIFICACION_CONCENTRADO_X_HORA
	SELECT	FECHA, 
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_CERTIFICACION
	--WHERE DEFECTOS > 0
	ORDER BY FECHA
	
	-- /////////SE INSERTAN LOS DATOS A LA TABLA//////////////
	DELETE @VP_TBL_CERTIFICACION

	INSERT INTO @VP_TBL_CERTIFICACION
	SELECT	CONVERT(DATE, fecha) AS 'FECHA', 
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1)+ SUM(cant2)+ SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt (NOLOCK)
	INNER JOIN personal (NOLOCK) ON sello = sello_paq
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND personal.turno = 1
	GROUP BY CONVERT(DATE, fecha)


	-- /////////SE CALCULAS LOS TOTALES//////////////
	INSERT INTO @VP_TBL_CERTIFICACION_CONCENTRADO_X_HORA
	SELECT 'Turno', 'Total Muestra', 'Suma Defectos', 'PPMS'

	INSERT INTO @VP_TBL_CERTIFICACION_CONCENTRADO_X_HORA
	SELECT	'1', 
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_CERTIFICACION
	ORDER BY FECHA

	-- /////////SE INSERTAN LOS DATOS A LA TABLA//////////////
	DELETE @VP_TBL_CERTIFICACION

	INSERT INTO @VP_TBL_CERTIFICACION
	SELECT	CONVERT(DATE, fecha) AS 'FECHA', 
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1)+ SUM(cant2)+ SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt (NOLOCK)
	INNER JOIN personal (NOLOCK) ON sello = sello_paq
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND personal.turno = 2
	GROUP BY CONVERT(DATE, fecha)


	-- /////////SE CALCULAS LOS TOTALES//////////////
	INSERT INTO @VP_TBL_CERTIFICACION_CONCENTRADO_X_HORA
	SELECT	'2', 
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_CERTIFICACION
	ORDER BY FECHA

	-- /////////SE INSERTAN LOS DATOS A LA TABLA//////////////
	DELETE @VP_TBL_CERTIFICACION

	INSERT INTO @VP_TBL_CERTIFICACION
	SELECT	CONVERT(DATE, fecha) AS 'FECHA', 
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1)+ SUM(cant2)+ SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt (NOLOCK)
	INNER JOIN personal (NOLOCK) ON sello = sello_paq
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND personal.turno = 3
	GROUP BY CONVERT(DATE, fecha)


	-- /////////SE CALCULAS LOS TOTALES//////////////
	INSERT INTO @VP_TBL_CERTIFICACION_CONCENTRADO_X_HORA
	SELECT	'3', 
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_CERTIFICACION
	ORDER BY FECHA

	SET NOCOUNT OFF

	SELECT * FROM @VP_TBL_CERTIFICACION_CONCENTRADO_X_HORA
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
