-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	[PPMS_PEARL]
-- // MODULO:			PPM & CERTIFICACION REPORT
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			FEG
-- // Fecha creación:	22/SEP/2021
-- //////////////////////////////////////////////////////////////  

USE [PPMS_PEARL]
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA]
GO

/*
 EXEC	[dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA] 0,0, '2021-09-01', '2021-09-13'
*/

CREATE PROCEDURE [dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_F_INICIAL						DATE,
	@PP_F_FIN							DATE
AS

	-- /////////SE CREA TABLA TEMPORAL PARA LOS DATOS DE CERTIFICACION//////////////
	DECLARE @VP_TBL_CERTIFICACION TABLE(
		FECHA		DATE,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INSERTAN LOS DATOS A LA TABLA//////////////
	INSERT INTO @VP_TBL_CERTIFICACION
	SELECT	CONVERT(DATE, fecha) AS 'FECHA', 
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1)+ SUM(cant2)+ SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt (NOLOCK)
	WHERE CONVERT(DATE, fecha) >= @PP_F_INICIAL
	AND CONVERT(DATE, fecha) <= @PP_F_FIN
	GROUP BY CONVERT(DATE, fecha)

	-- /////////SE CALCULAS LOS TOTALES//////////////
	SELECT	FECHA, 
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_CERTIFICACION
	WHERE DEFECTOS > 0
	ORDER BY FECHA
	
	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA_TURNO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA_TURNO]
GO

/*
 EXEC	[dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA_TURNO] 0,0, '2021-10-01', '2021-10-13', 3
*/

CREATE PROCEDURE [dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA_TURNO]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_F_INICIAL						DATE,
	@PP_F_FIN							DATE,
	@VP_TURNO							INT
AS

	-- /////////SE CREA TABLA TEMPORAL PARA LOS DATOS DE CERTIFICACION//////////////
	DECLARE @VP_TBL_CERTIFICACION TABLE(
		FECHA		DATE,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INSERTAN LOS DATOS A LA TABLA//////////////
	INSERT INTO @VP_TBL_CERTIFICACION
	SELECT	CONVERT(DATE, fecha) AS 'FECHA', 
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1)+ SUM(cant2)+ SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt (NOLOCK)
	WHERE CONVERT(DATE, fecha) >= @PP_F_INICIAL
	AND CONVERT(DATE, fecha) <= @PP_F_FIN
	AND turno = @VP_TURNO
	GROUP BY CONVERT(DATE, fecha)

	-- /////////SE CALCULAS LOS TOTALES//////////////
	SELECT	FECHA, MUESTRA AS 'TOTAL_MUESTRA', DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_CERTIFICACION
	WHERE DEFECTOS > 0
	ORDER BY FECHA

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA_TURNO_GRAF]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA_TURNO_GRAF]
GO

/*
 EXEC	[dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA_TURNO_GRAF] 0,0, '2021-09-01', '2021-09-13'
*/

CREATE PROCEDURE [dbo].[PG_LI_CERTIFICACION_REPORT_X_FECHA_TURNO_GRAF]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_F_INICIAL						DATE,
	@PP_F_FIN							DATE
AS

	-- /////////SE CREA TABLA TEMPORAL PARA LOS DATOS DE CERTIFICACION//////////////
	DECLARE @VP_TBL_CERTIFICACION TABLE(
		FECHA		DATE,
		TURNO		INT,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INSERTAN LOS DATOS A LA TABLA//////////////
	INSERT INTO @VP_TBL_CERTIFICACION
	SELECT	CONVERT(DATE, fecha) AS 'FECHA', 
			TURNO AS TURNO,
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1)+ SUM(cant2)+ SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt (NOLOCK)
	WHERE CONVERT(DATE, fecha) >= @PP_F_INICIAL
	AND CONVERT(DATE, fecha) <= @PP_F_FIN
	GROUP BY CONVERT(DATE, fecha), turno

	-- /////////SE CREA TABLA TEMPORAL PARA LOS DATOS DE CERTIFICACION//////////////
	DECLARE @VP_TBL_CERTIFICACION_TOTALES TABLE(
		FECHA			DATE,
		PPMS_1ER_TURNO	INT,
		PPMS_2DO_TURNO	INT,
		PPMS_3ER_TURNO	INT
	)

	-- /////////SE CALCULAS LOS TOTALES Y SE INGRESA A LA TABLA TEMPORAL DE TOTALES POR TURNO//////////////
	INSERT INTO @VP_TBL_CERTIFICACION_TOTALES
	SELECT	FECHA, 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'PPMS 1ER TURNO',
			0,
			0
	FROM @VP_TBL_CERTIFICACION
	WHERE DEFECTOS > 0
	AND TURNO = 1
	ORDER BY FECHA

	INSERT INTO @VP_TBL_CERTIFICACION_TOTALES
	SELECT	FECHA, 
			0,
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'PPMS 2DO TURNO',
			0
	FROM @VP_TBL_CERTIFICACION
	WHERE DEFECTOS > 0
	AND TURNO = 2
	ORDER BY FECHA

	INSERT INTO @VP_TBL_CERTIFICACION_TOTALES
	SELECT	FECHA, 
			0,
			0,
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'PPMS 3ER TURNO'
	FROM @VP_TBL_CERTIFICACION
	WHERE DEFECTOS > 0
	AND TURNO = 3
	ORDER BY FECHA

	-- /////////SE MUESTRA EL RESULTADO//////////////
	SELECT	FECHA, 
			SUM(PPMS_1ER_TURNO) AS 'PPMS 1ER TURNO',
			SUM(PPMS_2DO_TURNO) AS 'PPMS 2DO TURNO',
			SUM(PPMS_3ER_TURNO) AS 'PPMS 3ER TURNO'
	FROM @VP_TBL_CERTIFICACION_TOTALES
	GROUP BY FECHA

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_CERTIFICACION_REPORT_X_MES]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_CERTIFICACION_REPORT_X_MES]
GO

/*
 EXEC	[dbo].[PG_LI_CERTIFICACION_REPORT_X_MES] 0,0, '2021-09-13'
*/

CREATE PROCEDURE [dbo].[PG_LI_CERTIFICACION_REPORT_X_MES]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_F_FIN							DATE
AS

-- /////////SE BNTIENE EL AÑO DE LA FECHA INICIAL///////////////////////////////////////
DECLARE @VP_YEAR INT = YEAR(@PP_F_FIN)

-- /////////SE CREA TABLA TEMPORAL PARA GUARDAR LOS DATOS///////////////////////////////////////
DECLARE @VP_TBL_CERTIFICACION_X_MES TABLE(
		MES			INT,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	INSERT INTO @VP_TBL_CERTIFICACION_X_MES
	SELECT	FORMAT(CONVERT(DATE, fecha), 'MM') AS 'MES', 
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1) + SUM(cant2) + SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt (NOLOCK)
	WHERE YEAR(CONVERT(DATE, fecha)) = @VP_YEAR
	GROUP BY FORMAT(CONVERT(DATE, fecha), 'MM')

	SELECT	( CASE	WHEN MES = 1 THEN 'Enero'
					WHEN MES = 2 THEN 'Febrero'
					WHEN MES = 3 THEN 'Marzo'
					WHEN MES = 4 THEN 'Abril'
					WHEN MES = 5 THEN 'Mayo'
					WHEN MES = 6 THEN 'Junio'
					WHEN MES = 7 THEN 'Julio'
					WHEN MES = 8 THEN 'Agosto'
					WHEN MES = 9 THEN 'Septiembre'
					WHEN MES = 10 THEN 'Octubre'
					WHEN MES = 11 THEN 'Noviembre'
					WHEN MES = 12 THEN 'Diciembre' END ) NOMBRE_MES,
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_CERTIFICACION_X_MES
	WHERE DEFECTOS > 0
	ORDER BY MES

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_CERTIFICACION_DEFECTO_X_DIA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_CERTIFICACION_DEFECTO_X_DIA]
GO

/*
 EXEC	[dbo].[PG_LI_CERTIFICACION_DEFECTO_X_DIA] 0,0, '2021-09-13'
*/

CREATE PROCEDURE [dbo].[PG_LI_CERTIFICACION_DEFECTO_X_DIA]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_F_FIN							DATE
AS
	
	-- /////////SE CREA TABLA TEMPORAL PARA GUARDAR LOS DATOS///////////////////////////////////////
	DECLARE @VP_TBL_CERTIFICACION_DEFECTO TABLE(
		DEFECTO		VARCHAR(50),
		CANTIDAD	INT
	)

	-- /////////SE INGRESAN LOS DATOS A LA TABLA///////////////////////////////////////
	INSERT INTO @VP_TBL_CERTIFICACION_DEFECTO
	SELECT defecto1, SUM(cant1)
	FROM certificacion_rpt (NOLOCK)
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND defecto1 <> ''
	GROUP BY defecto1

	-- /////////SE INGRESAN LOS DATOS A LA TABLA///////////////////////////////////////
	INSERT INTO @VP_TBL_CERTIFICACION_DEFECTO
	SELECT defecto2, SUM(cant2)
	FROM certificacion_rpt (NOLOCK)
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND defecto2 <> ''
	GROUP BY defecto2

	-- /////////SE INGRESAN LOS DATOS A LA TABLA///////////////////////////////////////
	INSERT INTO @VP_TBL_CERTIFICACION_DEFECTO
	SELECT defecto3, SUM(cant3)
	FROM certificacion_rpt (NOLOCK)
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND defecto3 <> ''
	GROUP BY defecto3

	-- /////////SE MUESTRAN LOS DATOS///////////////////////////////////////
	SELECT 	--TOP 5 
			DEF.DEFECTO, SUM(CANTIDAD) AS CANTIDAD
	FROM @VP_TBL_CERTIFICACION_DEFECTO AS CERTI_DEF
	INNER JOIN def (NOLOCK) ON DEF.CLAVE = CERTI_DEF.DEFECTO
	GROUP BY DEF.DEFECTO
	ORDER BY SUM(CANTIDAD) DESC

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_CERTIFICACION_DEFECTO_ACUMULADO_X_DIA_TURNO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_CERTIFICACION_DEFECTO_ACUMULADO_X_DIA_TURNO]
GO

/*
 EXEC	[dbo].[PG_LI_CERTIFICACION_DEFECTO_ACUMULADO_X_DIA_TURNO] 0,0, '2021-09-13', 1
*/

CREATE PROCEDURE [dbo].[PG_LI_CERTIFICACION_DEFECTO_ACUMULADO_X_DIA_TURNO]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_F_FIN							DATE,
	@PP_TURNO							INT
AS
	
	-- /////////SE CREA TABLA TEMPORAL PARA GUARDAR LOS DATOS///////////////////////////////////////
	DECLARE @VP_TBL_CERTIFICACION_DEFECTO TABLE(
		SELLO		VARCHAR(20),
		INSPECTOR	VARCHAR(255),
		DEFECTO		VARCHAR(50),
		CANTIDAD	INT
	)

	--CREATE TABLE #CERTIFICACION_DEFECTO_ACUMULADO(
	--	SELLO		VARCHAR(20),
	--	INSPECTOR	VARCHAR(255),
	--	DEFECTO		VARCHAR(50),
	--	CANTIDAD	INT
	--)

	-- /////////SE INGRESAN LOS DATOS A LA TABLA///////////////////////////////////////
	INSERT INTO @VP_TBL_CERTIFICACION_DEFECTO
	SELECT	SELLO_PAQ		AS SELLO,
			INSPECTOR_CAL	AS INSPECTOR, 
			DEFECTO,
			( SUM(cant1)) AS DEFECTOS
	FROM certificacion_rpt (NOLOCK)
	INNER JOIN personal (NOLOCK) ON sello = sello_paq
	INNER JOIN def (NOLOCK) ON DEF.CLAVE = certificacion_rpt.defecto1
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND personal.turno = @PP_TURNO
	AND insp_certi <> '' 
	GROUP BY SELLO_PAQ, INSPECTOR_CAL, DEFECTO
	HAVING  SUM(cant1)   > 0

	-- /////////SE INGRESAN LOS DATOS A LA TABLA///////////////////////////////////////
	INSERT INTO @VP_TBL_CERTIFICACION_DEFECTO
	SELECT	SELLO_PAQ	AS SELLO,
			INSPECTOR_CAL	AS INSPECTOR, 
			DEFECTO,
			( SUM(cant2)) AS DEFECTOS
	FROM certificacion_rpt (NOLOCK)
	INNER JOIN personal (NOLOCK) ON sello = sello_paq
	INNER JOIN def (NOLOCK) ON DEF.CLAVE = certificacion_rpt.defecto2
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND personal.turno = @PP_TURNO
	AND insp_certi <> '' 
	GROUP BY SELLO_PAQ, INSPECTOR_CAL, DEFECTO
	HAVING  SUM(cant2)   > 0
	
	-- /////////SE INGRESAN LOS DATOS A LA TABLA///////////////////////////////////////
	INSERT INTO @VP_TBL_CERTIFICACION_DEFECTO
	SELECT	SELLO_PAQ	AS SELLO,
			INSPECTOR_CAL	AS INSPECTOR, 
			DEFECTO,
			( SUM(cant3)) AS DEFECTOS
	FROM certificacion_rpt (NOLOCK)
	INNER JOIN personal (NOLOCK) ON sello = sello_paq
	INNER JOIN def (NOLOCK) ON DEF.CLAVE = certificacion_rpt.defecto3
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND personal.turno = @PP_TURNO
	AND insp_certi <> '' 
	GROUP BY SELLO_PAQ, INSPECTOR_CAL, DEFECTO
	HAVING  SUM(cant2)   > 0

	-- /////////SE MUESTRAN LOS DATOS///////////////////////////////////////
	SELECT 	CERTI_DEF.SELLO,
			CONCAT((SUBSTRING( CONCAT(EP_NOMBRE, ' '), 1, CHARINDEX(' ', CONCAT(EP_NOMBRE, ' ')))), ' ' + EP_APELLIDO_PATERNO) AS INSPECTOR,		
			--INSPECTOR,	
			DEFECTO,	
			CANTIDAD	
	FROM @VP_TBL_CERTIFICACION_DEFECTO AS CERTI_DEF
	INNER JOIN personal (NOLOCK) ON personal.sello =  CERTI_DEF.SELLO
	INNER JOIN HOWE.DBO.VISTA_GAFETES (NOLOCK) ON EN_NUM_EMP = noreloj
	ORDER BY INSPECTOR

	-- ////////////////////SE OBTIENEN LOS DEFECTOS EN FORMA DE COLUMNAS//////////////////////////	
	--DECLARE @VP_COLUMNA_DEFECTO NVARCHAR(MAX) = '', @VP_QUERY AS NVARCHAR(MAX) = ''
	--SELECT @VP_COLUMNA_DEFECTO = STUFF(( SELECT ',' + QUOTENAME(DEFECTO) 
	--						FROM #CERTIFICACION_DEFECTO_ACUMULADO 
	--						GROUP BY DEFECTO
	--						ORDER BY DEFECTO
	--						FOR XML PATH(''), TYPE ).value('.', 'NVARCHAR(MAX)') ,1, 1,'' ) 									 										 			
								 			
	--SET @VP_QUERY = N'SELECT SELLO, INSPECTOR, ' + @VP_COLUMNA_DEFECTO + N' into [tempdb].[dbo].[CERTIFICACION_DEFECTO_ACUMULADO_PIVOT]  from ( SELECT SELLO, INSPECTOR, CANTIDAD, DEFECTO from #CERTIFICACION_DEFECTO_ACUMULADO ) x pivot ( SUM(CANTIDAD) for DEFECTO in (' + @VP_COLUMNA_DEFECTO + N') ) p ' 
	--EXEC sp_executesql @VP_QUERY;	

	--SELECT * FROM [tempdb].[dbo].CERTIFICACION_DEFECTO_ACUMULADO_PIVOT

	--SET NOCOUNT ON
	--DROP TABLE #CERTIFICACION_DEFECTO_ACUMULADO
	--DROP TABLE [tempdb].[dbo].[CERTIFICACION_DEFECTO_ACUMULADO_PIVOT]

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////
-- USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_CERTIFICACION_DEFECTO_X_MES]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_CERTIFICACION_DEFECTO_X_MES]
GO

/*
 EXEC	[dbo].[PG_LI_CERTIFICACION_DEFECTO_X_MES] 0,0, '2021-09-13'
*/

CREATE PROCEDURE [dbo].[PG_LI_CERTIFICACION_DEFECTO_X_MES]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_F_FIN							DATE
AS
	
	-- /////////SE BNTIENE EL AÑO DE LA FECHA INICIAL///////////////////////////////////////
	DECLARE @VP_YEAR INT = YEAR(@PP_F_FIN)
	DECLARE @VP_MES INT = MONTH(@PP_F_FIN)
	
	-- /////////SE CREA TABLA TEMPORAL PARA GUARDAR LOS DATOS///////////////////////////////////////
	DECLARE @VP_TBL_CERTIFICACION_DEFECTO_X_MES TABLE(
		DEFECTO		VARCHAR(50),
		CANTIDAD	INT
	)

	-- /////////SE INGRESAN LOS DATOS A LA TABLA///////////////////////////////////////
	INSERT INTO @VP_TBL_CERTIFICACION_DEFECTO_X_MES
	SELECT defecto1, SUM(cant1)
	FROM certificacion_rpt (NOLOCK)
	WHERE YEAR(CONVERT(DATE, fecha)) = @VP_YEAR
	AND MONTH(CONVERT(DATE, fecha)) = @VP_MES
	AND defecto1 <> ''
	GROUP BY defecto1

	-- /////////SE INGRESAN LOS DATOS A LA TABLA///////////////////////////////////////
	INSERT INTO @VP_TBL_CERTIFICACION_DEFECTO_X_MES
	SELECT defecto2, SUM(cant2)
	FROM certificacion_rpt (NOLOCK)
	WHERE YEAR(CONVERT(DATE, fecha)) = @VP_YEAR
	AND MONTH(CONVERT(DATE, fecha)) = @VP_MES
	AND defecto2 <> ''
	GROUP BY defecto2

	-- /////////SE INGRESAN LOS DATOS A LA TABLA///////////////////////////////////////
	INSERT INTO @VP_TBL_CERTIFICACION_DEFECTO_X_MES
	SELECT defecto3, SUM(cant3)
	FROM certificacion_rpt (NOLOCK)
	WHERE YEAR(CONVERT(DATE, fecha)) = @VP_YEAR
	AND MONTH(CONVERT(DATE, fecha)) = @VP_MES
	AND defecto3 <> ''
	GROUP BY defecto3

	-- /////////SE MUESTRAN LOS DATOS///////////////////////////////////////
	SELECT --TOP 5 
			DEF.DEFECTO, SUM(CANTIDAD) AS CANTIDAD
	FROM @VP_TBL_CERTIFICACION_DEFECTO_X_MES AS CERTI_DEF
	INNER JOIN def (NOLOCK) ON DEF.CLAVE = CERTI_DEF.DEFECTO
	GROUP BY DEF.DEFECTO
	ORDER BY SUM(CANTIDAD) DESC

	-- ////////////////////////////////////////////////
	-- ////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////
-- USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_PPMS_REPORT_X_FECHA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_PPMS_REPORT_X_FECHA]
GO

/*
	EXEC	[dbo].[PG_LI_PPMS_REPORT_X_FECHA] 0, 144, '2021-09-01', '2021-09-13'
*/

CREATE PROCEDURE [dbo].[PG_LI_PPMS_REPORT_X_FECHA]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_INICIAL				DATE,
	@PP_F_FIN					DATE
AS
	
	-- /////////SE CREA LA TABLA PARA LOS PPMS//////////////
	DECLARE @VP_TBL_PPMS TABLE(
		FECHA		DATE,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INGRESAN LOS DATOS A LA TABLA PPMS//////////////
	INSERT INTO @VP_TBL_PPMS
	SELECT	CONVERT(DATE, Date) AS FECHA, 
			SAMPLE_SIZE, 
			ISNULL((SELECT SUM([DEFECTOS].Cant)  FROM [PPMS_PEARL].[dbo].[DEFECTOS] (NOLOCK) WHERE [DEFECTOS].ID = [QC].ID), 0)
	FROM [PPMS_PEARL].[dbo].[QC] (NOLOCK)
	WHERE [Date] >= @PP_F_INICIAL
	AND [Date] <= @PP_F_FIN
	ORDER BY CONVERT(DATE, [Date])
	
	-- /////////SE CALCULAN LOS TOTALES//////////////
	SELECT	FECHA, 
			SUM(MUESTRA) AS 'TOTAL_MUESTRA', 
			SUM(DEFECTOS) AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (SUM(MUESTRA)) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_PPMS
	GROUP BY FECHA
	HAVING SUM(DEFECTOS) > 0
	ORDER BY FECHA


	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////
-- USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_PPMS_REPORT_X_MES]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_PPMS_REPORT_X_MES]
GO

/*
	EXEC	[dbo].[PG_LI_PPMS_REPORT_X_MES] 0, 144, '2021-09-13'
*/

CREATE PROCEDURE [dbo].[PG_LI_PPMS_REPORT_X_MES]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_FIN					DATE
AS
	
	-- /////////SE BNTIENE EL AÑO DE LA FECHA INICIAL///////////////////////////////////////
	DECLARE @VP_YEAR INT = YEAR(@PP_F_FIN)

	-- /////////SE CREA LA TABLA PARA LOS PPMS//////////////
	DECLARE @VP_TBL_PPMS_X_MES TABLE(
		MES			INT,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INGRESAN LOS DATOS A LA TABLA PPMS//////////////
	INSERT INTO @VP_TBL_PPMS_X_MES
	SELECT	FORMAT([Date], 'MM') AS MES, 
			SAMPLE_SIZE, 
			ISNULL((SELECT SUM([DEFECTOS].Cant)  FROM [PPMS_PEARL].[dbo].[DEFECTOS] (NOLOCK)  WHERE [DEFECTOS].ID = [QC].ID), 0)
	FROM [PPMS_PEARL].[dbo].[QC] (NOLOCK)
	WHERE YEAR([Date]) = @VP_YEAR 	
	
	-- /////////SE CALCULAN LOS TOTALES//////////////
	SELECT	( CASE	WHEN MES = 1 THEN 'Enero'
					WHEN MES = 2 THEN 'Febrero'
					WHEN MES = 3 THEN 'Marzo'
					WHEN MES = 4 THEN 'Abril'
					WHEN MES = 5 THEN 'Mayo'
					WHEN MES = 6 THEN 'Junio'
					WHEN MES = 7 THEN 'Julio'
					WHEN MES = 8 THEN 'Agosto'
					WHEN MES = 9 THEN 'Septiembre'
					WHEN MES = 10 THEN 'Octubre'
					WHEN MES = 11 THEN 'Noviembre'
					WHEN MES = 12 THEN 'Diciembre' END ) NOMBRE_MES, 
			SUM(MUESTRA) AS 'TOTAL_MUESTRA', 
			SUM(DEFECTOS) AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (SUM(MUESTRA)) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_PPMS_X_MES
	GROUP BY MES
	HAVING SUM(DEFECTOS) > 0
	ORDER BY MES
	
	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT_X_FECHA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT_X_FECHA]
GO

/*	USE [PPMS_PEARL]
	EXEC	[dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT_X_FECHA] 0, 144, '2021-09-01', '2021-09-24'
*/

CREATE PROCEDURE [dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT_X_FECHA]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_INICIAL				DATE,
	@PP_F_FIN					DATE
AS
	-- /////////SE CREA TABLA TEMPORAL PARA LOS TOTALES//////////////
	DECLARE @VP_TBL_PPMS_CERTIFICACION_TOTAL TABLE(
		FECHA					DATE,
		MUESTRA					INT,
		DEFECTOS				INT,
		PPMS_CERTIFICACION		INT,
		PPMS_PRODUCCION			INT
	)

	-- /////////SE CREA TABLA TEMPORAL PARA LOS DATOS DE CERTIFICACION//////////////
	DECLARE @VP_TBL_CERTIFICACION TABLE(
		FECHA		DATE,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INSERTAN LOS DATOS A LA TABLA//////////////
	INSERT INTO @VP_TBL_CERTIFICACION
	SELECT	CONVERT(DATE, fecha) AS 'FECHA', 
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1)+ SUM(cant2)+ SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt 
	WHERE CONVERT(DATE, fecha) >= @PP_F_INICIAL
	AND CONVERT(DATE, fecha) <= @PP_F_FIN
	GROUP BY CONVERT(DATE, fecha)

	-- /////////SE CALCULAS LOS TOTALES//////////////
	INSERT INTO @VP_TBL_PPMS_CERTIFICACION_TOTAL
	SELECT	FECHA, 
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS',
			0
	FROM @VP_TBL_CERTIFICACION
	WHERE DEFECTOS > 0
	ORDER BY FECHA

	-- /////////SE CREA TABLA PARA PPMS//////////////
	DECLARE @VP_TBL_PPMS TABLE(
		FECHA		DATE,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INGRESAN LOS DATOS A LA TABLA @VP_TBL_PPMS//////////////
	INSERT INTO @VP_TBL_PPMS
	SELECT	CONVERT(DATE, Date) AS FECHA, 
			SAMPLE_SIZE, 
			ISNULL((SELECT SUM([DEFECTOS].Cant)  FROM [PPMS_PEARL].[dbo].[DEFECTOS] (NOLOCK) WHERE [DEFECTOS].ID = [QC].ID), 0)
	FROM [PPMS_PEARL].[dbo].[QC] 
	WHERE [Date] >= @PP_F_INICIAL
	AND [Date] <= @PP_F_FIN
	ORDER BY CONVERT(DATE, [Date])
	
	-- /////////SE INGRESAN LOS DATOS DE PPMS//////////////
	INSERT INTO @VP_TBL_PPMS_CERTIFICACION_TOTAL
	SELECT	FECHA, 
			SUM(MUESTRA) AS 'TOTAL_MUESTRA', 
			SUM(DEFECTOS) AS 'TOTAL_DEFECTOS', 
			0,
			( CASE WHEN (SUM(MUESTRA)) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_PPMS
	GROUP BY FECHA
	HAVING SUM(DEFECTOS) > 0
	ORDER BY FECHA

	-- /////////SE MUESTRA EL RESULTADO//////////////
	SELECT	FECHA, 
			SUM(MUESTRA) AS 'TOTAL_MUESTRA', 
			SUM(DEFECTOS) AS 'TOTAL_DEFECTOS' ,
			( CASE WHEN (SUM(MUESTRA)) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS',
			CONVERT(DECIMAL(13,2), (SUM(PPMS_CERTIFICACION)) / (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000)) AS 'PORCENJATE_QC'
	FROM @VP_TBL_PPMS_CERTIFICACION_TOTAL
	GROUP BY FECHA
	HAVING SUM(DEFECTOS) > 0
	ORDER BY FECHA

	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO



IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT_X_MES]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT_X_MES]
GO

/*	USE [PPMS_PEARL]
	EXEC	[dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT_X_MES] 0, 144, '2021-09-13'
*/

CREATE PROCEDURE [dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT_X_MES]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_FIN					DATE
AS
	-- /////////SE CREA TABLA TEMPORAL PARA LOS TOTALES//////////////
	DECLARE @VP_TBL_PPMS_CERTIFICACION_TOTAL_X_MES TABLE(
		MES							INT,
		MUESTRA_CERTIFICACION		INT,
		DEFECTOS_CERTIFICACION		INT,
		PPMS_CERTIFICACION			INT,
		MUESTRA_PRODUCCION			INT,
		DEFECTOS_PRODUCCION			INT,
		PPMS_PRODUCCION				INT
	)
		
	-- /////////SE BNTIENE EL AÑO DE LA FECHA INICIAL///////////////////////////////////////
	DECLARE @VP_YEAR INT = YEAR(@PP_F_FIN)
	
	-- /////////SE CREA TABLA TEMPORAL PARA GUARDAR LOS DATOS///////////////////////////////////////
	DECLARE @VP_TBL_CERTIFICACION_X_MES TABLE(
		MES			INT,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	INSERT INTO @VP_TBL_CERTIFICACION_X_MES
	SELECT	FORMAT(CONVERT(DATE, fecha), 'MM') AS 'MES', 
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1) + SUM(cant2) + SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt 
	WHERE YEAR(CONVERT(DATE, fecha)) = @VP_YEAR
	GROUP BY FORMAT(CONVERT(DATE, fecha), 'MM')

	INSERT INTO @VP_TBL_PPMS_CERTIFICACION_TOTAL_X_MES
	SELECT	MES,
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS',
			0,
			0,
			0
	FROM @VP_TBL_CERTIFICACION_X_MES
	WHERE DEFECTOS > 0

	-- /////////SE CREA LA TABLA PARA LOS PPMS//////////////
	DECLARE @VP_TBL_PPMS_X_MES TABLE(
		MES			INT,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INGRESAN LOS DATOS A LA TABLA PPMS//////////////
	INSERT INTO @VP_TBL_PPMS_X_MES
	SELECT	FORMAT([Date], 'MM') AS MES, 
			SAMPLE_SIZE, 
			ISNULL((SELECT SUM([DEFECTOS].Cant)  FROM [PPMS_PEARL].[dbo].[DEFECTOS] (NOLOCK)  WHERE [DEFECTOS].ID = [QC].ID), 0)
	FROM [PPMS_PEARL].[dbo].[QC] (NOLOCK)
	WHERE YEAR([Date]) = @VP_YEAR 	
	
	-- /////////SE CALCULAN LOS TOTALES//////////////
	INSERT INTO @VP_TBL_PPMS_CERTIFICACION_TOTAL_X_MES
	SELECT	MES, 
			0,
			0,
			0,
			SUM(MUESTRA) AS 'TOTAL_MUESTRA', 
			SUM(DEFECTOS) AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (SUM(MUESTRA)) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_PPMS_X_MES
	GROUP BY MES
	HAVING SUM(DEFECTOS) > 0

	-- /////////SE MUESTRA EL RESULTADO//////////////
	SELECT	( CASE	WHEN MES = 1 THEN 'Enero'
					WHEN MES = 2 THEN 'Febrero'
					WHEN MES = 3 THEN 'Marzo'
					WHEN MES = 4 THEN 'Abril'
					WHEN MES = 5 THEN 'Mayo'
					WHEN MES = 6 THEN 'Junio'
					WHEN MES = 7 THEN 'Julio'
					WHEN MES = 8 THEN 'Agosto'
					WHEN MES = 9 THEN 'Septiembre'
					WHEN MES = 10 THEN 'Octubre'
					WHEN MES = 11 THEN 'Noviembre'
					WHEN MES = 12 THEN 'Diciembre' END ) NOMBRE_MES, 
			SUM(MUESTRA_CERTIFICACION)	AS 'MUESTRA_CERTIFICACION', 
			SUM(DEFECTOS_CERTIFICACION)	AS 'DEFECTOS_CERTIFICACION' ,
			( CASE WHEN (SUM(MUESTRA_CERTIFICACION)) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), SUM(DEFECTOS_CERTIFICACION)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA_CERTIFICACION)) * 1000000) )
				ELSE 0 END ) AS 'PPMS_CERTIFICACION',
			--==========================================================
			SUM(MUESTRA_PRODUCCION)	AS 'MUESTRA_PRODUCCION', 
			SUM(DEFECTOS_PRODUCCION)	AS 'DEFECTOS_PRODUCCION',
			( CASE WHEN (SUM(MUESTRA_PRODUCCION)) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), SUM(DEFECTOS_PRODUCCION)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA_PRODUCCION)) * 1000000) )
				ELSE 0 END ) AS 'PPMS_PRODUCCION',
			--==========================================================
			CONVERT(DECIMAL(13,2),  ( SUM(PPMS_CERTIFICACION) 
									/ ( CONVERT(DECIMAL(13,2), ( SUM(DEFECTOS_CERTIFICACION) +  SUM(DEFECTOS_PRODUCCION)  ) ) 
										/ 
										CONVERT(DECIMAL(13,2), ( SUM(MUESTRA_CERTIFICACION) + SUM(MUESTRA_PRODUCCION) ) ) 
										* 
										1000000
									  ) 
									) 
					) AS 'PORCENJATE_QC_DEC',
			CONVERT(INT,  ( SUM(PPMS_CERTIFICACION) 
									/ ( CONVERT(DECIMAL(13,2), ( SUM(DEFECTOS_CERTIFICACION) +  SUM(DEFECTOS_PRODUCCION)  ) ) 
										/ 
										CONVERT(DECIMAL(13,2), ( SUM(MUESTRA_CERTIFICACION) + SUM(MUESTRA_PRODUCCION) ) ) 
										* 
										1000000
									  ) 
									) * 100 
					) AS 'PORCENTAJE_QC'
	FROM @VP_TBL_PPMS_CERTIFICACION_TOTAL_X_MES
	GROUP BY MES
	ORDER BY MES

	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////
--	USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT]
GO

/*	USE [PPMS_PEARL]
	EXEC	[dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT] 0,0, '2021-09-01', '2021-09-13'
*/

CREATE PROCEDURE [dbo].[PG_LI_PPMS_CERTIFICACION_TOTALES_REPORT]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_INICIAL				DATE,
	@PP_F_FIN					DATE
AS
	-- /////////SE CREA TABLA TEMPORAL PARA LOS TOTALES//////////////
	DECLARE @VP_TBL_PPMS_CERTIFICACION_TOTAL TABLE(
		FECHA					DATE,
		MUESTRA					INT,
		DEFECTOS				INT,
		PPMS_CERTIFICACION		INT,
		PPMS_PRODUCCION			INT
	)

	-- /////////SE CREA TABLA TEMPORAL PARA LOS DATOS DE CERTIFICACION//////////////
	DECLARE @VP_TBL_CERTIFICACION TABLE(
		FECHA		DATE,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INSERTAN LOS DATOS A LA TABLA//////////////
	INSERT INTO @VP_TBL_CERTIFICACION
	SELECT	CONVERT(DATE, fecha) AS 'FECHA', 
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1)+ SUM(cant2)+ SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt (NOLOCK)
	WHERE CONVERT(DATE, fecha) >= @PP_F_INICIAL
	AND CONVERT(DATE, fecha) <= @PP_F_FIN
	GROUP BY CONVERT(DATE, fecha)

	-- /////////SE CALCULAS LOS TOTALES//////////////
	INSERT INTO @VP_TBL_PPMS_CERTIFICACION_TOTAL
	SELECT	FECHA, MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS',
			0
	FROM @VP_TBL_CERTIFICACION
	WHERE DEFECTOS > 0
	ORDER BY FECHA

	-- /////////SE OBTIENE EL TOTAL DE MUESTRA Y DEFECTOS DE CERTIFICACION//////////////
	DECLARE @VP_TOTAL_MUESTRA_CERT DECIMAL(13,2) = 0,  @VP_TOTAL_DEFECTOS_CERT DECIMAL(13,2) = 0, @VP_TOTAL_PPMS_CERT INT = 0
	SELECT	@VP_TOTAL_MUESTRA_CERT	= SUM(MUESTRA), 
			@VP_TOTAL_DEFECTOS_CERT	= SUM(DEFECTOS) 
	FROM @VP_TBL_CERTIFICACION
	WHERE DEFECTOS > 0

	IF @VP_TOTAL_MUESTRA_CERT > 0
		SET @VP_TOTAL_PPMS_CERT = ( @VP_TOTAL_DEFECTOS_CERT / @VP_TOTAL_MUESTRA_CERT ) * 1000000

	-- /////////SE CREA TABLA PARA PPMS//////////////
	DECLARE @VP_TBL_PPMS TABLE(
		FECHA		DATE,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INGRESAN LOS DATOS A LA TABLA @VP_TBL_PPMS//////////////
	INSERT INTO @VP_TBL_PPMS
	SELECT	CONVERT(DATE, Date) AS FECHA, 
			SAMPLE_SIZE, 
			ISNULL((SELECT SUM([DEFECTOS].Cant)  FROM [PPMS_PEARL].[dbo].[DEFECTOS] (NOLOCK) WHERE [DEFECTOS].ID = [QC].ID), 0)
	FROM [PPMS_PEARL].[dbo].[QC] (NOLOCK)
	WHERE [Date] >= @PP_F_INICIAL
	AND [Date] <= @PP_F_FIN
	ORDER BY CONVERT(DATE, [Date])
	
	-- /////////SE INGRESAN LOS DATOS DE PPMS//////////////
	INSERT INTO @VP_TBL_PPMS_CERTIFICACION_TOTAL
	SELECT	FECHA, 
			SUM(MUESTRA) AS 'TOTAL_MUESTRA', 
			SUM(DEFECTOS) AS 'TOTAL_DEFECTOS', 
			0,
			( CASE WHEN (SUM(MUESTRA)) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_PPMS
	GROUP BY FECHA
	HAVING SUM(DEFECTOS) > 0
	ORDER BY FECHA

	-- /////////SE MUESTRA EL RESULTADO//////////////
	SELECT	
			SUM(MUESTRA) AS 'TOTAL_MUESTRA_FOO', 
			SUM(DEFECTOS) AS 'TOTAL_DEFECTOS_FOO' ,
			( CASE WHEN (SUM(MUESTRA)) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS_FOO',
			CONVERT(DECIMAL(13,2), (CONVERT(DECIMAL(13,2), @VP_TOTAL_PPMS_CERT) / (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000))) AS 'TOTAL_PORCENJATE_QC_FOO'
	FROM @VP_TBL_PPMS_CERTIFICACION_TOTAL
	HAVING SUM(DEFECTOS) > 0

	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////
--	USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_PPMS_CALIDAD_VS_PRODUCCION_GRAF_X_FECHA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_PPMS_CALIDAD_VS_PRODUCCION_GRAF_X_FECHA]
GO

/*
	EXEC	[dbo].[PG_LI_PPMS_CALIDAD_VS_PRODUCCION_GRAF_X_FECHA] 0, 144, '2021-09-01', '2021-09-13'
*/

CREATE PROCEDURE [dbo].[PG_LI_PPMS_CALIDAD_VS_PRODUCCION_GRAF_X_FECHA]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_INICIAL				DATE,
	@PP_F_FIN					DATE
AS
	
	-- /////////SE CREA TABLA TEMPORAL PARA LOS TOTALES//////////////
	DECLARE @VP_TBL_PPMS_CERTIFICACION_TOTAL TABLE(
		FECHA					DATE,
		MUESTRA					INT,
		DEFECTOS				INT,
		PPMS_CERTIFICACION		INT,
		PPMS_PRODUCCION			INT
	)

	-- /////////SE CREA TABLA TEMPORAL PARA LOS DATOS DE CERTIFICACION//////////////
	DECLARE @VP_TBL_CERTIFICACION TABLE(
		FECHA		DATE,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INSERTAN LOS DATOS A LA TABLA//////////////
	INSERT INTO @VP_TBL_CERTIFICACION
	SELECT	CONVERT(DATE, fecha) AS 'FECHA', 
			SUM(TOTAL) AS 'TOTAL_MUESTRA', 
			(SUM(cant1)+ SUM(cant2)+ SUM(cant3)) AS 'TOTAL_DEFECTOS'
	FROM certificacion_rpt (NOLOCK)
	WHERE CONVERT(DATE, fecha) >= @PP_F_INICIAL
	AND CONVERT(DATE, fecha) <= @PP_F_FIN
	GROUP BY CONVERT(DATE, fecha)

	-- /////////SE INGRESA DATOS A TABLA DE TOTALES//////////////
	INSERT INTO @VP_TBL_PPMS_CERTIFICACION_TOTAL
	SELECT	FECHA, 
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS',
			0
	FROM @VP_TBL_CERTIFICACION
	WHERE DEFECTOS > 0
	ORDER BY FECHA

	-- /////////SE CREA LA TABLA PARA LOS PPMS//////////////
	DECLARE @VP_TBL_PPMS TABLE(
		FECHA		DATE,
		MUESTRA		INT,
		DEFECTOS	INT
	)

	-- /////////SE INGRESAN LOS DATOS A LA TABLA PPMS//////////////
	INSERT INTO @VP_TBL_PPMS
	SELECT	CONVERT(DATE, Date) AS FECHA, 
			SAMPLE_SIZE, 
			ISNULL((SELECT SUM([DEFECTOS].Cant)  FROM [PPMS_PEARL].[dbo].[DEFECTOS] (NOLOCK)  WHERE [DEFECTOS].ID = [QC].ID), 0)
	FROM [PPMS_PEARL].[dbo].[QC] (NOLOCK)
	WHERE [Date] >= @PP_F_INICIAL
	AND [Date] <= @PP_F_FIN
	ORDER BY CONVERT(DATE, [Date])
	
	-- /////////SE INGRESA DATOS A TABLA DE TOTALES//////////////
	INSERT INTO @VP_TBL_PPMS_CERTIFICACION_TOTAL
	SELECT	FECHA,
			SUM(MUESTRA) AS 'TOTAL_MUESTRA', 
			SUM(DEFECTOS) AS 'TOTAL_DEFECTOS', 
			0,
			( CASE WHEN (SUM(MUESTRA)) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @VP_TBL_PPMS
	GROUP BY FECHA
	HAVING SUM(DEFECTOS) > 0
	ORDER BY FECHA

	-- /////////SE INGRESA DATOS A TABLA DE TOTALES//////////////
	SELECT	FECHA AS FECHA_QC_PRD,				 
			SUM(PPMS_CERTIFICACION)	AS TOTAL_PPMS_CALIDAD,	
			SUM(PPMS_PRODUCCION)	AS TOTAL_PPMS_PRD,
			CONVERT(DECIMAL(13,2), ((SUM(PPMS_CERTIFICACION)) / (CONVERT(DECIMAL(13,2), SUM(DEFECTOS)) / CONVERT(DECIMAL(13,2), SUM(MUESTRA)) * 1000000)) * 100 ) AS 'TOTAL_PORCENTAJE_QC'
	FROM @VP_TBL_PPMS_CERTIFICACION_TOTAL
	GROUP BY FECHA
	ORDER BY FECHA
	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////
--	USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_REPORT_X_FECHA_TURNO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_REPORT_X_FECHA_TURNO]
GO

/*
	EXEC	[dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_REPORT_X_FECHA_TURNO] 0, 144, '2021-09-13', 3
*/

CREATE PROCEDURE [dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_REPORT_X_FECHA_TURNO]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_FIN					DATE,
	@PP_TURNO					INT
AS
	
	-- //////SE CREA TABLA TEMPORAL//////////////////////////////////////
	DECLARE @TBL_MATERIAL_REVISADO TABLE(
	INSP_CERTI		VARCHAR(100),
	T_NORMAL		INT,
	T_EXTRA			INT,
	TOTAL			INT
	)

	-- //////SE AGREGAN LOS DATOS A LA TABLA TEMPORAL////////////////////
	INSERT INTO @TBL_MATERIAL_REVISADO
	SELECT	LTRIM(RTRIM(insp_certi)) AS INSP_CERTI,
			(SUM((CASE WHEN extra = 0 THEN total ELSE 0 END))) AS T_NORMAL, 
			(SUM((CASE WHEN extra = 1 THEN total ELSE 0 END))) AS T_EXTRA, 
			(SUM((CASE WHEN extra = 0 THEN total ELSE 0 END))) + 
			(SUM((CASE WHEN extra = 1 THEN total ELSE 0 END))) AS TOTAL
	FROM certificacion_rpt (NOLOCK)
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND certificacion_rpt.turno = @PP_TURNO  
	GROUP BY insp_certi
	HAVING	SUM(total) > 0
	AND	SUM(total) < 6000
	ORDER BY	SUM(total) DESC

	-- ////SE HACE LA UNION PARA OBTENER NOMBRE Y APELLIDO///////////////////
	SELECT CONCAT((SUBSTRING( CONCAT(EP_NOMBRE, ' '), 1, CHARINDEX(' ', CONCAT(EP_NOMBRE, ' ')))), ' ' + EP_APELLIDO_PATERNO) AS INSP_CERTI,	
		   T_NORMAL,
		   T_EXTRA,	
		   TOTAL
	FROM @TBL_MATERIAL_REVISADO
	INNER JOIN personal (NOLOCK) ON LTRIM(RTRIM(inspector_cal)) =  INSP_CERTI
	INNER JOIN HOWE.DBO.VISTA_GAFETES (NOLOCK) ON EN_NUM_EMP = noreloj
	ORDER BY TOTAL DESC
	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////
--	USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_DIA_X_TURNO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_DIA_X_TURNO]
GO

/*
	EXEC	[dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_DIA_X_TURNO] 0, 144, '2021-09-30', 1
*/

CREATE PROCEDURE [dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_DIA_X_TURNO]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_FIN					DATE,
	@PP_TURNO					INT
AS
	
	-- //////SE CREA TABLA TEMPORAL//////////////////////////////////////
	DECLARE @TBL_MATERIAL_REVISADO_DIA TABLE(
	SELLO			VARCHAR(100),
	INSPECTOR		VARCHAR(100),
	MUESTRA			INT,
	DEFECTOS		INT
	)

	-- //////SE INGRESAN LOS DATOS A LA TABLA TEMPORAL//////////////////////////////////////
	INSERT INTO @TBL_MATERIAL_REVISADO_DIA
	SELECT	SELLO_PAQ	AS SELLO,
			INSPECTOR_CAL	AS INSPECTOR, 
			SUM(total)	AS REVISADAS,
			( SUM(cant1) + SUM(cant2) + SUM(cant3)) AS DEFECTOS
	FROM certificacion_rpt (NOLOCK)
	INNER JOIN personal (NOLOCK) ON sello = sello_paq
	WHERE CONVERT(DATE, fecha) = @PP_F_FIN
	AND personal.turno = @PP_TURNO
	AND insp_certi <> '' 
	GROUP BY SELLO_PAQ, INSPECTOR_CAL

	-- //////SE CREA TABLA TEMPORAL//////////////////////////////////////
	DECLARE @TBL_MATERIAL_REVISADO_X_DIA_TOTAL TABLE(
	INSPECTOR				VARCHAR(100),
	TOTAL_MUESTRA			INT,
	TOTAL_DEFECTOS			INT,
	TOTAL_PPMS				INT
	)

	-- /////////SE CALCULAS LOS TOTALES Y SE MUESTRA EL RESULTADO//////////////
	INSERT INTO @TBL_MATERIAL_REVISADO_X_DIA_TOTAL
	SELECT	--CONCAT((SUBSTRING( CONCAT(EP_NOMBRE, ' '), 1, CHARINDEX(' ', CONCAT(EP_NOMBRE, ' ')))), ' ' + EP_APELLIDO_PATERNO) AS INSPECTOR, 
			(	SELECT TOP 1 CONCAT((SUBSTRING( CONCAT(EP_NOMBRE, ' '), 1, CHARINDEX(' ', CONCAT(EP_NOMBRE, ' ')))), ' ' + EP_APELLIDO_PATERNO)
				FROM HOWE.DBO.VISTA_GAFETES (NOLOCK)
				INNER JOIN personal (NOLOCK) ON LTRIM(RTRIM(inspector_cal)) =  LTRIM(RTRIM(INSPECTOR)) AND EN_NUM_EMP = noreloj	) AS INSPECTOR,
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @TBL_MATERIAL_REVISADO_DIA
	--INNER JOIN personal (NOLOCK) ON LTRIM(RTRIM(inspector_cal)) =  INSPECTOR
	--INNER JOIN HOWE.DBO.VISTA_GAFETES (NOLOCK) ON EN_NUM_EMP = noreloj
	WHERE DEFECTOS > 0
	--ORDER BY TOTAL_PPMS DESC

	-- /////////SE MUESTRA EL RESULTADO//////////////
	SELECT INSPECTOR,		
		   TOTAL_MUESTRA,	
		   TOTAL_DEFECTOS,	
		   TOTAL_PPMS		
	FROM @TBL_MATERIAL_REVISADO_X_DIA_TOTAL
	WHERE INSPECTOR IS NOT NULL
	ORDER BY TOTAL_PPMS DESC
	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////
--	USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_MES_X_TURNO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_MES_X_TURNO]
GO

/*
	EXEC	[dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_MES_X_TURNO] 0, 144, '2021-09-30', 1
*/

CREATE PROCEDURE [dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_MES_X_TURNO]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_FIN					DATE,
	@PP_TURNO					INT
AS
	
	-- /////////SE OBTIENE EL AÑO DE LA FECHA INICIAL///////////////////////////////////////
	DECLARE @VP_YEAR INT = YEAR(@PP_F_FIN)
	DECLARE @VP_MES INT = MONTH(@PP_F_FIN)

	-- //////SE CREA TABLA TEMPORAL//////////////////////////////////////
	DECLARE @TBL_MATERIAL_REVISADO_X_MES TABLE(
	INSPECTOR		VARCHAR(100),
	MUESTRA			INT,
	DEFECTOS		INT
	)

	-- //////SE INGRESAN LOS DATOS A LA TABLA TEMPORAL//////////////////////////////////////
	INSERT INTO @TBL_MATERIAL_REVISADO_X_MES
	SELECT	LTRIM(RTRIM(INSPECTOR_CAL)) 	AS INSPECTOR, 
			SUM(total)	AS REVISADAS,
			( SUM(cant1) + SUM(cant2) + SUM(cant3)) AS DEFECTOS
	FROM certificacion_rpt (NOLOCK)
	INNER JOIN personal (NOLOCK) ON sello = sello_paq
	WHERE YEAR(CONVERT(DATE, fecha)) = @VP_YEAR
	AND MONTH(CONVERT(DATE, fecha)) = @VP_MES
	AND CONVERT(DATE, fecha) <= @PP_F_FIN
	AND personal.turno = @PP_TURNO
	AND insp_certi <> '' 
	GROUP BY LTRIM(RTRIM(INSPECTOR_CAL)) 

	-- //////SE CREA TABLA TEMPORAL//////////////////////////////////////
	DECLARE @TBL_MATERIAL_REVISADO_X_MES_TOTAL TABLE(
	INSPECTOR				VARCHAR(100),
	TOTAL_MUESTRA			INT,
	TOTAL_DEFECTOS			INT,
	TOTAL_PPMS				INT
	)

	-- /////////SE CALCULAS LOS TOTALES Y SE MUESTRA EL RESULTADO//////////////
	INSERT INTO @TBL_MATERIAL_REVISADO_X_MES_TOTAL
	SELECT	--CONCAT((SUBSTRING( CONCAT(EP_NOMBRE, ' '), 1, CHARINDEX(' ', CONCAT(EP_NOMBRE, ' ')))), ' ' + EP_APELLIDO_PATERNO) AS INSPECTOR, 
			(	SELECT TOP 1 CONCAT((SUBSTRING( CONCAT(EP_NOMBRE, ' '), 1, CHARINDEX(' ', CONCAT(EP_NOMBRE, ' ')))), ' ' + EP_APELLIDO_PATERNO)
				FROM HOWE.DBO.VISTA_GAFETES (NOLOCK)
				INNER JOIN personal (NOLOCK) ON LTRIM(RTRIM(inspector_cal)) =  LTRIM(RTRIM(INSPECTOR)) AND EN_NUM_EMP = noreloj	) AS INSPECTOR,
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @TBL_MATERIAL_REVISADO_X_MES
	--INNER JOIN personal (NOLOCK) ON LTRIM(RTRIM(inspector_cal)) =  LTRIM(RTRIM(INSPECTOR))
	--INNER JOIN HOWE.DBO.VISTA_GAFETES (NOLOCK) ON EN_NUM_EMP = noreloj
	WHERE DEFECTOS > 0
	--ORDER BY TOTAL_PPMS DESC

	-- /////////SE MUESTRA EL RESULTADO//////////////
	SELECT INSPECTOR,		
		   TOTAL_MUESTRA,	
		   TOTAL_DEFECTOS,	
		   TOTAL_PPMS		
	FROM @TBL_MATERIAL_REVISADO_X_MES_TOTAL
	WHERE INSPECTOR IS NOT NULL
	ORDER BY TOTAL_PPMS DESC
	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////
--	USE [PPMS_PEARL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_MES_X_TURNO_MAYOR_800]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_MES_X_TURNO_MAYOR_800]
GO

/*
	EXEC	[dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_MES_X_TURNO_MAYOR_800] 0, 144, '2021-09-30', 2
*/

CREATE PROCEDURE [dbo].[PG_LI_MATERIAL_REVISADO_CERTIFICACION_ACUMULADO_MES_X_TURNO_MAYOR_800]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_F_FIN					DATE,
	@PP_TURNO					INT
AS
	
	-- /////////SE OBTIENE EL AÑO DE LA FECHA INICIAL///////////////////////////////////////
	DECLARE @VP_YEAR INT = YEAR(@PP_F_FIN)
	DECLARE @VP_MES INT = MONTH(@PP_F_FIN)

	-- //////SE CREA TABLA TEMPORAL//////////////////////////////////////
	DECLARE @TBL_MATERIAL_REVISADO_X_MES TABLE(
	INSPECTOR		VARCHAR(100),
	MUESTRA			INT,
	DEFECTOS		INT
	)

	-- //////SE INGRESAN LOS DATOS A LA TABLA TEMPORAL//////////////////////////////////////
	INSERT INTO @TBL_MATERIAL_REVISADO_X_MES
	SELECT	LTRIM(RTRIM(INSPECTOR_CAL)) 	AS INSPECTOR, 
			SUM(total)	AS REVISADAS,
			( SUM(cant1) + SUM(cant2) + SUM(cant3)) AS DEFECTOS
	FROM certificacion_rpt (NOLOCK)
	INNER JOIN personal (NOLOCK) ON sello = sello_paq
	WHERE YEAR(CONVERT(DATE, fecha)) = @VP_YEAR
	AND MONTH(CONVERT(DATE, fecha)) = @VP_MES
	AND CONVERT(DATE, fecha) <= @PP_F_FIN
	AND personal.turno = @PP_TURNO
	AND insp_certi <> '' 
	GROUP BY LTRIM(RTRIM(INSPECTOR_CAL)) 

	-- //////SE CREA TABLA TEMPORAL//////////////////////////////////////
	DECLARE @TBL_MATERIAL_REVISADO_X_MES_TOTAL TABLE(
	INSPECTOR				VARCHAR(100),
	TOTAL_MUESTRA			INT,
	TOTAL_DEFECTOS			INT,
	TOTAL_PPMS				INT
	)

	-- /////////SE CALCULAS LOS TOTALES Y SE MUESTRA EL RESULTADO//////////////
	INSERT INTO @TBL_MATERIAL_REVISADO_X_MES_TOTAL
	SELECT	--CONCAT((SUBSTRING( CONCAT(EP_NOMBRE, ' '), 1, CHARINDEX(' ', CONCAT(EP_NOMBRE, ' ')))), ' ' + EP_APELLIDO_PATERNO) AS INSPECTOR, 
			(	SELECT TOP 1 CONCAT((SUBSTRING( CONCAT(EP_NOMBRE, ' '), 1, CHARINDEX(' ', CONCAT(EP_NOMBRE, ' ')))), ' ' + EP_APELLIDO_PATERNO)
				FROM HOWE.DBO.VISTA_GAFETES (NOLOCK)
				INNER JOIN personal (NOLOCK) ON LTRIM(RTRIM(inspector_cal)) =  LTRIM(RTRIM(INSPECTOR)) AND EN_NUM_EMP = noreloj	) AS INSPECTOR,
			MUESTRA AS 'TOTAL_MUESTRA', 
			DEFECTOS AS 'TOTAL_DEFECTOS', 
			( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) AS 'TOTAL_PPMS'
	FROM @TBL_MATERIAL_REVISADO_X_MES
	--INNER JOIN personal (NOLOCK) ON LTRIM(RTRIM(inspector_cal)) =  LTRIM(RTRIM(INSPECTOR))
	--INNER JOIN HOWE.DBO.VISTA_GAFETES (NOLOCK) ON EN_NUM_EMP = noreloj
	WHERE DEFECTOS > 0
	AND ( CASE WHEN (MUESTRA) > 0 THEN CONVERT(INT, (CONVERT(DECIMAL(13,2), DEFECTOS) / CONVERT(DECIMAL(13,2), MUESTRA) * 1000000) )
				ELSE 0 END ) > 800
	--ORDER BY TOTAL_PPMS DESC

	-- /////////SE MUESTRA EL RESULTADO//////////////
	SELECT INSPECTOR,		
		   TOTAL_MUESTRA,	
		   TOTAL_DEFECTOS,	
		   TOTAL_PPMS		
	FROM @TBL_MATERIAL_REVISADO_X_MES_TOTAL
	WHERE INSPECTOR IS NOT NULL
	ORDER BY TOTAL_PPMS DESC
	-- //////////////////////////////////////////////////////////////
	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
