

USE PPMS_PEARL
	SELECT TOP 1 * FROM rechazos WHERE ORDEN = '43103'

	SELECT DISTINCT ITEM_NO FROM DATA_02.dbo.ccjoblin_sql WHERE JOBNO = '43103'
	
	SELECT * FROM numpart WHERE noparte = '200766DTX7'

	SELECT * FROM personal (NOLOCK) WHERE INSPECTOR_CAL = 'GLADYS DEL CARMEN MARTINEZ PATRACA'
	SELECT * FROM personal (NOLOCK) WHERE SELLO = '344'
	SELECT * FROM personal (NOLOCK) WHERE NORELOJ =14869

	SELECT	* FROM certificacion_rpt (NOLOCK)

	SELECT * FROM HOWE.DBO.VISTA_GAFETES (NOLOCK) WHERE  EN_NUM_EMP = 14869

	--	DEFECTO CRITICO: ( 'EE', 'ES', 'FL', 'LE', 'LM', 'MI', 'PF', 'PFL', 'PM', 'PSP', 'PS', 'PE', 'PSL', 'SB' )
	SELECT * FROM DEF WHERE CRITICO = 1

	SELECT * FROM [PPMS_PEARL].[dbo].DEF WHERE clave = 'TST'

	--UPDATE [PPMS_PEARL].[dbo].DEF
	--	SET TRADUCCION = 'VEINS' 
	--		--DESCRIPCION = 'NATURAL'
	--WHERE clave = 'VN'


	-- //////////PPMS////////////////////////////////////////////////////
	SELECT * FROM [PPMS_PEARL].[dbo].[QC] WHERE CONVERT(DATE, Date) = '2021-09-13' ORDER BY INSPECTOR
	SELECT * FROM [PPMS_PEARL].[dbo].[QC] WHERE ID = 303022 -- CONVERT(DATE, Date) = '2021-09-01'
	SELECT *   FROM [PPMS_PEARL].[dbo].[DEFECTOS] WHERE ID IN (303022) ORDER BY ID
	