

USE PPMS_PEARL
	SELECT * FROM numpart WHERE noparte = '200766DTX7'

	SELECT * FROM [PPMS_PEARL].[dbo].personal (NOLOCK) WHERE INSPECTOR_CAL = 'GLADYS DEL CARMEN MARTINEZ PATRACA'
	SELECT * FROM [PPMS_PEARL].[dbo].personal (NOLOCK) WHERE SELLO = '000'
	SELECT * FROM [PPMS_PEARL].[dbo].personal (NOLOCK) WHERE NORELOJ =14869

	SELECT	* FROM certificacion_rpt (NOLOCK)

	SELECT * FROM HOWE.DBO.VISTA_GAFETES (NOLOCK) WHERE  EN_NUM_EMP = 13367

	--	DEFECTO CRITICO: ( 'EE', 'ES', 'FL', 'LE', 'LM', 'MI', 'PF', 'PFL', 'PM', 'PSP', 'PS', 'PE', 'PSL', 'SB' )
	SELECT * FROM DEF WHERE CRITICO = 1

	SELECT * FROM [PPMS_PEARL].[dbo].DEF WHERE clave = 'TST'

	-- //////////PPMS////////////////////////////////////////////////////
	SELECT * FROM [PPMS_PEARL].[dbo].[QC] WHERE ID = CONVERT(DATE, Date) = '2021-11-15' AND [Shift] = 1 ORDER BY INSPECTOR

	SELECT * FROM [PPMS_PEARL].[dbo].[QC] WHERE ID = 303022 -- CONVERT(DATE, Date) = '2021-09-01'

	SELECT *   FROM [PPMS_PEARL].[dbo].[DEFECTOS] WHERE ID = 303022 -- IN (SELECT ID  FROM [PPMS_PEARL].[dbo].[QC] WHERE CONVERT(DATE, Date) = '2021-11-15' AND [Shift] = 1) ORDER BY ID
	
	 SELECT DEFECTO, SUM(Cant) AS TOTAL
	 FROM [PPMS_PEARL].[dbo].[DEFECTOS] 
	 WHERE ID IN (SELECT ID  FROM [PPMS_PEARL].[dbo].[QC] WHERE CONVERT(DATE, Date) = '2021-11-12' AND [Shift] = 1)
	 GROUP BY Defecto 
	 ORDER BY Defecto

	SELECT Machine,
			ISNULL((SELECT SUM([DEFECTOS].Cant)  FROM [PPMS_PEARL].[dbo].[DEFECTOS] (NOLOCK) WHERE [DEFECTOS].ID = [QC].ID), 0)	 
	FROM 
	[PPMS_PEARL].[dbo].[QC] 
	WHERE CONVERT(DATE, Date) = '2021-11-15' 
	GROUP BY Machine
	ORDER BY Machine
	

	SELECT * FROM  [DATA_02].dbo.imlocfil_sql where loc = 'mfp'

	-- ORDEN CON KIT U 48125
	SELECT * FROM [DATA_02].dbo.jobs_piso WHERE  jobno = '48125'
		
	SELECT * FROM [MATERIAL_PROGRAMADO_LOG] (NOLOCK) WHERE SERIAL LIKE '46500%' ORDER BY SERIAL, K_MATERIAL_PROGRAMADO_LOG

	SELECT * FROM [DATA_02].dbo.ccjoblin_sql WHERE JOBNO = '43929'

	SELECT * FROM [DATA_02].dbo.ccjobhdr_sql WHERE jobno = '40798'

	SELECT * --SUM(OriginalQty * patternsper)
	FROM [DATA_02].dbo.ccjoblin_sql WHERE  jobno = '45250'

	SELECT * FROM [DATA_02].dbo.cccuthst_sql WHERE  jobno = '45250' ORDER BY LOTNO
	
	select * from [PPMS_PEARL].[dbo].rechazos WHERE ORDEN = 48100
	 
	select * from [PPMS_PEARL].[dbo].rechazos where ORDEN = 45250
	--ORDEN < 50000 
	--order by ORDEN desc
	
	SELECT * FROM [PPMS_PEARL].[dbo].[QC] WHERE Order_No = '48100' -- ID IN (303022)

	SELECT * FROM [PPMS_PEARL].[dbo].[DEFECTOS] WHERE ID IN (303022)

	SELECT * FROM [BD_GENERAL].[dbo].USUARIO_PEARL 

	SELECT * FROM DATA_02.dbo.pearl_log WHERE  screen_opt = 'RECHAZOS'

	SELECT * FROM DATA_02.dbo.pearl_log WHERE jobno = '48336'

